#!/bin/sh

DIRNAME="$(dirname $0)"
if [ "DIRNAME" = "" ] ; then
DIRNAME=$(dirname $(which $0))
fi
DIRNAME=$(cd $DIRNAME && pwd)

if [ "$1" = --cflags ] ; then
echo -I$DIRNAME/include
elif  [ "$1" = --libs ] ; then
echo -Wl,--whole-archive $DIRNAME/src/.libs/libssim.a -Wl,--no-whole-archive
else
echo "Usage: $(basename $0)  (--cflags|--libs)"
exit 1
fi

