#!/bin/sh 

if [ -f locallibs/external_env_file ]; then . locallibs/external_env_file; fi

if [ "$LOCALCC" = "" ] ; then
        LOCALCC=gcc
fi

if [ "$LOCALCXX" = "" ] ; then
        LOCALCXX=g++
fi

CC=$LOCALCC
CXX=$LOCALCXX
CFLAGS=$LOCALCFLAGS

if [ "$1" = "-f" ] ; then
     echo "skip -f option"
     shift
fi
if [ "$1" = "-shared" ] ; then
     shift
     shared_mode="--enable-shared --disable-static"
fi

if [ -n "$BOOST" ]; then
      WITH_PARAMS="$WITH_PARAMS --with-boost=$BOOST"
fi
if [ -n "$BOOST_LIB" ]; then
      WITH_PARAMS="$WITH_PARAMS --with-boost-libdir=$BOOST_LIB"
fi
if [ -n "$PION" ]; then
      WITH_PARAMS="$WITH_PARAMS --with-pion=$PION"
fi
if [ "$BUILD_TESTS" = "1" ]; then
      WITH_PARAMS="$WITH_PARAMS --enable-xp-testing"
fi


set -x
pwd
autoreconf --force --install && ./configure --silent CFLAGS=$CFLAGS CXXFLAGS=$CFLAGS CC="$CC" CXX="$CXX" $WITH_PARAMS $shared_mode $@
