#!/bin/bash 

CXXFLAGS="$EXTERNAL_CXXFLAGS $CXXFLAGS"

if [ "$1" = "-f" ] ; then
     echo "skip -f option"
     shift
fi
if [ "$1" = "-shared" ] ; then
     shift
     shared_mode="--enable-shared --disable-static"
fi

if [ -n "$BOOST" ]; then
      WITH_PARAMS="$WITH_PARAMS --with-boost=$BOOST"
fi
if [ -n "$BOOST_LIB" ]; then
      WITH_PARAMS="$WITH_PARAMS --with-boost-libdir=$BOOST_LIB"
fi
if [ "$BUILD_TESTS" = "1" ]; then
      WITH_PARAMS="$WITH_PARAMS --enable-xp-testing"
fi

if [[ -n "$TOOLS" ]]; then
    tcl_flag="--with-tcl=$TOOLS"
fi;

WITH_PARAMS="$WITH_PARAMS --with-xml-prefix=$LIBXML2 --with-check=$LIBCHECK"

[ -n $ORACLE_INSTANT ] && export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${ORACLE_INSTANT}"

pwd
autoreconf --force --install && ./configure --silent --enable-silent-rules CC="$CC" CXX="$CXX" CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" $tcl_flag $WITH_PARAMS $shared_mode $@
