#!/bin/sh


for i in /bin/nawk /usr/bin/nawk /bin/awk /usr/bin/awk /usr/bin/gawk \
/usr/local/bin/gawk /usr/local/bin/nawk ; do
	if [ -f $i ] ; then
	 	AWK=$i 
		break
    fi
done
if [ "" == "$AWK" ] ; then
    echo no awk
    exit 1
fi

for i in astra.log  daemon.log  logairimp.log  monitor.log  system.log  tclmon.log ; do
	mv $i `basename $i .log`.moved	
done

PS | $AWK '/monitor|logger|astra/ {print $2}' | xargs kill -USR1
