#!/bin/bash
set -euo pipefail
PASS=${1?NO_PASSWORD}

CMD="psql --no-psqlrc ${PASS}"

rm -f ok oldlog2 now.run
if  [ -f oldlog1 ] ; then
    mv oldlog1 oldlog2
fi
if [ -f log ] ; then
    mv log oldlog1
fi

if [ "${1}" = "NO_POSTGRES_CONNECT" ]; then
    echo PostgreSQL Connection not set >> log
    exit
fi

for f in *.ldr ; do
    python3 make_copy_cmd.py $f | $CMD 2>&1 | tee -a log
    if grep -Ec "ERROR:" log; then
        echo Errors in $PWD $PASS | tee -a log
        exit 1
    else
        echo OK>ok
    fi
done
