#!/bin/sh

DIRNAME="$(dirname $0)"
if [ "DIRNAME" = "" ] ; then
DIRNAME=$(dirname $(which $0))
fi
DIRNAME=$(cd "$DIRNAME" && pwd)
CONF_NAME="$DIRNAME/libjms-conf"
if  [ -f "$CONF_NAME" ] ; then
. "$CONF_NAME"
fi

if [ "$1" = --cflags ] ; then
echo -I$DIRNAME/include
elif  [ "$1" = --libs ] ; then
echo $DIRNAME/src/.libs/libjms.a $LIBJMS_DEP_LIBS
else
echo "Usage: $(basename $0)  (--cflags|--libs)"
exit 1
fi

