CREATE TABLE AIRLINES (
    AIRCODE VARCHAR(3),
    CITY VARCHAR(3),
    CODE VARCHAR(3) NOT NULL,
    CODE_ICAO VARCHAR(3),
    CODE_ICAO_LAT VARCHAR(3),
    CODE_LAT VARCHAR(3),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    SHORT_NAME VARCHAR(50),
    SHORT_NAME_LAT VARCHAR(50),
    TID INTEGER NOT NULL,
    TID_SYNC INTEGER
);

