CREATE TABLE AIRPS (
    CITY VARCHAR(3) NOT NULL,
    CODE VARCHAR(3) NOT NULL,
    CODE_ICAO VARCHAR(4),
    CODE_ICAO_LAT VARCHAR(4),
    CODE_LAT VARCHAR(3),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL,
    TID_SYNC INTEGER
);

