CREATE TABLE AODB_EVENTS (
    AIRLINE VARCHAR(3) NOT NULL,
    FILENAME VARCHAR(50) NOT NULL,
    MSG VARCHAR(1000) NOT NULL,
    POINT_ADDR VARCHAR(6) NOT NULL,
    RECORD VARCHAR(4000) NOT NULL,
    REC_NO INTEGER NOT NULL,
    TIME TIMESTAMP(0) NOT NULL,
    TYPE VARCHAR(3) NOT NULL
);

