CREATE TABLE AODB_UNACCOMP (
    GRP_ID INTEGER NOT NULL,
    NUM SMALLINT NOT NULL,
    POINT_ADDR VARCHAR(6) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_CABIN SMALLINT NOT NULL,
    RECORD VARCHAR(1000) NOT NULL
);

