CREATE TABLE ARX_BAG_TAGS (
    BAG_NUM SMALLINT,
    COLOR VARCHAR(2),
    GRP_ID INTEGER NOT NULL,
    NO BIGINT NOT NULL,
    NUM SMALLINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PR_PRINT SMALLINT NOT NULL,
    TAG_TYPE VARCHAR(5) NOT NULL
);

