CREATE TABLE ARX_STAT_ZAMAR (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP VARCHAR(3) NOT NULL,
    AMOUNT_FAULT INTEGER NOT NULL,
    AMOUNT_OK INTEGER NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    SBDO_TYPE VARCHAR(10) NOT NULL,
    TIME TIMESTAMP(0) NOT NULL
);

