CREATE TABLE ARX_UNACCOMP_BAG_INFO (
    AIRLINE VARCHAR(3),
    FLT_NO INTEGER,
    GRP_ID INTEGER NOT NULL,
    NAME VARCHAR(64),
    NUM SMALLINT NOT NULL,
    ORIGINAL_TAG_NO VARCHAR(15),
    PART_KEY TIMESTAMP(0) NOT NULL,
    SCD TIMESTAMP(0),
    SUFFIX VARCHAR(1),
    SURNAME VARCHAR(64)
);

