CREATE TABLE ARX_PAX_DOCO (
    APPLIC_COUNTRY VARCHAR(3),
    BIRTH_PLACE VARCHAR(35),
    EXPIRY_DATE TIMESTAMP(0),
    ISSUE_DATE TIMESTAMP(0),
    ISSUE_PLACE VARCHAR(35),
    NO VARCHAR(25),
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    SCANNED_ATTRS INTEGER,
    SUBTYPE VARCHAR(1),
    TYPE VARCHAR(2)
);

