CREATE TABLE ARX_STAT_AD (
BAG_AMOUNT INT,
BAG_WEIGHT INT,
CLASS VARCHAR(1) NOT NULL,
CLIENT_TYPE VARCHAR(5) NOT NULL,
DESK VARCHAR(6) NOT NULL,
PART_KEY TIMESTAMP NOT NULL,
PAX_ID INT NOT NULL,
PNR VARCHAR(20),
POINT_ID INT NOT NULL,
SCD_OUT TIMESTAMP NOT NULL,
SEAT_NO VARCHAR(50),
SEAT_NO_LAT VARCHAR(50),
STATION VARCHAR(6)
);
