CREATE TABLE ARX_TRIP_DELAYS (
    DELAY_CODE VARCHAR(3) NOT NULL,
    DELAY_NUM SMALLINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    TIME TIMESTAMP(0) NOT NULL
);

