CREATE TABLE ARX_TRIP_LOAD (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    CARGO INTEGER NOT NULL,
    MAIL INTEGER NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ARV INTEGER NOT NULL,
    POINT_DEP INTEGER NOT NULL
);

