CREATE TABLE ARX_VALUE_BAG (
    GRP_ID INTEGER NOT NULL,
    NUM SMALLINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    TAX DECIMAL(4,1),
    TAX_ID INTEGER,
    TAX_TRFER SMALLINT,
    VALUE DECIMAL(12,2) NOT NULL,
    VALUE_CUR VARCHAR(3) NOT NULL
);

