CREATE TABLE ARX_STAT_ZAMAR (
    TIME TIMESTAMP NOT NULL,
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP VARCHAR(3) NOT NULL,
    AMOUNT_OK INT NOT NULL,
    AMOUNT_FAULT INT NOT NULL,
    PART_KEY TIMESTAMP NOT NULL
);
