CREATE TABLE ARX_STAT_SERVICES (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RECEIPT_NO VARCHAR(30),
    RFIC VARCHAR(1),
    RFISC VARCHAR(15) NOT NULL,
    SCD_OUT TIMESTAMP(0) NOT NULL
);

