CREATE TABLE ARX_TRFER_PAX_STAT (
    BAG_AMOUNT INTEGER,
    BAG_WEIGHT INTEGER,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER,
    POINT_ID INTEGER NOT NULL,
    RK_WEIGHT INTEGER,
    SCD_OUT TIMESTAMP(0) NOT NULL,
    SEGMENTS VARCHAR(4000) NOT NULL
);

