CREATE TABLE ARX_PAY_SERVICES (
    AIRLINE VARCHAR(3) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    DOC_ID VARCHAR(100) NOT NULL,
    GRP_ID INTEGER NOT NULL,
    LIST_ID INTEGER,
    NAME_VIEW VARCHAR(100) NOT NULL,
    NAME_VIEW_LAT VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(6) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PASS_ID INTEGER NOT NULL,
    PAX_ID INTEGER NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    RFISC VARCHAR(15) NOT NULL,
    SEG_ID INTEGER NOT NULL,
    SERVICE_TYPE VARCHAR(1) NOT NULL,
    SVC_ID INTEGER NOT NULL,
    TICKET_CPN VARCHAR(1) NOT NULL,
    TICKNUM VARCHAR(15) NOT NULL,
    TIME_PAID TIMESTAMP(0) NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

