CREATE TABLE BAG_TYPE_LIST_ITEMS (
    AIRLINE VARCHAR(3) NOT NULL,
    BAG_TYPE VARCHAR(15) NOT NULL,
    CATEGORY SMALLINT NOT NULL,
    DESCR VARCHAR(150),
    DESCR_LAT VARCHAR(150),
    LIST_ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50) NOT NULL,
    VISIBLE SMALLINT NOT NULL
);

