CREATE TABLE BAG_TYPES (
    CODE SMALLINT NOT NULL,
    DESCR VARCHAR(2000),
    DESCR_LAT VARCHAR(2000),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    REM_CODE_LCI VARCHAR(4),
    REM_CODE_LDM VARCHAR(3)
);

