CREATE TABLE BALANCE_SETS (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3) NOT NULL,
    BALANCE_TYPE VARCHAR(5) NOT NULL,
    BORT VARCHAR(10),
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL
);

