CREATE TABLE BP_MODELS (
    DEV_MODEL VARCHAR(10) NOT NULL,
    FMT_TYPE VARCHAR(10) NOT NULL,
    FORM_TYPE VARCHAR(5) NOT NULL,
    ID INTEGER NOT NULL,
    OP_TYPE VARCHAR(10) NOT NULL,
    VERSION INTEGER NOT NULL
);

