CREATE TABLE BP_SET (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    BP_TYPE VARCHAR(5) NOT NULL,
    CLASS VARCHAR(1),
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    OP_TYPE VARCHAR(10) NOT NULL
);

