CREATE TABLE BRAND_FARES (
    AIRLINE VARCHAR(3) NOT NULL,
    BRAND VARCHAR(10) NOT NULL,
    FARE_BASIS VARCHAR(15) NOT NULL,
    ID INTEGER NOT NULL,
    SALE_FIRST_DATE TIMESTAMP(0) NOT NULL,
    SALE_LAST_DATE TIMESTAMP(0)
);

