CREATE TABLE CACHE_TABLES (
    CODE VARCHAR(30) NOT NULL,
    DB_TABLES VARCHAR(100),
    DELETE_RIGHT SMALLINT,
    DELETE_SQL VARCHAR(4000),
    EVENT_TYPE VARCHAR(3),
    INSERT_RIGHT SMALLINT,
    INSERT_SQL VARCHAR(4000),
    KEEP_DELETED_ROWS SMALLINT DEFAULT 0 NOT NULL,
    KEEP_LOCALLY SMALLINT DEFAULT 0 NOT NULL,
    LOGGING SMALLINT NOT NULL,
    NEED_REFRESH SMALLINT DEFAULT 1 NOT NULL,
    REFRESH_SQL VARCHAR(4000),
    SELECT_RIGHT SMALLINT,
    SELECT_SQL VARCHAR(4000),
    TID INTEGER NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    UPDATE_RIGHT SMALLINT,
    UPDATE_SQL VARCHAR(4000)
);

