CREATE TABLE CACHE_CHILD_FIELDS (
    AUTO_INSERT SMALLINT NOT NULL,
    CACHE_CHILD VARCHAR(30) NOT NULL,
    CACHE_PARENT VARCHAR(30) NOT NULL,
    CHECK_EQUAL SMALLINT NOT NULL,
    FIELD_CHILD VARCHAR(30),
    FIELD_PARENT VARCHAR(30) NOT NULL,
    MODIFY_VAR VARCHAR(30),
    READ_ONLY SMALLINT NOT NULL,
    SELECT_VAR VARCHAR(30)
);

