CREATE TABLE CITIES (
    CODE VARCHAR(3) NOT NULL,
    CODE_LAT VARCHAR(3),
    COUNTRY VARCHAR(2) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL,
    TID_SYNC INTEGER,
    TZ_REGION VARCHAR(50)
);

