CREATE TABLE CKIN_REM_TYPES (
    CODE VARCHAR(4) NOT NULL,
    CODE_LAT VARCHAR(4) NOT NULL,
    GRP_ID SMALLINT NOT NULL,
    ID INTEGER NOT NULL,
    IS_IATA SMALLINT NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    NAME_LAT VARCHAR(200),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL
);

