CREATE TABLE CLIENT_TYPES (
    CODE VARCHAR(5) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PRIORITY SMALLINT NOT NULL,
    SHORT_NAME VARCHAR(10) NOT NULL,
    SHORT_NAME_LAT VARCHAR(10)
);

