CREATE TABLE COMP_RATES (
    COLOR VARCHAR(10) NOT NULL,
    COMP_ID INTEGER NOT NULL,
    NUM SMALLINT NOT NULL,
    RATE DECIMAL(12,2) NOT NULL,
    RATE_CUR VARCHAR(3) NOT NULL,
    X SMALLINT NOT NULL,
    Y SMALLINT NOT NULL
);

