CREATE TABLE COMP_LAYER_TYPES (
    CODE VARCHAR(10) NOT NULL,
    COLOR VARCHAR(10) NOT NULL,
    DEL_IF_COMP_CHG SMALLINT NOT NULL,
    FIGURE VARCHAR(20),
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PRIORITY SMALLINT NOT NULL,
    PR_OCCUPY SMALLINT NOT NULL
);

