CREATE TABLE COMP_ELEM_TYPES (
    CODE VARCHAR(1) NOT NULL,
    FILENAME VARCHAR(20) NOT NULL,
    IMAGE bytea NOT NULL,
    NAME VARCHAR(50),
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    PR_SEAT SMALLINT NOT NULL,
    TIME_CREATE TIMESTAMP(0) NOT NULL
);
