CREATE TABLE COMPS (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    BORT VARCHAR(10),
    CLASSES VARCHAR(20),
    COMP_ID INTEGER NOT NULL,
    CRAFT VARCHAR(3) NOT NULL,
    DESCR VARCHAR(100),
    PR_LAT_SEAT SMALLINT NOT NULL,
    TIME_CREATE TIMESTAMP(0) NOT NULL
);

