CREATE TABLE CONFIRM_PRINT (
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    EMD_COUPON SMALLINT,
    EMD_NO VARCHAR(15),
    FROM_SCAN_CODE SMALLINT,
    GRP_ID INTEGER NOT NULL,
    HALL_ID INTEGER,
    OP_TYPE VARCHAR(10) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_PRINT SMALLINT NOT NULL,
    SEAT_NO VARCHAR(50),
    SEAT_NO_LAT VARCHAR(50),
    TIME_PRINT TIMESTAMP(0) NOT NULL,
    VOUCHER VARCHAR(2)
);

