CREATE TABLE CONFIRMATION_SETS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3),
    BRAND_AIRLINE VARCHAR(3),
    BRAND_CODE VARCHAR(10),
    CLASS VARCHAR(1),
    DCS_ACTION VARCHAR(20) NOT NULL,
    FQT_AIRLINE VARCHAR(3),
    FQT_TIER_LEVEL VARCHAR(50),
    ID INTEGER NOT NULL,
    REM_CODE VARCHAR(4),
    RFISC VARCHAR(15),
    SUBCLASS VARCHAR(1),
    TEXT VARCHAR(250) NOT NULL,
    TEXT_LAT VARCHAR(250) NOT NULL
);

