CREATE TABLE CONFIRM_PRINT_VO_UNREG (
    DESK VARCHAR(6) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(64),
    POINT_ID INTEGER NOT NULL,
    PR_PRINT SMALLINT NOT NULL,
    SCD_OUT TIMESTAMP(0) NOT NULL,
    SURNAME VARCHAR(64) NOT NULL,
    TIME_PRINT TIMESTAMP(0) NOT NULL,
    VOUCHER VARCHAR(2) NOT NULL
);

