CREATE TABLE COUNTERS_BY_SUBCLS (
    BAG_WEIGHT INTEGER NOT NULL,
    CHILD SMALLINT NOT NULL,
    CLASS VARCHAR(1),
    FEMALE SMALLINT NOT NULL,
    INFANT SMALLINT NOT NULL,
    MALE SMALLINT NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RK_WEIGHT INTEGER NOT NULL,
    SUBCLASS VARCHAR(1)
);

