CREATE TABLE COUNTRIES (
    CODE VARCHAR(2) NOT NULL,
    CODE_ISO VARCHAR(3),
    CODE_LAT VARCHAR(2),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL,
    TID_SYNC INTEGER
);

