CREATE TABLE COUNTERS2 (
    AVAIL SMALLINT NOT NULL,
    CLASS VARCHAR(1) NOT NULL,
    CRS_OK SMALLINT NOT NULL,
    CRS_TRANZIT SMALLINT NOT NULL,
    FREE_GOSHOW SMALLINT NOT NULL,
    FREE_OK SMALLINT NOT NULL,
    GOSHOW SMALLINT NOT NULL,
    JMP_GOSHOW SMALLINT NOT NULL,
    JMP_NOOCCUPY SMALLINT NOT NULL,
    JMP_OK SMALLINT NOT NULL,
    JMP_TRANZIT SMALLINT NOT NULL,
    NOOCCUPY SMALLINT NOT NULL,
    OK SMALLINT NOT NULL,
    POINT_ARV INTEGER NOT NULL,
    POINT_DEP INTEGER NOT NULL,
    TRANZIT SMALLINT NOT NULL
);

