CREATE TABLE CRS_TRANSFER (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_ARV VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    FLT_NO INTEGER NOT NULL,
    LOCAL_DATE SMALLINT NOT NULL,
    PNR_ID INTEGER NOT NULL,
    SUBCLASS VARCHAR(1) NOT NULL,
    SUFFIX VARCHAR(1),
    TRANSFER_NUM SMALLINT NOT NULL
);

