CREATE TABLE CRS_DATA (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AVAIL SMALLINT,
    CFG SMALLINT,
    CLASS VARCHAR(1) NOT NULL,
    PAD SMALLINT,
    POINT_ID INTEGER NOT NULL,
    RESA SMALLINT,
    SENDER VARCHAR(7) NOT NULL,
    SYSTEM VARCHAR(3) NOT NULL,
    TRANZIT SMALLINT
);

