CREATE TABLE CRS_DATA_STAT (
    CRS VARCHAR(7) NOT NULL,
    LAST_AVAIL TIMESTAMP(0),
    LAST_CFG TIMESTAMP(0),
    LAST_RBD TIMESTAMP(0),
    LAST_RESA TIMESTAMP(0),
    LAST_TRANZIT TIMESTAMP(0),
    POINT_ID INTEGER NOT NULL,
    PR_PNL SMALLINT DEFAULT 0 NOT NULL
);

