CREATE TABLE CRS_PAX_ASVC (
    EMD_COUPON SMALLINT,
    EMD_NO VARCHAR(15),
    EMD_TYPE VARCHAR(1),
    PAX_ID INTEGER,
    REM_STATUS VARCHAR(2) NOT NULL,
    RFIC VARCHAR(1),
    RFISC VARCHAR(15),
    SERVICE_NAME VARCHAR(30),
    SERVICE_QUANTITY SMALLINT,
    SSR_CODE VARCHAR(4)
);

