CREATE TABLE CRS_SET (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3),
    CRS VARCHAR(7) NOT NULL,
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    PRIORITY SMALLINT DEFAULT 0 NOT NULL,
    PR_NUMERIC_PNL SMALLINT NOT NULL
);

