CREATE TABLE CRS_PAX_DOCA (
    ADDRESS VARCHAR(35),
    CITY VARCHAR(35),
    COUNTRY VARCHAR(3),
    PAX_ID INTEGER NOT NULL,
    POSTAL_CODE VARCHAR(17),
    REGION VARCHAR(35),
    REM_CODE VARCHAR(5) NOT NULL,
    REM_STATUS VARCHAR(2),
    TYPE VARCHAR(1)
);

