CREATE TABLE CRS_PAX_DOCO (
    APPLIC_COUNTRY VARCHAR(3),
    BIRTH_PLACE VARCHAR(35),
    ISSUE_DATE TIMESTAMP(0),
    ISSUE_PLACE VARCHAR(35),
    NO VARCHAR(25),
    PAX_ID INTEGER NOT NULL,
    REM_CODE VARCHAR(5) NOT NULL,
    REM_STATUS VARCHAR(2),
    TYPE VARCHAR(2)
);

