CREATE TABLE CRS_PNR (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_ARV_FINAL VARCHAR(3),
    CLASS VARCHAR(1) NOT NULL,
    GRP_NAME VARCHAR(64),
    PNR_ID INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PRIORITY VARCHAR(64),
    SENDER VARCHAR(7) NOT NULL,
    STATUS VARCHAR(3),
    SUBCLASS VARCHAR(1) NOT NULL,
    SYSTEM VARCHAR(3) NOT NULL,
    TID INTEGER NOT NULL
);

