CREATE TABLE CRYPT_FILE_PARAMS (
    CERTNAME VARCHAR(50) NOT NULL,
    DESK VARCHAR(6),
    DESK_GRP_ID INTEGER NOT NULL,
    KEYNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PKCS_ID INTEGER NOT NULL,
    SEND_COUNT SMALLINT NOT NULL
);

