CREATE TABLE CRYPT_TERM_CERT (
    CERTIFICATE VARCHAR(4000) NOT NULL,
    DESK VARCHAR(6),
    DESK_GRP_ID INTEGER NOT NULL,
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP(0) NOT NULL,
    PKCS_ID INTEGER,
    PR_DENIAL SMALLINT NOT NULL
);

