CREATE TABLE CUSTOM_ALARM_SETS (
    AIRLINE VARCHAR(3) NOT NULL,
    ALARM INTEGER NOT NULL,
    BRAND_AIRLINE VARCHAR(3),
    BRAND_CODE VARCHAR(10),
    FQT_AIRLINE VARCHAR(3),
    FQT_TIER_LEVEL VARCHAR(50),
    ID INTEGER NOT NULL,
    RFISC VARCHAR(15),
    RFISC_TLG VARCHAR(15)
);

