CREATE TABLE CUSTOM_ALARM_TYPES (
    AIRLINE VARCHAR(3),
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NAME_LAT VARCHAR(100) NOT NULL,
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL
);

