CREATE TABLE DATE_TIME_ZONESPEC (
    COUNTRY VARCHAR(2),
    DST_ABBR VARCHAR(5),
    DST_ADJUSTMENT VARCHAR(9),
    DST_END_DATE_RULE VARCHAR(10),
    DST_NAME VARCHAR(50),
    DST_START_DATE_RULE VARCHAR(10),
    END_TIME VARCHAR(9),
    GMT_OFFSET VARCHAR(9),
    ID VARCHAR(50) NOT NULL,
    PR_DEL SMALLINT NOT NULL,
    START_TIME VARCHAR(9),
    STD_ABBR VARCHAR(5),
    STD_NAME VARCHAR(50),
    TID INTEGER NOT NULL
);

