CREATE TABLE DEL_VO (
    COUPON_NO SMALLINT,
    FULL_NAME VARCHAR(129) NOT NULL,
    PERS_TYPE VARCHAR(2) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    REG_NO SMALLINT NOT NULL,
    REM_CODES VARCHAR(500),
    TICKET_NO VARCHAR(15),
    TOTAL INTEGER NOT NULL,
    VOUCHER VARCHAR(2) NOT NULL
);

