CREATE TABLE DEV_EVENT_CMD (
    BINARY_VAL SMALLINT NOT NULL,
    CMD_DATA VARCHAR(100) NOT NULL,
    CMD_FMT_FILE SMALLINT NOT NULL,
    CMD_FMT_HEX SMALLINT NOT NULL,
    CMD_ORDER SMALLINT NOT NULL,
    DESK_GRP_ID INTEGER,
    DEV_MODEL VARCHAR(10),
    ERROR_ABORT SMALLINT NOT NULL,
    ERROR_LOG SMALLINT NOT NULL,
    ERROR_SHOW SMALLINT NOT NULL,
    EVENT_NAME VARCHAR(30) NOT NULL,
    FMT_TYPE VARCHAR(10) NOT NULL,
    POSTED SMALLINT NOT NULL,
    SESS_TYPE VARCHAR(10),
    WAIT_PRIOR_CMD SMALLINT NOT NULL
);

