CREATE TABLE DEV_MODEL_DEFAULTS (
    DEV_MODEL VARCHAR(10) NOT NULL,
    FMT_TYPE VARCHAR(10) NOT NULL,
    OP_TYPE VARCHAR(10) NOT NULL,
    SESS_TYPE VARCHAR(10) NOT NULL,
    TERM_MODE VARCHAR(10) NOT NULL
);

