CREATE TABLE DEV_MODEL_PARAMS (
    DESK_GRP_ID INTEGER,
    DEV_MODEL VARCHAR(10),
    EDITABLE SMALLINT NOT NULL,
    FMT_TYPE VARCHAR(10),
    PARAM_NAME VARCHAR(30) NOT NULL,
    PARAM_VALUE VARCHAR(100),
    PR_SESS_PARAM SMALLINT,
    SESS_TYPE VARCHAR(10),
    SUBPARAM_NAME VARCHAR(20)
);

