CREATE TABLE EDI_HELP (
    ADDRESS VARCHAR(40),
    DATE1 TIMESTAMP(0),
    INSTANCE VARCHAR(3),
    INTMSGID VARCHAR(24),
    PULT VARCHAR(6),
    SESSION_ID BIGINT DEFAULT 0 NOT NULL,
    TEXT VARCHAR(1000),
    TIMEOUT TIMESTAMP(0)
);

