CREATE TABLE EDI_STR_MESSAGE (
    GRP_NUM SMALLINT,
    MAXPOS SMALLINT,
    MESSAGE VARCHAR(6) NOT NULL,
    POS SMALLINT NOT NULL,
    R INTEGER NOT NULL,
    S VARCHAR(1) NOT NULL,
    TAG VARCHAR(3)
);

