CREATE TABLE EDIFACT_PROFILES (
    CTRL_AGENCY VARCHAR(2) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    SUB_VERSION VARCHAR(3) NOT NULL,
    SYNTAX_NAME VARCHAR(4) NOT NULL,
    SYNTAX_VER BIGINT NOT NULL,
    VERSION VARCHAR(3) NOT NULL
);

