CREATE TABLE EDISESSION (
    ACCESS_KEY VARCHAR(10),
    FLAGS BIGINT,
    IDA INTEGER NOT NULL,
    INTMSGID VARCHAR(24) NOT NULL,
    LAST_ACCESS TIMESTAMP(0) DEFAULT NOW() NOT NULL,
    MSG_ID VARCHAR(10),
    OTHERCARF VARCHAR(50),
    OTHERREF VARCHAR(14),
    OTHERREFNUM SMALLINT,
    OURCARF VARCHAR(17) NOT NULL,
    OURREF VARCHAR(14) NOT NULL,
    OURREFNUM SMALLINT NOT NULL,
    PRED_P VARCHAR(6),
    PULT VARCHAR(6),
    SESSDATECR TIMESTAMP(0) NOT NULL,
    SESSION_TYPE VARCHAR(4),
    STATUS VARCHAR(1) NOT NULL,
    SYSTEM_ID INTEGER,
    SYSTEM_TYPE VARCHAR(3),
    TIMEOUT TIMESTAMP(0),
    CONSTRAINT EDISESSION_PK_IDA PRIMARY KEY (IDA)
);

