CREATE TABLE EMDOCS_DISPLAY (
    EMD_COUPON SMALLINT NOT NULL,
    EMD_NO VARCHAR(15) NOT NULL,
    EMD_NO_BASE VARCHAR(15) NOT NULL,
    EMD_TYPE VARCHAR(1) NOT NULL,
    ET_COUPON SMALLINT,
    ET_NO VARCHAR(15),
    LAST_DISPLAY TIMESTAMP(0) NOT NULL,
    RFIC VARCHAR(1) NOT NULL,
    RFISC VARCHAR(15) NOT NULL,
    SERVICE_NAME VARCHAR(100) NOT NULL,
    SERVICE_QUANTITY SMALLINT,
    SSR_CODE VARCHAR(4)
);

