CREATE TABLE ETICKETS (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    COUPON_NO SMALLINT NOT NULL,
    COUPON_STATUS VARCHAR(1),
    ERROR VARCHAR(100),
    POINT_ID INTEGER NOT NULL,
    TICKET_NO VARCHAR(15) NOT NULL
);

