CREATE TABLE ETICKS_DISPLAY (
    BAG_NORM SMALLINT,
    BAG_NORM_UNIT VARCHAR(2),
    COUPON_NO SMALLINT NOT NULL,
    FARE_BASIS VARCHAR(15) NOT NULL,
    FARE_CLASS VARCHAR(3),
    ISSUE_DATE TIMESTAMP(0) NOT NULL,
    LAST_DISPLAY TIMESTAMP(0) NOT NULL,
    NAME VARCHAR(70),
    ORIG_FARE_CLASS VARCHAR(3),
    SURNAME VARCHAR(70) NOT NULL,
    TICKET_NO VARCHAR(20) NOT NULL
);

