CREATE TABLE ETICKS_DISPLAY_TLGS (
    COUPON_NO SMALLINT NOT NULL,
    LAST_DISPLAY TIMESTAMP(0) NOT NULL,
    PAGE_NO INTEGER NOT NULL,
    TICKET_NO VARCHAR(20) NOT NULL,
    TLG_TEXT VARCHAR(1000) NOT NULL,
    TLG_TYPE SMALLINT NOT NULL
);

