CREATE TABLE EVENTS_BILINGUAL (
    EV_ORDER INTEGER NOT NULL,
    EV_USER VARCHAR(20),
    ID1 INTEGER,
    ID2 INTEGER,
    ID3 INTEGER,
    LANG VARCHAR(2) NOT NULL,
    MSG VARCHAR(250) NOT NULL,
    PART_NUM SMALLINT NOT NULL,
    SCREEN VARCHAR(15),
    STATION VARCHAR(15),
    SUB_TYPE VARCHAR(100),
    TIME TIMESTAMP(0) NOT NULL,
    TYPE VARCHAR(3) NOT NULL
);

