CREATE TABLE EXTRA_ROLE_ACCESS (
    AIRLINE_FROM VARCHAR(3),
    AIRLINE_TO VARCHAR(3),
    AIRP_FROM VARCHAR(3),
    AIRP_TO VARCHAR(3),
    FULL_ACCESS SMALLINT NOT NULL,
    ID INTEGER NOT NULL
);
