CREATE TABLE FILE_QUEUE (
    ID INTEGER NOT NULL,
    RECEIVER VARCHAR(6) NOT NULL,
    SENDER VARCHAR(6) NOT NULL,
    STATUS VARCHAR(4) NOT NULL,
    TIME TIMESTAMP(0) NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

