CREATE TABLE FILES (
    DATA bytea,
    ERROR VARCHAR(4),
    ID INTEGER NOT NULL,
    RECEIVER VARCHAR(6) NOT NULL,
    SENDER VARCHAR(6) NOT NULL,
    TIME TIMESTAMP(0) NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

