CREATE TABLE FILE_SETS (
    AIRP VARCHAR(3),
    CODE VARCHAR(20) NOT NULL,
    DIR VARCHAR(50) NOT NULL,
    LAST_CREATE TIMESTAMP(0),
    NAME VARCHAR(20) NOT NULL,
    NUM SMALLINT,
    PR_DENIAL SMALLINT NOT NULL
);

