CREATE TABLE FOREIGN_SCAN (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    DESK_AIRP VARCHAR(3),
    ERRORS VARCHAR(200),
    FLT_NO INTEGER NOT NULL,
    ID INTEGER NOT NULL,
    SCAN_DATA VARCHAR(4000) NOT NULL,
    SCD_OUT TIMESTAMP(0) NOT NULL,
    SUFFIX VARCHAR(1),
    TIME_PRINT TIMESTAMP(0) NOT NULL
);
