CREATE TABLE GRAPH_STAGES (
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_AIRP_STAGE SMALLINT NOT NULL,
    PR_AUTO SMALLINT NOT NULL,
    STAGE_ID SMALLINT NOT NULL,
    TIME SMALLINT NOT NULL
);

