CREATE TABLE GRP_NORMS (
    AIRLINE VARCHAR(3),
    BAG_TYPE SMALLINT,
    BAG_TYPE_STR VARCHAR(15),
    GRP_ID INTEGER NOT NULL,
    HANDMADE SMALLINT,
    LIST_ID INTEGER,
    NORM_ID INTEGER,
    NORM_TRFER SMALLINT
);

