CREATE TABLE HIST_TYPEB_ADDR_OWNERS (
    ADDR VARCHAR(7) NOT NULL,
    COUNTRY VARCHAR(2),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    TRANSPORT_ADDR VARCHAR(6) NOT NULL,
    TRANSPORT_TYPE VARCHAR(20) NOT NULL
);
