CREATE TABLE HIST_BRANDS (
    AIRLINE VARCHAR(3) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50) NOT NULL
);

