CREATE TABLE HIST_FORM_TYPES (
    BASIC_TYPE VARCHAR(3) NOT NULL,
    CODE VARCHAR(7) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NAME_LAT VARCHAR(100),
    NO_LEN SMALLINT NOT NULL,
    PR_CHECK_BIT SMALLINT NOT NULL,
    SERIES_LEN SMALLINT NOT NULL,
    VALIDATOR VARCHAR(4) NOT NULL
);
