CREATE TABLE HIST_PAY_CLIENTS (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    CLIENT_ID INTEGER NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PACT VARCHAR(100) NOT NULL,
    PR_DENIAL SMALLINT NOT NULL
);
