CREATE TABLE HIST_SALE_DESKS (
    CODE VARCHAR(6) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    SALE_POINT VARCHAR(8) NOT NULL,
    VALIDATOR VARCHAR(4) NOT NULL
);

