CREATE TABLE HIST_TIMATIC_SETS (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    HOST VARCHAR(200) NOT NULL,
    ID INTEGER,
    PORT INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    PWD VARCHAR(200) NOT NULL,
    SUB_USERNAME VARCHAR(200) NOT NULL,
    USERNAME VARCHAR(200) NOT NULL
);
