CREATE TABLE HIST_STAGE_NAMES (
    AIRP VARCHAR(3) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    STAGE_ID SMALLINT NOT NULL
);

