CREATE TABLE HIST_CRYPT_REQ_DATA (
    CITY VARCHAR(128),
    COUNTRY VARCHAR(2) NOT NULL,
    DESK VARCHAR(6),
    DESK_GRP_ID INTEGER NOT NULL,
    EMAIL VARCHAR(40),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    KEYSLENGTH SMALLINT,
    KEY_ALGO VARCHAR(20),
    ORGANIZATION VARCHAR(64),
    ORGANIZATIONAL_UNIT VARCHAR(64),
    PR_DENIAL SMALLINT NOT NULL,
    STATE VARCHAR(128),
    TITLE VARCHAR(64),
    USER_NAME VARCHAR(64)
);

