CREATE TABLE HIST_TYPEB_SEND (
    AIRLINE VARCHAR(3),
    AIRP_ARV VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    FLT_NO INTEGER,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    TLG_TYPE VARCHAR(6) NOT NULL
);
