CREATE TABLE HIST_TYPEB_ORIGINATORS (
    ADDR VARCHAR(7) NOT NULL,
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    DESCR VARCHAR(50) NOT NULL,
    DOUBLE_SIGN VARCHAR(2),
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP,
    PR_DEL SMALLINT NOT NULL,
    TLG_TYPE VARCHAR(6)
);
