CREATE TABLE HIST_BI_PRINT_RULES (
    AIRCODE VARCHAR(3),
    AIRLINE VARCHAR(3) NOT NULL,
    BRAND_AIRLINE VARCHAR(3),
    BRAND_CODE VARCHAR(10),
    CLASS VARCHAR(1),
    FQT_AIRLINE VARCHAR(3),
    FQT_TIER_LEVEL VARCHAR(50),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PRINT_TYPE VARCHAR(3) NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    REM_CODE VARCHAR(4),
    RFISC VARCHAR(15),
    SUBCLASS VARCHAR(1)
);

