CREATE TABLE HIST_RFISC_SETS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3),
    AUTO_CHECKIN SMALLINT NOT NULL,
    FLT_NO INTEGER,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    RFIC VARCHAR(1) NOT NULL,
    RFISC VARCHAR(15)
);

