CREATE TABLE HIST_OPERATORS (
    AGENCY VARCHAR(5) NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LOGIN VARCHAR(12) NOT NULL,
    PRIVATE_NUM SMALLINT NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    VALIDATOR VARCHAR(4) NOT NULL
);

