CREATE TABLE HIST_TYPEB_ADDR_OPTIONS (
    CATEGORY VARCHAR(20) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    TLG_TYPE VARCHAR(6) NOT NULL,
    TYPEB_ADDRS_ID INTEGER NOT NULL,
    VALUE VARCHAR(10)
);
