CREATE TABLE HIST_STAGE_SETS (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_AUTO SMALLINT NOT NULL,
    STAGE_ID SMALLINT NOT NULL
);

