CREATE TABLE HIST_HALL_SET (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    FLT_NO INTEGER,
    HALL INTEGER,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_MISC SMALLINT NOT NULL,
    TYPE SMALLINT NOT NULL
);

