CREATE TABLE HIST_REFUSAL_TYPES (
    CODE VARCHAR(1) NOT NULL,
    CODE_LAT VARCHAR(1),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL
);

