CREATE TABLE HIST_PAX_CATS (
    CODE VARCHAR(3) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    NAME_LAT VARCHAR(150)
);

