CREATE TABLE HIST_ROLES (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

