CREATE TABLE HIST_CRYPT_SETS (
    DESK VARCHAR(6),
    DESK_GRP_ID INTEGER NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_CRYPT SMALLINT NOT NULL
);

