CREATE TABLE HIST_AIRLINE_OFFICES (
    AIRLINE VARCHAR(3) NOT NULL,
    CONTACT_NAME VARCHAR(35) NOT NULL,
    COUNTRY_CONTROL VARCHAR(2) NOT NULL,
    FAX VARCHAR(20) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID BIGINT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    TO_APIS SMALLINT NOT NULL
);

