CREATE TABLE HIST_PLACE_CALC (
    BC VARCHAR(3) NOT NULL,
    COD_IN VARCHAR(3) NOT NULL,
    COD_OUT VARCHAR(3) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    TIME_OUT_IN TIMESTAMP(0),
    TIME_OUT_OUT TIMESTAMP(0),
    TROUND_IN SMALLINT,
    TROUND_OUT SMALLINT
);

