CREATE TABLE HIST_TRIP_LIST_DAYS (
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    SHIFT_DOWN SMALLINT NOT NULL,
    SHIFT_UP SMALLINT NOT NULL
);

