CREATE TABLE HIST_BI_HALLS (
    AIRP VARCHAR(3) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    NAME_LAT VARCHAR(40),
    TERMINAL INTEGER
);

