CREATE TABLE HIST_CUSTOM_ALARM_TYPES (
    AIRLINE VARCHAR(3),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NAME_LAT VARCHAR(100) NOT NULL
);

