CREATE TABLE HIST_DCS_SERVICE_APPLYING (
    AIRLINE VARCHAR(3) NOT NULL,
    BRAND_AIRLINE VARCHAR(3),
    BRAND_CODE VARCHAR(10),
    CLASS VARCHAR(1),
    DCS_SERVICE VARCHAR(20) NOT NULL,
    FQT_AIRLINE VARCHAR(3),
    FQT_TIER_LEVEL VARCHAR(50),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    RFISC VARCHAR(15) NOT NULL
);

