CREATE TABLE HIST_PAY_METHODS_SET (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    DESK VARCHAR(6),
    DESK_GRP_ID INTEGER,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    METHOD_TYPE SMALLINT NOT NULL
);
