CREATE TABLE HIST_TYPEB_ADDR_TRANS_PARAMS (
    ADDR VARCHAR(7) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PARAM_NAME VARCHAR(20) NOT NULL,
    PARAM_VALUE VARCHAR(100) NOT NULL
);
