CREATE TABLE HIST_EXTRA_USER_ACCESS (
    AIRLINE_FROM VARCHAR(3),
    AIRLINE_TO VARCHAR(3),
    AIRP_FROM VARCHAR(3),
    AIRP_TO VARCHAR(3),
    FULL_ACCESS SMALLINT NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    TYPE_FROM SMALLINT NOT NULL,
    TYPE_TO SMALLINT NOT NULL
);
