CREATE TABLE HIST_BI_AIRLINE_SERVICE (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP VARCHAR(3) NOT NULL,
    HALL INTEGER,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    PR_PRINT_BI SMALLINT NOT NULL,
    TERMINAL INTEGER
);

