CREATE TABLE HIST_RFISC_COMP_PROPS (
    AIRLINE VARCHAR(3) NOT NULL,
    CODE VARCHAR(15) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    PR_PROT_CKIN SMALLINT NOT NULL,
    RATE_COLOR VARCHAR(10) NOT NULL
);

