CREATE TABLE HIST_COMP_REM_TYPES (
    CODE VARCHAR(4) NOT NULL,
    CODE_LAT VARCHAR(4) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(60),
    PR_COMP SMALLINT NOT NULL,
    PR_DEL SMALLINT NOT NULL
);

