CREATE TABLE HIST_CODESHARE_SETS (
    AIRLINE_MARK VARCHAR(3) NOT NULL,
    AIRLINE_OPER VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    DAYS VARCHAR(7),
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    FLT_NO_MARK INTEGER NOT NULL,
    FLT_NO_OPER INTEGER NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP(0),
    PR_DEL SMALLINT NOT NULL,
    PR_MARK_BP SMALLINT NOT NULL,
    PR_MARK_NORMS SMALLINT NOT NULL,
    PR_MARK_RPT SMALLINT NOT NULL,
    SUFFIX_MARK VARCHAR(1),
    SUFFIX_OPER VARCHAR(1)
);

