CREATE TABLE HIST_COMP_SUBCLS_SETS (
    AIRLINE VARCHAR(3) NOT NULL,
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    REM VARCHAR(4) NOT NULL,
    SUBCLASS VARCHAR(1) NOT NULL
);

