CREATE TABLE HIST_GRAPH_TIMES (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    CRAFT VARCHAR(3),
    HIST_ORDER INTEGER NOT NULL,
    HIST_TIME TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    STAGE_ID SMALLINT NOT NULL,
    TIME SMALLINT NOT NULL,
    TRIP_TYPE VARCHAR(1)
);

