CREATE TABLE HOTEL_ACMD_PAX (
    BREAKFAST SMALLINT,
    DINNER SMALLINT,
    HOTEL_ID INTEGER NOT NULL,
    PAX_ID INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    ROOM_TYPE INTEGER,
    SUPPER SMALLINT
);

