CREATE TABLE HOTEL_ACMD (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3) NOT NULL,
    DOUBLE_AMOUNT INTEGER NOT NULL,
    HOTEL_NAME VARCHAR(100) NOT NULL,
    ID INTEGER NOT NULL,
    SINGLE_AMOUNT INTEGER NOT NULL
);

