CREATE TABLE IATCI_SETTINGS (
BPR SMALLINT NOT NULL,
CKI SMALLINT NOT NULL,
CKU SMALLINT NOT NULL,
CKX SMALLINT NOT NULL,
DCS_ID INTEGER NOT NULL,
IFM SMALLINT NOT NULL,
PLF SMALLINT NOT NULL,
SMF SMALLINT NOT NULL
);
