#!/bin/bash -e

PASS=${1?NO_PASSWORD}

CMD="psql ${PASS}"

rm -f ok oldlog2 now.run
if  [ -f oldlog1 ] ; then
    mv oldlog1 oldlog2
fi
if [ -f log ] ; then
    mv log oldlog1
fi

if [ "${1}" = "NO_POSTGRES_CONNECT" ]; then
    echo PostgreSQL Connection not set > log
    exit
fi


for f in *.sql ; do 
    if [ $f != \*.sql ] ; then
        now=1
        if [ -f LATER ] ; then
            while read file dir ; do
                if [ ${file}x = ${f}x ] ; then
                    [ -d $BASEDIR/$dir ] || mkdir $BASEDIR/$dir
                    ln -sf `pwd`/$f $BASEDIR/$dir 
                    echo saved for later $BASEDIR/$dir/$f 2>&1 | tee -a log
                    now=0
                fi
            done <LATER
        fi
        if [ $now -eq 1 ] ; then
            echo "\\echo  $f" >>now.run
            if [ -f ./localaction ] ; then
                FILENAME=$f . ./localaction  >>now.run
            fi
            echo \\ir ${f} >>now.run
        fi    
    fi
done 


if [ -f now.run ] ; then
    echo ${CMD}
    ${CMD} -f now.run </dev/null 2>&1 | tee -a log

    if grep -Ec "ERROR:" log; then
        echo Errors in $PWD $PASS | tee -a log 1>&2
        exit 1
    else
        echo OK>ok
    fi

fi
