CREATE TABLE KIOSK_EVENTS (
    APPLICATION VARCHAR(50),
    EV_ORDER INTEGER NOT NULL,
    ID INTEGER NOT NULL,
    KIOSKID VARCHAR(50),
    SCREEN VARCHAR(50),
    SESSION_ID VARCHAR(32),
    TIME TIMESTAMP(0) NOT NULL,
    TYPE VARCHAR(50)
);

