CREATE TABLE PAID_RFISC (
    AIRLINE VARCHAR(3) NOT NULL,
    LIST_ID INTEGER NOT NULL,
    NEED SMALLINT NOT NULL,
    PAID SMALLINT NOT NULL,
    PAX_ID INTEGER NOT NULL,
    RFISC VARCHAR(15) NOT NULL,
    SERVICE_QUANTITY SMALLINT NOT NULL,
    SERVICE_TYPE VARCHAR(1) NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

