CREATE TABLE PAID_BAG_EMD_PROPS (
    EMD_COUPON SMALLINT NOT NULL,
    EMD_NO VARCHAR(15) NOT NULL,
    GRP_ID INTEGER NOT NULL,
    MANUAL_BIND SMALLINT NOT NULL,
    NOT_AUTO_CHECKIN SMALLINT NOT NULL
);

