CREATE TABLE PAX_FQT (
    AIRLINE VARCHAR(3) NOT NULL,
    EXTRA VARCHAR(250),
    NO VARCHAR(25) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    REM_CODE VARCHAR(5) NOT NULL,
    TIER_LEVEL VARCHAR(50),
    TIER_LEVEL_CONFIRM SMALLINT
);

