CREATE TABLE PAX_BRANDS (
    GRP_ID INTEGER NOT NULL,
    LANG VARCHAR(2) NOT NULL,
    PAGE_NO INTEGER NOT NULL,
    PAX_ID INTEGER NOT NULL,
    TEXT VARCHAR(4000) NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

