CREATE TABLE PAX_NORMS (
    AIRLINE VARCHAR(3),
    BAG_TYPE SMALLINT,
    BAG_TYPE_STR VARCHAR(15),
    HANDMADE SMALLINT,
    LIST_ID INTEGER,
    NORM_ID INTEGER,
    NORM_TRFER SMALLINT,
    PAX_ID INTEGER NOT NULL
);

