CREATE TABLE PAX_EVENTS (
    DESK VARCHAR(6) NOT NULL,
    EV_ORDER INTEGER NOT NULL,
    PAX_EVENT VARCHAR(10) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    STATION VARCHAR(6),
    TIME TIMESTAMP(0) NOT NULL
);

