CREATE TABLE PAX_SERVICE_LISTS (
    ADDITIONAL_LIST_ID INTEGER,
    CATEGORY SMALLINT NOT NULL,
    GRP_ID INTEGER NOT NULL,
    LIST_ID INTEGER NOT NULL,
    PAX_ID INTEGER NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

