CREATE TABLE PAX_ASVC (
    EMD_COUPON SMALLINT,
    EMD_NO VARCHAR(15),
    EMD_TYPE VARCHAR(1),
    PAX_ID INTEGER NOT NULL,
    RFIC VARCHAR(1) NOT NULL,
    RFISC VARCHAR(15) NOT NULL,
    SERVICE_NAME VARCHAR(30) NOT NULL,
    SERVICE_QUANTITY SMALLINT NOT NULL,
    SSR_CODE VARCHAR(4)
);

