CREATE TABLE PAX_NORMS_TEXT (
    AIRLINE VARCHAR(3) NOT NULL,
    CARRY_ON SMALLINT NOT NULL,
    CONCEPT VARCHAR(10) NOT NULL,
    GRP_ID INTEGER NOT NULL,
    LANG VARCHAR(2) NOT NULL,
    PAGE_NO INTEGER NOT NULL,
    PAX_ID INTEGER NOT NULL,
    RFISCS VARCHAR(50),
    TEXT VARCHAR(4000) NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

