CREATE TABLE PAX_DOC_TYPES (
    CODE VARCHAR(2) NOT NULL,
    CODE_MINTRANS VARCHAR(2) NOT NULL,
    IS_DOCO_TYPE SMALLINT NOT NULL,
    IS_DOCS_TYPE SMALLINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NAME_LAT VARCHAR(100)
);

