CREATE TABLE PAY_CLIENTS (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    CLIENT_ID INTEGER NOT NULL,
    ID INTEGER NOT NULL,
    PACT VARCHAR(100) NOT NULL,
    PR_DENIAL SMALLINT NOT NULL
);
