CREATE TABLE PERS_WEIGHTS (
    AIRLINE VARCHAR(3),
    BORT VARCHAR(10),
    CHILD SMALLINT NOT NULL,
    CLASS VARCHAR(1),
    CRAFT VARCHAR(3),
    FEMALE SMALLINT,
    FIRST_DATE TIMESTAMP(0),
    ID INTEGER NOT NULL,
    INFANT SMALLINT NOT NULL,
    LAST_DATE TIMESTAMP(0),
    MALE SMALLINT NOT NULL,
    PR_SUMMER SMALLINT,
    SUBCLASS VARCHAR(1)
);

