CREATE TABLE PNR_MARKET_FLT (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    FLT_NO INTEGER NOT NULL,
    LOCAL_DATE SMALLINT NOT NULL,
    PNR_ID INTEGER NOT NULL,
    SUBCLASS VARCHAR(1) NOT NULL,
    SUFFIX VARCHAR(1)
);

