CREATE TABLE POS_TERM_SETS (
    ADDRESS VARCHAR(100),
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    CLIENT_ID INTEGER NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    SERIAL VARCHAR(30) NOT NULL,
    SHOP_ID INTEGER NOT NULL,
    VENDOR_ID INTEGER NOT NULL
);
