CREATE TABLE PRN_TESTS (
    DATA VARCHAR(4000) NOT NULL,
    DESK_GRP_ID INTEGER,
    DEV_MODEL VARCHAR(10),
    FMT_TYPE VARCHAR(10) NOT NULL,
    FORM VARCHAR(4000),
    OP_TYPE VARCHAR(10) NOT NULL
);

