CREATE TABLE PRN_FORM_VERS (
    DATA VARCHAR(4000),
    DESCR VARCHAR(100) NOT NULL,
    FORM VARCHAR(4000),
    ID INTEGER NOT NULL,
    READ_ONLY SMALLINT NOT NULL,
    VERSION INTEGER NOT NULL
);

