CREATE TABLE PRN_TAG_PROPS (
    CODE VARCHAR(20) NOT NULL,
    CONVERT_CHAR_VIEW SMALLINT NOT NULL,
    EXCEPT_WHEN_GREAT_LEN SMALLINT NOT NULL,
    EXCEPT_WHEN_ONLY_LAT SMALLINT NOT NULL,
    LENGTH SMALLINT NOT NULL,
    OP_TYPE VARCHAR(10) NOT NULL
);

