CREATE TABLE REFUSAL_TYPES (
    CODE VARCHAR(1) NOT NULL,
    CODE_LAT VARCHAR(1),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL
);

