CREATE TABLE RFISC_LIST_ITEMS (
    AIRLINE VARCHAR(3) NOT NULL,
    CATEGORY SMALLINT NOT NULL,
    DESCR1 VARCHAR(2),
    DESCR2 VARCHAR(2),
    EMD_TYPE VARCHAR(6),
    GRP VARCHAR(3),
    LIST_ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    NAME_LAT VARCHAR(100) NOT NULL,
    RFIC VARCHAR(1),
    RFISC VARCHAR(15) NOT NULL,
    SERVICE_TYPE VARCHAR(1) NOT NULL,
    SUBGRP VARCHAR(3),
    VISIBLE SMALLINT NOT NULL
);

