CREATE TABLE RFISC_BAG_PROPS (
    AIRLINE VARCHAR(3) NOT NULL,
    CODE VARCHAR(15) NOT NULL,
    ID INTEGER NOT NULL,
    MAX_WEIGHT SMALLINT,
    MIN_WEIGHT SMALLINT,
    PRIORITY INTEGER,
    REM_CODE_LCI VARCHAR(4),
    REM_CODE_LDM VARCHAR(3)
);

