CREATE TABLE RPT_BM_BAG_NAMES (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    BAG_TYPE SMALLINT,
    CLASS VARCHAR(1),
    NAME VARCHAR(20) NOT NULL,
    NAME_LAT VARCHAR(20) NOT NULL,
    RFISC VARCHAR(15)
);

