CREATE TABLE SBDO_TAGS_GENERATED (
    AIRLINE VARCHAR(3) NOT NULL,
    BAG_TYPE VARCHAR(15),
    DEACTIVATED SMALLINT NOT NULL,
    LIST_ID INTEGER NOT NULL,
    NO BIGINT NOT NULL,
    PAX_ID INTEGER NOT NULL,
    RFISC VARCHAR(15),
    SBDO_TYPE VARCHAR(10) NOT NULL,
    SERVICE_TYPE VARCHAR(20),
    WEIGHT SMALLINT NOT NULL
);

