CREATE TABLE SELF_CKIN_STAT (
    ADULT SMALLINT NOT NULL,
    BABY SMALLINT NOT NULL,
    CHILD SMALLINT NOT NULL,
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    DESK_AIRP VARCHAR(3),
    POINT_ID INTEGER NOT NULL,
    TCKIN SMALLINT NOT NULL,
    TERM_BAG SMALLINT,
    TERM_BP SMALLINT,
    TERM_CKIN_SERVICE SMALLINT
);

