CREATE TABLE SERVICE_PAYMENT (
    AIRLINE VARCHAR(3) NOT NULL,
    BAG_TYPE VARCHAR(15),
    DOC_AIRCODE VARCHAR(3),
    DOC_COUPON SMALLINT,
    DOC_NO VARCHAR(15) NOT NULL,
    DOC_TYPE VARCHAR(5) NOT NULL,
    DOC_WEIGHT INTEGER,
    GRP_ID INTEGER NOT NULL,
    LIST_ID INTEGER NOT NULL,
    PAX_ID INTEGER,
    POINT_ID INTEGER NOT NULL,
    RFISC VARCHAR(15),
    SERVICE_QUANTITY SMALLINT NOT NULL,
    SERVICE_TYPE VARCHAR(1),
    TRANSFER_NUM SMALLINT NOT NULL
);

