CREATE TABLE STAT_ORDERS_DATA (
    DOWNLOAD_TIMES INTEGER NOT NULL,
    FILE_ID INTEGER NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT,
    FILE_SIZE_ZIP BIGINT,
    MD5_SUM VARCHAR(32),
    MONTH TIMESTAMP(0) NOT NULL
);

