CREATE TABLE STAT_ORDERS (
    DATA_SIZE BIGINT,
    DATA_SIZE_ZIP BIGINT,
    ERROR VARCHAR(250),
    FILE_ID INTEGER NOT NULL,
    PROGRESS SMALLINT NOT NULL,
    SOURCE VARCHAR(100) NOT NULL,
    STATUS SMALLINT NOT NULL,
    TIME_CREATED TIMESTAMP(0),
    TIME_ORDERED TIMESTAMP(0) NOT NULL,
    USER_ID INTEGER NOT NULL
);

