CREATE TABLE STAT_AD (
    BAG_AMOUNT INTEGER,
    BAG_WEIGHT INTEGER,
    CLASS VARCHAR(1) NOT NULL,
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    PNR VARCHAR(20),
    POINT_ID INTEGER NOT NULL,
    SCD_OUT TIMESTAMP(0) NOT NULL,
    SEAT_NO VARCHAR(50),
    SEAT_NO_LAT VARCHAR(50),
    STATION VARCHAR(6)
);

