CREATE TABLE STAT_PARAMS (
    CAPTION VARCHAR(20) NOT NULL,
    CODE VARCHAR(20) NOT NULL,
    CTYPE VARCHAR(20) NOT NULL,
    EDIT_FMT VARCHAR(100),
    FILTER VARCHAR(200),
    ISALNUM SMALLINT NOT NULL,
    LEN INTEGER NOT NULL,
    REF VARCHAR(20),
    REF_FIELD VARCHAR(20),
    TAG VARCHAR(20),
    VISIBLE INTEGER NOT NULL,
    WIDTH INTEGER NOT NULL
);

