CREATE TABLE STATIONS (
    AIRP VARCHAR(3) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    ID INTEGER NOT NULL,
    NAME VARCHAR(6) NOT NULL,
    USING_SCALES SMALLINT NOT NULL,
    WITHOUT_MONITOR SMALLINT NOT NULL,
    WORK_MODE VARCHAR(1) NOT NULL
);

