CREATE TABLE TAG_RANGES2 (
    AIRCODE SMALLINT NOT NULL,
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    CLASS VARCHAR(1),
    LAST_ACCESS TIMESTAMP(0) NOT NULL,
    NO SMALLINT NOT NULL,
    POINT_ID INTEGER,
    RANGE SMALLINT NOT NULL
);

