CREATE TABLE TAG_PACKS (
    AIRLINE VARCHAR(3) NOT NULL,
    COLOR VARCHAR(2),
    DESK VARCHAR(6) NOT NULL,
    NO BIGINT NOT NULL,
    TAG_TYPE VARCHAR(5) NOT NULL,
    TARGET VARCHAR(3) NOT NULL
)
