CREATE TABLE TASKS (
    INTERVAL SMALLINT NOT NULL,
    LAST_EXEC TIMESTAMP(0),
    NAME VARCHAR(20) NOT NULL,
    NEXT_EXEC TIMESTAMP(0),
    PROC_NAME VARCHAR(20),
    PR_DENIAL SMALLINT NOT NULL
);
