CREATE TABLE TCKIN_PAX_GRP (
    FIRST_REG_NO SMALLINT,
    GRP_ID INTEGER NOT NULL,
    GRP_NUM SMALLINT NOT NULL,
    PR_DEPEND SMALLINT NOT NULL,
    SEG_NO SMALLINT NOT NULL,
    TCKIN_ID INTEGER NOT NULL,
    TRANSIT_NUM SMALLINT NOT NULL
);

