CREATE TABLE TEXT_TLG_H2H (
    "END" VARCHAR(1),
    ERR VARCHAR(3),
    MSG_ID VARCHAR(10) NOT NULL,
    PART VARCHAR(1),
    QRI5 VARCHAR(1),
    QRI6 VARCHAR(1),
    RCVR VARCHAR(20),
    REM_ADDR_NUM VARCHAR(1),
    SNDR VARCHAR(20),
    TIMESTAMP TIMESTAMP(0),
    TPR VARCHAR(21),
    TYPE VARCHAR(1)
);

