CREATE TABLE TIMATIC_SETS (
    AIRLINE VARCHAR(3),
    AIRP VARCHAR(3),
    HOST VARCHAR(200) NOT NULL,
    ID INTEGER NOT NULL,
    PORT INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    PWD VARCHAR(200) NOT NULL,
    SUB_USERNAME VARCHAR(200) NOT NULL,
    USERNAME VARCHAR(200) NOT NULL
);
