CREATE TABLE TLG_TRIPS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_ARV VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    BIND_TYPE SMALLINT NOT NULL,
    FLT_NO INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_UTC SMALLINT NOT NULL,
    SCD TIMESTAMP(0) NOT NULL,
    SUFFIX VARCHAR(1)
);

