CREATE TABLE TLG_QUEUE (
    ID INTEGER NOT NULL,
    LAST_SEND DECIMAL(16,10),
    PRIORITY SMALLINT NOT NULL,
    PROC_ATTEMPT SMALLINT,
    RECEIVER VARCHAR(5) NOT NULL,
    SENDER VARCHAR(5) NOT NULL,
    STATUS VARCHAR(4) NOT NULL,
    SUBTYPE VARCHAR(15),
    TIME TIMESTAMP(0) NOT NULL,
    TIME_MSEC DECIMAL(16,10) NOT NULL,
    TLG_NUM BIGINT NOT NULL,
    TTL INTEGER,
    TYPE VARCHAR(4) NOT NULL
);

