CREATE TABLE TLG_TRANSFER (
    POINT_ID_IN INTEGER NOT NULL,
    POINT_ID_OUT INTEGER NOT NULL,
    SUBCL_IN VARCHAR(1),
    SUBCL_OUT VARCHAR(1),
    TLG_ID INTEGER NOT NULL,
    TRFER_ID INTEGER NOT NULL
);

