CREATE TABLE TLG_COMP_LAYERS (
    AIRP_ARV VARCHAR(3) NOT NULL,
    CRS_PAX_ID INTEGER,
    FIRST_XNAME VARCHAR(4) NOT NULL,
    FIRST_YNAME VARCHAR(4) NOT NULL,
    LAST_XNAME VARCHAR(4) NOT NULL,
    LAST_YNAME VARCHAR(4) NOT NULL,
    LAYER_TYPE VARCHAR(10) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RANGE_ID INTEGER NOT NULL,
    REM_CODE VARCHAR(5),
    TIME_REMOVE TIMESTAMP(0),
    TLG_ID INTEGER
);

