CREATE TABLE TLGS (
    ERROR VARCHAR(4),
    ID INTEGER NOT NULL,
    POSTPONED SMALLINT,
    RECEIVER VARCHAR(5) NOT NULL,
    SENDER VARCHAR(5) NOT NULL,
    TIME TIMESTAMP(0) NOT NULL,
    TLG_NUM BIGINT NOT NULL,
    TYPE VARCHAR(4) NOT NULL,
    TYPEB_TLG_ID INTEGER,
    TYPEB_TLG_NUM INTEGER
);

