CREATE TABLE TLGS_IN (
    ADDR VARCHAR(300),
    ENDING VARCHAR(20),
    HEADING VARCHAR(100),
    ID INTEGER NOT NULL,
    IS_FINAL_PART SMALLINT NOT NULL,
    MERGE_KEY VARCHAR(50),
    NUM INTEGER NOT NULL,
    TIME_CREATE TIMESTAMP(0),
    TIME_PARSE TIMESTAMP(0),
    TIME_RECEIVE TIMESTAMP(0) NOT NULL,
    TIME_RECEIVE_NOT_PARSE TIMESTAMP(0),
    TYPE VARCHAR(3)
);

