CREATE TABLE TRANSFER (
    AIRLINE_FMT SMALLINT NOT NULL,
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_ARV_FMT SMALLINT NOT NULL,
    AIRP_DEP_FMT SMALLINT NOT NULL,
    GRP_ID INTEGER NOT NULL,
    PIECE_CONCEPT SMALLINT,
    POINT_ID_TRFER INTEGER NOT NULL,
    PR_FINAL SMALLINT NOT NULL,
    SUFFIX_FMT SMALLINT,
    TRANSFER_NUM SMALLINT NOT NULL
);

