CREATE TABLE TRANZIT_SET (
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    BORT_CHANGING SMALLINT NOT NULL,
    BRD_WITH_AUTOREG SMALLINT NOT NULL,
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    PR_REG SMALLINT NOT NULL,
    PR_TRANZIT SMALLINT NOT NULL
);

