CREATE TABLE TRFER_TRIPS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    FLT_NO INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    POINT_ID_SPP INTEGER,
    SCD TIMESTAMP(0) NOT NULL,
    SUFFIX VARCHAR(1)
);

