CREATE TABLE TRFER_GRP (
    BAG_AMOUNT SMALLINT,
    BAG_WEIGHT SMALLINT,
    GRP_ID INTEGER NOT NULL,
    RK_WEIGHT SMALLINT,
    SEATS SMALLINT,
    TRFER_ID INTEGER NOT NULL,
    WEIGHT_UNIT VARCHAR(1)
);

