CREATE TABLE TRIP_CKIN_CLIENT (
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESK_GRP_ID INTEGER,
    POINT_ID INTEGER NOT NULL,
    PR_PERMIT SMALLINT NOT NULL,
    PR_TCKIN SMALLINT NOT NULL,
    PR_UPD_STAGE SMALLINT NOT NULL,
    PR_WAITLIST SMALLINT NOT NULL
);

