CREATE TABLE TRIP_COMP_REM (
    NUM SMALLINT NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    REM VARCHAR(4) NOT NULL,
    X SMALLINT NOT NULL,
    Y SMALLINT NOT NULL
);

