CREATE TABLE TRIP_DATA (
    AIRP_ARV VARCHAR(3) NOT NULL,
    AVAIL SMALLINT,
    CLASS VARCHAR(1) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RESA SMALLINT NOT NULL,
    TRANZIT SMALLINT NOT NULL
);

