CREATE TABLE TRIP_TASKS (
    ID INTEGER NOT NULL,
    LAST_EXEC TIMESTAMP(0),
    NAME VARCHAR(50) NOT NULL,
    NEXT_EXEC TIMESTAMP(0),
    PARAMS VARCHAR(4000),
    POINT_ID INTEGER NOT NULL,
    PROC_NAME VARCHAR(20),
    TID INTEGER
);

