CREATE TABLE TRIP_COMP_ELEMS (
    AGLE SMALLINT NOT NULL,
    CLASS VARCHAR(1),
    ELEM_TYPE VARCHAR(1) NOT NULL,
    NOT_GOOD SMALLINT,
    NUM SMALLINT NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_SMOKE SMALLINT,
    X SMALLINT NOT NULL,
    XNAME VARCHAR(4),
    XPRIOR SMALLINT,
    Y SMALLINT NOT NULL,
    YNAME VARCHAR(4),
    YPRIOR SMALLINT
);

