CREATE TABLE TRIP_LITERS (
    CODE VARCHAR(3) NOT NULL,
    CODE_LAT VARCHAR(3),
    ID INTEGER NOT NULL,
    NAME VARCHAR(50),
    NAME_LAT VARCHAR(50),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL
);

