CREATE TABLE TRIP_PERS_WEIGHTS (
    CHILD SMALLINT NOT NULL,
    CLASS VARCHAR(1),
    FEMALE SMALLINT,
    INFANT SMALLINT NOT NULL,
    MALE SMALLINT NOT NULL,
    POINT_ID INTEGER NOT NULL,
    SUBCLASS VARCHAR(1)
);

