CREATE TABLE TRIP_COMP_RANGES (
    LAYER_TYPE VARCHAR(10) NOT NULL,
    NUM SMALLINT NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RANGE_ID INTEGER NOT NULL,
    X SMALLINT NOT NULL,
    Y SMALLINT NOT NULL
);

