CREATE TABLE TYPEB_ORIGINATORS (
    ADDR VARCHAR(7) NOT NULL,
    AIRLINE VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    DESCR VARCHAR(50) NOT NULL,
    DOUBLE_SIGN VARCHAR(2),
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP(0),
    PR_DEL SMALLINT NOT NULL,
    TID INTEGER NOT NULL,
    TLG_TYPE VARCHAR(6)
);
