CREATE TABLE TYPEB_TYPES (
    BASIC_TYPE VARCHAR(3) NOT NULL,
    CODE VARCHAR(6) NOT NULL,
    EDITABLE SMALLINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    PR_DEP SMALLINT,
    SHORT_NAME VARCHAR(20) NOT NULL,
    SHORT_NAME_LAT VARCHAR(20)
);

