CREATE TABLE TYPEB_OPTION_VALUES (
    CATEGORY VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NAME_LAT VARCHAR(50),
    SHORT_NAME VARCHAR(20) NOT NULL,
    SHORT_NAME_LAT VARCHAR(20),
    TLG_TYPE VARCHAR(6) NOT NULL,
    VALUE VARCHAR(10) NOT NULL
);
