CREATE TABLE TYPEB_SEND (
    AIRLINE VARCHAR(3),
    AIRP_ARV VARCHAR(3),
    AIRP_DEP VARCHAR(3),
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    PR_DENIAL SMALLINT NOT NULL,
    TLG_TYPE VARCHAR(6) NOT NULL
);
