CREATE TABLE USERS2 (
    DESCR VARCHAR(20) NOT NULL,
    DESK VARCHAR(6),
    LOGIN VARCHAR(20),
    PASSWD VARCHAR(20),
    PR_DENIAL SMALLINT DEFAULT 0 NOT NULL,
    TYPE SMALLINT NOT NULL,
    USER_ID INTEGER NOT NULL
);

