CREATE TABLE WEB_CLIENTS (
    CLIENT_ID VARCHAR(20) NOT NULL,
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    ID INTEGER NOT NULL,    
    KIOSK_ADDR INTEGER,
    KIOSK_ID VARCHAR(50),
    TRACING_SEARCH SMALLINT NOT NULL,
    USER_ID INTEGER NOT NULL
);

