#!/bin/sh

DIRNAME="$(dirname $0)"
if [ "DIRNAME" = "" ] ; then
    DIRNAME=$(dirname $(which $0))
fi
DIRNAME=$(cd $DIRNAME && pwd)

if [ "$1" = --cflags ] ; then
    echo `pkg-config $DIRNAME/lib/pkgconfig/timatic.pc --cflags`
elif [ "$1" = --cxxflags ] ; then
    echo `pkg-config $DIRNAME/lib/pkgconfig/timatic.pc --cflags`
elif  [ "$1" = --libs ] ; then
    echo `pkg-config $DIRNAME/lib/pkgconfig/timatic.pc --libs`
else
    echo "Usage: $(basename $0) (--cxxflags|--cflags|--libs)"
    exit 1
fi
