SAVECC:=$(CC)
SAVECXX:=$(CXX)
CC:=$(SAVECC)
CXX:=$(SAVECXX)
OTHERINCLUDES=$(LIBXML2INCLUDE) $(BOOST_INCLUDE)
COMPFLAGS2=$(ORACLE_INCLUDE) -I$(SRCHOME) $(OP_CFLAGS) $(OTHERINCLUDES)
COMPFLAGS=$(COMPFLAGS2) $(LOCALFLAGS)
CPPCOMPFLAGS=$(CPPINCLUDE) 

