#!/bin/sh

DIRNAME="$(dirname $0)"
if [ "DIRNAME" = "" ] ; then
    DIRNAME=$(dirname $(which $0))
fi

DIRNAME=$(cd $DIRNAME && pwd)

. $DIRNAME/serverlibconfig

if [ "$1" = --cxxflags ] ; then
    echo $SERVERLIB_CXXFLAGS
elif [ "$1" = --cflags ] ; then
    echo $SERVERLIB_CFLAGS
elif  [ "$1" = --libs ] ; then
    echo $SERVERLIB_LDFLAGS
else 
   echo "Usage: $(basename $0) (--cxxflags|--cflags|--libs)"
   exit 1
fi
