#!/bin/sh

DIRNAME="$(dirname $0)"
if [ "DIRNAME" = "" ] ; then
    DIRNAME=$(dirname $(which $0))
fi
DIRNAME=$(cd $DIRNAME && pwd)

if [ "$1" = --cflags ] ; then
    echo -I$DIRNAME/include
elif [ "$1" = --cxxflags ] ; then
    echo -I$DIRNAME/include
elif  [ "$1" = --libs ] ; then
    echo $DIRNAME/src/libserver.la
else
    echo "Usage: $(basename $0) (--cxxflags|--cflags|--libs)"
    exit 1
fi
