CREATE TABLE ARX_TRFER_STAT (
    ADULT SMALLINT NOT NULL,
    BABY SMALLINT NOT NULL,
    BABY_WOP SMALLINT NOT NULL,
    C SMALLINT NOT NULL,
    CHILD SMALLINT NOT NULL,
    CHILD_WOP SMALLINT NOT NULL,
    CLIENT_TYPE VARCHAR(5) NOT NULL,
    EXCESS_PC INTEGER,
    EXCESS_WT INTEGER NOT NULL,
    F SMALLINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PCS INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    TRFER_ROUTE VARCHAR(200) NOT NULL,
    UNCHECKED INTEGER NOT NULL,
    WEIGHT INTEGER NOT NULL,
    Y SMALLINT NOT NULL
);

