CREATE TABLE ARX_PAX_DOCA (
    ADDRESS VARCHAR(35),
    CITY VARCHAR(35),
    COUNTRY VARCHAR(3),
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    POSTAL_CODE VARCHAR(17),
    REGION VARCHAR(35),
    TYPE VARCHAR(1) NOT NULL
);

