CREATE TABLE ARX_BAG_PREPAY (
    AIRCODE VARCHAR(3) NOT NULL,
    BAG_TYPE SMALLINT,
    EX_WEIGHT SMALLINT,
    GRP_ID INTEGER NOT NULL,
    NO VARCHAR(15) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    RECEIPT_ID INTEGER NOT NULL,
    VALUE DECIMAL(12,2),
    VALUE_CUR VARCHAR(3)
);

