CREATE TABLE ARX_STAT_REPRINT (
    AMOUNT INTEGER NOT NULL,
    CKIN_TYPE VARCHAR(5),
    DESK VARCHAR(6) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    SCD_OUT TIMESTAMP(0) NOT NULL
);

