CREATE TABLE ARX_MARK_TRIPS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    FLT_NO BIGINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    SCD TIMESTAMP(0) NOT NULL,
    SUFFIX VARCHAR(1)
);

