CREATE TABLE ARX_STAT_HA (
    ADT SMALLINT NOT NULL,
    CHD SMALLINT NOT NULL,
    HOTEL_ID INTEGER NOT NULL,
    INF SMALLINT NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    ROOM_TYPE INTEGER,
    SCD_OUT TIMESTAMP(0) NOT NULL
);

