CREATE TABLE ARX_TRIP_SETS (
    C SMALLINT,
    COMP_ID INTEGER,
    F SMALLINT,
    MAX_COMMERCE INTEGER DEFAULT 0,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_AIRP_SEANCE SMALLINT,
    PR_ETSTATUS SMALLINT NOT NULL,
    PR_STAT SMALLINT NOT NULL,
    PR_TRANZ_REG SMALLINT,
    Y SMALLINT
);

