CREATE TABLE ARX_PAID_BAG (
    AIRLINE VARCHAR(3),
    BAG_TYPE SMALLINT,
    BAG_TYPE_STR VARCHAR(15),
    GRP_ID INTEGER NOT NULL,
    HANDMADE SMALLINT,
    LIST_ID INTEGER,
    PART_KEY TIMESTAMP(0) NOT NULL,
    RATE_ID INTEGER,
    RATE_TRFER SMALLINT,
    WEIGHT INTEGER NOT NULL
);

