CREATE TABLE ARX_PFS_STAT (
    AIRP_ARV VARCHAR(3) NOT NULL,
    BIRTH_DATE TIMESTAMP(0),
    GENDER VARCHAR(2),
    NAME VARCHAR(64),
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    PNR VARCHAR(50),
    POINT_ID INTEGER NOT NULL,
    SEATS SMALLINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    SUBCLS VARCHAR(1) NOT NULL,
    SURNAME VARCHAR(64) NOT NULL
);

