CREATE TABLE ARX_TRANSFER_SUBCLS (
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    SUBCLASS VARCHAR(1) NOT NULL,
    SUBCLASS_FMT SMALLINT NOT NULL,
    TRANSFER_NUM SMALLINT NOT NULL
);

