CREATE TABLE ARX_TCKIN_SEGMENTS (
    AIRLINE VARCHAR(3) NOT NULL,
    AIRP_ARV VARCHAR(3) NOT NULL,
    AIRP_DEP VARCHAR(3) NOT NULL,
    FLT_NO INTEGER NOT NULL,
    GRP_ID INTEGER NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PR_FINAL SMALLINT NOT NULL,
    SCD TIMESTAMP(0) NOT NULL,
    SEG_NO SMALLINT NOT NULL,
    SUFFIX VARCHAR(1)
);

