CREATE TABLE ARX_ANNUL_BAG (
    AMOUNT SMALLINT,
    BAG_TYPE SMALLINT,
    GRP_ID INTEGER NOT NULL,
    ID INTEGER,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER,
    RFISC VARCHAR(15),
    TIME_ANNUL TIMESTAMP(0),
    TIME_CREATE TIMESTAMP(0),
    USER_ID INTEGER,
    WEIGHT SMALLINT
);
