CREATE TABLE ARX_STAT_REM (
    AIRP_LAST VARCHAR(3) NOT NULL,
    DESK VARCHAR(6) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    RATE DECIMAL(12,2),
    RATE_CUR VARCHAR(3),
    REM_CODE VARCHAR(4) NOT NULL,
    RFISC VARCHAR(50),
    TICKET_NO VARCHAR(20),
    TRAVEL_TIME TIMESTAMP(0),
    USER_ID INTEGER NOT NULL
);

