CREATE TABLE ARX_VALUE_BAG_TAXES (
    AIRLINE VARCHAR(3),
    CITY_ARV VARCHAR(3),
    CITY_DEP VARCHAR(3),
    EXTRA VARCHAR(2000),
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP(0),
    MIN_VALUE INTEGER,
    MIN_VALUE_CUR VARCHAR(3),
    PART_KEY TIMESTAMP(0) NOT NULL,
    PR_DEL SMALLINT NOT NULL,
    PR_TRFER SMALLINT,
    TAX DECIMAL(4,1) NOT NULL,
    TID INTEGER NOT NULL
);

