CREATE TABLE ARX_BAG_RATES (
    AIRLINE VARCHAR(3),
    BAG_TYPE SMALLINT,
    CITY_ARV VARCHAR(3),
    CITY_DEP VARCHAR(3),
    CLASS VARCHAR(1),
    CRAFT VARCHAR(3),
    EXTRA VARCHAR(2000),
    FIRST_DATE TIMESTAMP(0) NOT NULL,
    FLT_NO INTEGER,
    ID INTEGER NOT NULL,
    LAST_DATE TIMESTAMP(0),
    MIN_WEIGHT SMALLINT,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_CAT VARCHAR(4),
    PR_DEL SMALLINT NOT NULL,
    PR_TRFER SMALLINT,
    RATE DECIMAL(8,2) NOT NULL,
    RATE_CUR VARCHAR(3) NOT NULL,
    SUBCLASS VARCHAR(1),
    TID INTEGER NOT NULL,
    TRIP_TYPE VARCHAR(1)
);

