CREATE TABLE ARX_PAX_DOC (
    BIRTH_DATE TIMESTAMP(0),
    EXPIRY_DATE TIMESTAMP(0),
    FIRST_NAME VARCHAR(64),
    GENDER VARCHAR(2),
    ISSUE_COUNTRY VARCHAR(3),
    NATIONALITY VARCHAR(3),
    NO VARCHAR(15),
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_ID INTEGER NOT NULL,
    PR_MULTI SMALLINT NOT NULL,
    SCANNED_ATTRS INTEGER,
    SECOND_NAME VARCHAR(64),
    SUBTYPE VARCHAR(1),
    SURNAME VARCHAR(64),
    TYPE VARCHAR(2),
    TYPE_RCPT VARCHAR(3)
);

