CREATE TABLE ARX_TRIP_CLASSES (
    BLOCK SMALLINT DEFAULT 0 NOT NULL,
    CFG SMALLINT DEFAULT 0 NOT NULL,
    CLASS VARCHAR(1) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PROT SMALLINT DEFAULT 0 NOT NULL
);

