CREATE TABLE ARX_TRIP_STAGES (
    ACT TIMESTAMP(0),
    EST TIMESTAMP(0),
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER NOT NULL,
    PR_AUTO SMALLINT DEFAULT 1 NOT NULL,
    PR_MANUAL SMALLINT NOT NULL,
    SCD TIMESTAMP(0) NOT NULL,
    STAGE_ID SMALLINT NOT NULL
);

