CREATE TABLE ARX_TLG_OUT (
    ADDR VARCHAR(1000),
    AIRLINE_MARK VARCHAR(3),
    BODY VARCHAR(4000),
    COMPLETED SMALLINT NOT NULL,
    ENDING VARCHAR(20),
    HAS_ERRORS SMALLINT NOT NULL,
    HEADING VARCHAR(1000),
    ID INTEGER NOT NULL,
    MANUAL_CREATION SMALLINT,
    NUM INTEGER NOT NULL,
    ORIGIN VARCHAR(1000),
    ORIGINATOR_ID INTEGER,
    PART_KEY TIMESTAMP(0) NOT NULL,
    POINT_ID INTEGER,
    PR_LAT SMALLINT NOT NULL,
    TIME_CREATE TIMESTAMP(0) NOT NULL,
    TIME_SEND_ACT TIMESTAMP(0),
    TIME_SEND_SCD TIMESTAMP(0),
    TYPE VARCHAR(6) NOT NULL
);

