CREATE TABLE ARX_LIMITED_CAPABILITY_STAT (
    AIRP_ARV VARCHAR(3) NOT NULL,
    PART_KEY TIMESTAMP(0) NOT NULL,
    PAX_AMOUNT INTEGER NOT NULL,
    POINT_ID INTEGER NOT NULL,
    REM_CODE VARCHAR(5) NOT NULL
);

