CREATE TABLE AER (
CLOSE NUMBER(1) DEFAULT 0,
CODEC NUMBER(9),
IDA NUMBER(9),
IN_USE NUMBER(1) DEFAULT 0,
LATIT NUMBER(6),
LCODEP VARCHAR2(3),
LNAME VARCHAR2(25),
LONGIT NUMBER(6),
RCODEP VARCHAR2(3),
RNAME VARCHAR2(25),
VERSION NUMBER
);
