CREATE TABLE AGN (
ACCRED NUMBER(1),
ADDRESS VARCHAR2(56),
AGENCY VARCHAR2(5),
CLOSE NUMBER(1) DEFAULT 0,
CODEC NUMBER(9),
EMD_AGN NUMBER(1) DEFAULT 0 NOT NULL,
EMD_MCO NUMBER(1) DEFAULT 0 NOT NULL,
EMD_PTA NUMBER(1) DEFAULT 0 NOT NULL,
IDA NUMBER(10),
L_AGENCY VARCHAR2(5),
NAME VARCHAR2(30),
RET_TAX NUMBER(9) NOT NULL,
SNAME VARCHAR2(30),
TYPE NUMBER(1) DEFAULT 0,
VERSION NUMBER
);
