CREATE TABLE AIRLINE_OFFICES (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP VARCHAR2(3),
CONTACT_NAME VARCHAR2(35) NOT NULL,
COUNTRY VARCHAR2(2) NOT NULL,
FAX VARCHAR2(20) NOT NULL,
ID NUMBER NOT NULL,
PHONE VARCHAR2(20) NOT NULL,
TO_APIS NUMBER(1) NOT NULL
);
