CREATE TABLE AIRPORT_CONTROLS (
AIRLINE NUMBER(9) NOT NULL,
CPNNUM NUMBER NOT NULL,
DATE_CR DATE DEFAULT sysdate NOT NULL,
RECLOC VARCHAR2(6),
TICKNUM VARCHAR2(13) NOT NULL
);
ALTER TABLE AIRPORT_CONTROLS ADD CONSTRAINT AIRPORT_CONTROLS_PK PRIMARY KEY(AIRLINE, TICKNUM, CPNNUM);
