CREATE TABLE AODB_PAX_CHANGE (
CLIENT_TYPE VARCHAR2(5) NOT NULL,
DESK VARCHAR2(6),
PAX_ID NUMBER(9) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
REG_NO NUMBER(3) NOT NULL,
TIME DATE NOT NULL,
WORK_MODE VARCHAR2(1) NOT NULL
);
