CREATE TABLE ARX_PAX_NORMS (
AIRLINE VARCHAR2(3),
BAG_TYPE NUMBER(2),
BAG_TYPE_STR VARCHAR2(15),
HANDMADE NUMBER(1),
LIST_ID NUMBER(9),
NORM_ID NUMBER(9),
NORM_TRFER NUMBER(1),
PART_KEY DATE NOT NULL,
PAX_ID NUMBER(9) NOT NULL
);
