CREATE TABLE ARX_TRIP_CLASSES (
BLOCK NUMBER(3) DEFAULT 0 NOT NULL,
CFG NUMBER(3) DEFAULT 0 NOT NULL,
CLASS VARCHAR2(1) NOT NULL,
PART_KEY DATE NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PROT NUMBER(3) DEFAULT 0 NOT NULL
);
