CREATE TABLE ARX_TRIP_STAGES (
ACT DATE,
EST DATE,
PART_KEY DATE NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PR_AUTO NUMBER(1) DEFAULT 1 NOT NULL,
PR_MANUAL NUMBER(1) NOT NULL,
SCD DATE NOT NULL,
STAGE_ID NUMBER(2) NOT NULL
);
