CREATE TABLE ARX_TRFER_PAX_STAT (
BAG_AMOUNT NUMBER(9),
BAG_WEIGHT NUMBER(9),
PART_KEY DATE NOT NULL,
PAX_ID NUMBER(9),
POINT_ID NUMBER(9) NOT NULL,
RK_WEIGHT NUMBER(9),
SCD_OUT DATE NOT NULL,
SEGMENTS VARCHAR2(4000) NOT NULL
);
