CREATE TABLE ARX_ANNUL_BAG (
AMOUNT NUMBER(3),
BAG_TYPE NUMBER(2),
GRP_ID NUMBER(9) NOT NULL,
ID NUMBER(9),
PART_KEY DATE NOT NULL,
PAX_ID NUMBER(9),
RFISC VARCHAR2(15),
TIME_ANNUL DATE,
TIME_CREATE DATE,
USER_ID NUMBER(9),
WEIGHT NUMBER(4)
);
