CREATE TABLE AWK (
ACCODE VARCHAR2(3),
CLOSE NUMBER(1) DEFAULT 0,
CODEC NUMBER(9),
CODEG NUMBER(9),
IDA NUMBER(9) NOT NULL,
LCODEA VARCHAR2(3),
LNAME VARCHAR2(30),
RCODEA VARCHAR2(3),
RNAME VARCHAR2(30),
SRNAME VARCHAR2(30),
VERSION NUMBER DEFAULT 1
);
