CREATE TABLE BAG2 (
AMOUNT NUMBER(3) DEFAULT 0 NOT NULL,
BAG_POOL_NUM NUMBER(3) NOT NULL,
BAG_TYPE NUMBER(2),
GRP_ID NUMBER(9) NOT NULL,
HALL NUMBER(9),
ID NUMBER(9) NOT NULL,
IS_TRFER NUMBER(1) NOT NULL,
NUM NUMBER(3) NOT NULL,
PR_CABIN NUMBER(1) NOT NULL,
PR_LIAB_LIMIT NUMBER(1) NOT NULL,
TO_RAMP NUMBER(1) NOT NULL,
USER_ID NUMBER(9),
USING_SCALES NUMBER(1) NOT NULL,
VALUE_BAG_NUM NUMBER(3),
WEIGHT NUMBER(4) DEFAULT 0 NOT NULL
);
