CREATE TABLE BAG_TYPE_LIST_ITEMS (
AIRLINE VARCHAR2(3) NOT NULL,
BAG_TYPE VARCHAR2(15) NOT NULL,
CATEGORY NUMBER(3) NOT NULL,
DESCR VARCHAR2(150),
DESCR_LAT VARCHAR2(150),
LIST_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50) NOT NULL,
VISIBLE NUMBER(1) NOT NULL
);
