CREATE TABLE BI_AIRLINE_SERVICE (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP VARCHAR2(3),
HALL NUMBER(9),
ID NUMBER(9) NOT NULL,
IS_BUSINESS_HALL NUMBER(1) NOT NULL,
PR_BI NUMBER(1) NOT NULL,
TERMINAL NUMBER(9)
);
