CREATE TABLE BI_PRINT_RULES (
AIRLINE VARCHAR2(3) NOT NULL,
CARD_TYPE VARCHAR2(20) NOT NULL,
CLS VARCHAR2(1),
ID NUMBER(9) NOT NULL,
PR_ISSUE NUMBER(1) NOT NULL,
REG_GROUP VARCHAR2(5) NOT NULL,
REM_CODE VARCHAR2(20) NOT NULL,
SUBCLS VARCHAR2(1)
);
