CREATE TABLE CENT_PAX (
AIRP_ARV VARCHAR2(3) NOT NULL,
CLASS VARCHAR2(1) NOT NULL,
EXCESS NUMBER(4) NOT NULL,
ID NUMBER(9) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
PCS NUMBER(3) NOT NULL,
PERS_TYPE VARCHAR2(1) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PR_INF NUMBER(1) NOT NULL,
SEAT_NO VARCHAR2(8) NOT NULL,
TID NUMBER(9) NOT NULL,
TRAN_TYPE NUMBER(1) NOT NULL,
UNCHECKED NUMBER(4) NOT NULL,
WEIGHT NUMBER(4) NOT NULL
);
