CREATE TABLE CENT_TRIPS (
AIRP_ARV1 VARCHAR2(3) NOT NULL,
AIRP_ARV2 VARCHAR2(3),
AIRP_ARV3 VARCHAR2(3),
AIRP_ARV4 VARCHAR2(3),
AIRP_ARV5 VARCHAR2(3),
BORT VARCHAR2(10),
COMP VARCHAR2(20),
CREW VARCHAR2(20),
POINT_ID NUMBER(9) NOT NULL,
SCD DATE NOT NULL,
TID NUMBER(9) NOT NULL,
TRIP VARCHAR2(10) NOT NULL
);
