CREATE TABLE CLIENT_TYPES (
CODE VARCHAR2(5) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PRIORITY NUMBER(2) NOT NULL,
SHORT_NAME VARCHAR2(10) NOT NULL,
SHORT_NAME_LAT VARCHAR2(10)
);
