CREATE TABLE CLS_GRP (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
CLASS VARCHAR2(1),
CODE VARCHAR2(1) NOT NULL,
CODE_LAT VARCHAR2(1) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
NAME_LAT VARCHAR2(20),
PRIORITY NUMBER(2) NOT NULL,
PR_DEL NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL
);
