CREATE TABLE COMP_LAYER_TYPES (
CODE VARCHAR2(10) NOT NULL,
COLOR VARCHAR2(10) NOT NULL,
DEL_IF_COMP_CHG NUMBER(1) NOT NULL,
FIGURE VARCHAR2(20),
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PRIORITY NUMBER(2) NOT NULL,
PR_OCCUPY NUMBER(1) NOT NULL
);
