CREATE TABLE COMP_RATES (
COLOR VARCHAR2(10) NOT NULL,
COMP_ID NUMBER(9) NOT NULL,
NUM NUMBER(2) NOT NULL,
RATE NUMBER(12) NOT NULL,
RATE_CUR VARCHAR2(3) NOT NULL,
X NUMBER(3) NOT NULL,
Y NUMBER(3) NOT NULL
);
