CREATE TABLE COMPS (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
BORT VARCHAR2(10),
CLASSES VARCHAR2(20),
COMP_ID NUMBER(9) NOT NULL,
CRAFT VARCHAR2(3) NOT NULL,
DESCR VARCHAR2(100),
PR_LAT_SEAT NUMBER(1) NOT NULL,
TIME_CREATE DATE NOT NULL
);
