CREATE TABLE CONFIRM_PRINT_VO_UNREG (
DESK VARCHAR2(6) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(64),
POINT_ID NUMBER(9) NOT NULL,
PR_PRINT NUMBER(1) NOT NULL,
SCD_OUT DATE NOT NULL,
SURNAME VARCHAR2(64) NOT NULL,
TIME_PRINT DATE NOT NULL,
VOUCHER VARCHAR2(2) NOT NULL
);
