CREATE TABLE COUNTERS_BY_SUBCLS (
BAG_WEIGHT NUMBER(7) NOT NULL,
CHILD NUMBER(3) NOT NULL,
CLASS VARCHAR2(1),
FEMALE NUMBER(3) NOT NULL,
INFANT NUMBER(3) NOT NULL,
MALE NUMBER(3) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
RK_WEIGHT NUMBER(7) NOT NULL,
SUBCLASS VARCHAR2(1)
);
