CREATE TABLE COUNTERS2 (
AVAIL NUMBER(3) NOT NULL,
CLASS VARCHAR2(1) NOT NULL,
CRS_OK NUMBER(3) NOT NULL,
CRS_TRANZIT NUMBER(3) NOT NULL,
FREE_GOSHOW NUMBER(3) NOT NULL,
FREE_OK NUMBER(3) NOT NULL,
GOSHOW NUMBER(3) NOT NULL,
NOOCCUPY NUMBER(3) NOT NULL,
OK NUMBER(3) NOT NULL,
POINT_ARV NUMBER(9) NOT NULL,
POINT_DEP NUMBER(9) NOT NULL,
TRANZIT NUMBER(3) NOT NULL
);
