CREATE TABLE CRS_PNR (
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_ARV_FINAL VARCHAR2(3),
CLASS VARCHAR2(1) NOT NULL,
GRP_NAME VARCHAR2(64),
PNR_ID NUMBER(9) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PRIORITY VARCHAR2(64),
SENDER VARCHAR2(7) NOT NULL,
STATUS VARCHAR2(3),
SUBCLASS VARCHAR2(1) NOT NULL,
SYSTEM VARCHAR2(3) NOT NULL,
TID NUMBER(9) NOT NULL
);
