CREATE TABLE CRS_PAX (
BAG_POOL NUMBER(3),
LAST_OP DATE NOT NULL,
NAME VARCHAR2(64),
PAX_ID NUMBER(9) NOT NULL,
PERS_TYPE VARCHAR2(2) NOT NULL,
PNR_ID NUMBER(9) NOT NULL,
PR_DEL NUMBER(1) DEFAULT 0 NOT NULL,
SEATS NUMBER(1) DEFAULT 1 NOT NULL,
SEAT_REM VARCHAR2(4),
SEAT_TYPE VARCHAR2(4),
SEAT_XNAME VARCHAR2(1),
SEAT_YNAME VARCHAR2(3),
SURNAME VARCHAR2(64) NOT NULL,
SYNC_CHKD NUMBER(1),
TID NUMBER(9) NOT NULL
);
