CREATE TABLE CRS_SET (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3),
CRS VARCHAR2(7) NOT NULL,
FLT_NO NUMBER(5),
ID NUMBER(9) NOT NULL,
PRIORITY NUMBER(1) DEFAULT 0 NOT NULL,
PR_NUMERIC_PNL NUMBER(1) NOT NULL
);
