CREATE TABLE CRS_RBD (
COMPARTMENT VARCHAR2(1) NOT NULL,
FARE_CLASS VARCHAR2(1) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
SENDER VARCHAR2(7) NOT NULL,
SYSTEM VARCHAR2(3) NOT NULL,
VIEW_ORDER NUMBER(2) NOT NULL
);
