CREATE TABLE CRS_PAX_DOCO (
APPLIC_COUNTRY VARCHAR2(3),
BIRTH_PLACE VARCHAR2(35),
ISSUE_DATE DATE,
ISSUE_PLACE VARCHAR2(35),
NO VARCHAR2(25),
PAX_ID NUMBER(9) NOT NULL,
PR_INF NUMBER(1) NOT NULL,
REM_CODE VARCHAR2(5) NOT NULL,
REM_STATUS VARCHAR2(2),
TYPE VARCHAR2(2)
);
