CREATE TABLE CRS_PAX_ASVC (
EMD_COUPON NUMBER(1),
EMD_NO VARCHAR2(15),
EMD_TYPE VARCHAR2(1),
PAX_ID NUMBER(9),
REM_STATUS VARCHAR2(2) NOT NULL,
RFIC VARCHAR2(1),
RFISC VARCHAR2(15),
SERVICE_NAME VARCHAR2(30),
SSR_CODE VARCHAR2(4)
);
