CREATE TABLE CRYPT_FILE_PARAMS (
CERTNAME VARCHAR2(50) NOT NULL,
DESK VARCHAR2(6),
DESK_GRP_ID NUMBER(9) NOT NULL,
KEYNAME VARCHAR2(50) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL,
PKCS_ID NUMBER(9) NOT NULL,
SEND_COUNT NUMBER(3) NOT NULL
);
