CREATE TABLE CRYPT_TERM_CERT (
CERTIFICATE VARCHAR2(4000) NOT NULL,
DESK VARCHAR2(6),
DESK_GRP_ID NUMBER(9) NOT NULL,
FIRST_DATE DATE NOT NULL,
ID NUMBER(9) NOT NULL,
LAST_DATE DATE NOT NULL,
PKCS_ID NUMBER(9),
PR_DENIAL NUMBER(1) NOT NULL
);
