CREATE TABLE DACHE_CHILD_FIELDS (
AUTO_INSERT NUMBER(1) NOT NULL,
CACHE_CHILD VARCHAR2(30) NOT NULL,
CACHE_PARENT VARCHAR2(30) NOT NULL,
CHECK_EQUAL NUMBER(1) NOT NULL,
FIELD_CHILD VARCHAR2(30),
FIELD_PARENT VARCHAR2(30) NOT NULL,
MODIFY_VAR VARCHAR2(30),
READ_ONLY NUMBER(1) NOT NULL,
SELECT_VAR VARCHAR2(30)
);
