CREATE TABLE DCS_ADDR_SET (
AIRLINE VARCHAR2(3) NOT NULL,
EDI_ADDR VARCHAR2(20) NOT NULL,
EDI_OWN_ADDR VARCHAR2(20) NOT NULL,
FLT_NO NUMBER(5),
ID NUMBER(9) NOT NULL,
IFM NUMBER(1),
AIRIMP_ADDR VARCHAR2(8),
AIRIMP_OWN_ADDR VARCHAR2(8)
);
