CREATE TABLE DESK_NOTICES (
DEFAULT_DISABLE NUMBER(1) NOT NULL,
DESK VARCHAR2(6),
DESK_GRP_ID NUMBER(9),
FIRST_VERSION VARCHAR2(20),
LAST_VERSION VARCHAR2(20),
NOTICE_ID NUMBER(9) NOT NULL,
NOTICE_TYPE NUMBER(2),
PR_DEL NUMBER(1) NOT NULL,
TERM_MODE VARCHAR2(10),
TIME_CREATE DATE NOT NULL
);
