CREATE TABLE DEV_MODEL_PARAMS (
DESK_GRP_ID NUMBER(9),
DEV_MODEL VARCHAR2(10),
EDITABLE NUMBER(1) NOT NULL,
FMT_TYPE VARCHAR2(10),
PARAM_NAME VARCHAR2(20) NOT NULL,
PARAM_VALUE VARCHAR2(100),
PR_SESS_PARAM NUMBER(1),
SESS_TYPE VARCHAR2(10),
SUBPARAM_NAME VARCHAR2(20)
);
