CREATE TABLE DOC (
CLOSE NUMBER(1) DEFAULT 0 ,
IDA NUMBER(4),
INTERNATIONAL NUMBER(1),
LCODED VARCHAR2(3),
LNAME VARCHAR2(50),
RCODED VARCHAR2(3),
RNAME VARCHAR2(50),
TYPE NUMBER(1),
VERSION NUMBER
);
