CREATE TABLE DROP_TEST_APIS2 (
AIRP_ARV VARCHAR2(3),
APIS_FORMATS VARCHAR2(100),
CREW_DOCAB_REQ NUMBER(5),
CREW_DOCAD_REQ NUMBER(5),
CREW_DOCAR_REQ NUMBER(5),
CREW_DOCO_REQ NUMBER(5),
CREW_DOC_REQ NUMBER(5),
CREW_TKN_REQ NUMBER(5),
IS_INTER NUMBER(2),
NOT_APIS NUMBER(2),
PASS_DOCAB_REQ NUMBER(5),
PASS_DOCAD_REQ NUMBER(5),
PASS_DOCAR_REQ NUMBER(5),
PASS_DOCO_REQ NUMBER(5),
PASS_DOC_REQ NUMBER(5),
PASS_TKN_REQ NUMBER(5),
POINT_ID NUMBER(9)
);
