CREATE TABLE DROP_TEST_RFISC_DIFF (
AIRLINE VARCHAR2(3) NOT NULL,
BAG_TYPES_ID NUMBER(9),
GRP_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
NAME_LAT VARCHAR2(100) NOT NULL,
PRIORITY NUMBER(6),
PR_CABIN NUMBER(1),
RFISC VARCHAR2(15) NOT NULL
);
