CREATE TABLE DROP_TEST_TYPEB_UTILS1 (
ADDR VARCHAR2(1000),
ADDR_NORMAL VARCHAR2(1000),
EXTRA VARCHAR2(50),
POINT_ID NUMBER(9) NOT NULL,
PR_LAT NUMBER(1) NOT NULL,
TLG_ID NUMBER(9) NOT NULL,
TYPE VARCHAR2(6) NOT NULL
);
