CREATE TABLE DROP_PC_WT_STAT (
COUPON_NO NUMBER(1) NOT NULL,
ETICK_NORM NUMBER(3),
ETICK_NORM_UNIT VARCHAR2(2) NOT NULL,
EVENTS_MSG VARCHAR2(250),
EVENTS_TIME DATE,
PAX_NORM VARCHAR2(20),
POINT_ID NUMBER(9) NOT NULL,
TICKET_NO VARCHAR2(15) NOT NULL
);
