CREATE TABLE DROP_REM_TYPES (
CODE VARCHAR2(4) NOT NULL,
CODE_LAT VARCHAR2(4) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(60),
PRIORITY NUMBER(1),
PR_COMP NUMBER(2),
PR_DEL NUMBER(1) NOT NULL,
PR_PSM NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL
);
