CREATE TABLE DROP_PRIOR_ROUTES (
DELTA_IN NUMBER(2),
DELTA_OUT NUMBER(2),
MOVE_ID NUMBER(9),
NUM NUMBER(3),
PRIOR_DELTA_IN NUMBER(2),
PRIOR_DELTA_OUT NUMBER(2),
PRIOR_SCD_IN DATE,
PRIOR_SCD_OUT DATE,
SCD_IN DATE,
SCD_OUT DATE
);
