CREATE TABLE DROP_EVENTS (
EV_ORDER NUMBER(9) NOT NULL,
EV_USER VARCHAR2(20),
ID1 NUMBER(9),
ID2 NUMBER(9),
ID3 NUMBER(9),
MSG VARCHAR2(250) NOT NULL,
PR_DEL NUMBER(1),
SCREEN VARCHAR2(15),
STATION VARCHAR2(15),
TIME DATE NOT NULL,
TYPE VARCHAR2(3) NOT NULL
);
