CREATE TABLE EDI_HELP (
ADDRESS VARCHAR2(40) NOT NULL,
DATE1 DATE,
INSTANCE VARCHAR2(3),
INTMSGID RAW(12) NOT NULL,
PULT VARCHAR2(6),
SESSION_ID NUMBER NOT NULL,
TEXT VARCHAR2(1000) NOT NULL,
TIMEOUT DATE
);
