CREATE TABLE EDIFACT_PROFILES (
CTRL_AGENCY VARCHAR2(2) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
SUB_VERSION NUMBER NOT NULL,
SYNTAX_NAME VARCHAR2(4) NOT NULL,
SYNTAX_VER NUMBER NOT NULL,
VERSION NUMBER NOT NULL
);
