create table EDIFACT_PROFILES
(
NAME         VARCHAR2(30) NOT NULL,
VERSION      NUMBER NOT NULL,
SUB_VERSION  NUMBER NOT NULL,
CTRL_AGENCY  VARCHAR2(2) NOT NULL,
SYNTAX_NAME  VARCHAR2(4) NOT NULL,
SYNTAX_VER   NUMBER NOT NULL
);
