CREATE TABLE EDISESSION (
SYSTEM_ID NUMBER(9),
FLAGS NUMBER,
IDA NUMBER(9) NOT NULL,
LAST_ACCESS DATE DEFAULT sysdate NOT NULL,
OTHERCARF VARCHAR2(50),
OTHERREF VARCHAR2(14),
OTHERREFNUM NUMBER(4),
OURREF VARCHAR2(14) NOT NULL,
OURREFNUM NUMBER(4) NOT NULL,
PRED_P VARCHAR2(6),
PULT VARCHAR2(6),
SESSDATECR DATE NOT NULL,
STATUS VARCHAR2(1) NOT NULL,
OURCARF VARCHAR2(17) NOT NULL,
MSG_ID NUMBER,
TIMEOUT DATE,
SYSTEM_TYPE  VARCHAR2(3),
SESSION_TYPE VARCHAR(4),
ACCESS_KEY VARCHAR(10)
);
ALTER TABLE EDISESSION ADD CONSTRAINT EDISESSION_PK_IDA PRIMARY KEY (IDA)
ENABLE;
