CREATE TABLE EDISESSION_TIMEOUTS
(
  INSTANCE VARCHAR2(3),
  SESS_IDA NUMBER NOT NULL,
  MSG_NAME VARCHAR2(6) NOT NULL,
  FUNC_CODE VARCHAR2(3),
  TIME_OUT DATE NOT NULL
);
ALTER TABLE EDISESSION_TIMEOUTS ADD CONSTRAINT EDISESSION_TIMEOUTS_IDA_PK PRIMARY KEY (SESS_IDA) ENABLE;
