CREATE TABLE ETICKS_DISPLAY (
BAG_NORM NUMBER(3),
BAG_NORM_UNIT VARCHAR2(2),
COUPON_NO NUMBER(1) NOT NULL,
FARE_BASIS VARCHAR2(15) NOT NULL,
ISSUE_DATE DATE NOT NULL,
LAST_DISPLAY DATE NOT NULL,
NAME VARCHAR2(70),
POINT_ID NUMBER(9),
SUBCLS VARCHAR2(3),
SURNAME VARCHAR2(70) NOT NULL,
TICKET_NO VARCHAR2(20) NOT NULL
);
