CREATE TABLE GOS (
CLOSE NUMBER(1) DEFAULT 0,
CODEAREA NUMBER(9) DEFAULT 0,
CODEW NUMBER(9),
CODEWT NUMBER(9) DEFAULT 0,
IDA NUMBER(9),
ISO_CODEG VARCHAR2(3),
LCODEG VARCHAR2(2),
LNAME VARCHAR2(25),
MCIS NUMBER(1),
NODST NUMBER(1),
NOT_COUNTRY NUMBER(1),
RCODEG VARCHAR2(2),
RNAME VARCHAR2(25),
VERSION NUMBER
);
