CREATE TABLE H2H_TLGS (
ERR VARCHAR2(2),
ID NUMBER(9) NOT NULL,
QRI5 VARCHAR2(1) NOT NULL,
QRI6 VARCHAR2(1) NOT NULL,
RECEIVER VARCHAR2(20) NOT NULL,
SENDER VARCHAR2(20) NOT NULL,
TPR VARCHAR2(20) NOT NULL,
TYPE VARCHAR2(1) NOT NULL
);
