CREATE TABLE HIST_TYPEB_SEND (
AIRLINE VARCHAR2(3),
AIRP_ARV VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL,
TLG_TYPE VARCHAR2(6) NOT NULL
);
