CREATE TABLE HIST_USER_SETS (
DISP_AIRLINE NUMBER(2),
DISP_AIRP NUMBER(2),
DISP_CRAFT NUMBER(2),
DISP_SUFFIX NUMBER(2),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
TIME NUMBER(2),
USER_ID NUMBER(9) NOT NULL
);
