CREATE TABLE HIST_COMP_REM_TYPES (
CODE VARCHAR2(4) NOT NULL,
CODE_LAT VARCHAR2(4) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(60),
PR_COMP NUMBER(2) NOT NULL,
PR_DEL NUMBER(1) NOT NULL
);
