CREATE TABLE HIST_DCS_SERVICE_APPLYING (
AIRLINE VARCHAR2(3) NOT NULL,
BRAND_AIRLINE VARCHAR2(3),
BRAND_CODE VARCHAR2(10),
CLASS VARCHAR2(1),
DCS_SERVICE VARCHAR2(20) NOT NULL,
FQT_AIRLINE VARCHAR2(3),
FQT_TIER_LEVEL VARCHAR2(50),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL,
RFISC VARCHAR2(15) NOT NULL
);
