CREATE TABLE HIST_BT_SET (
AIRLINE VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
TAG_TYPE VARCHAR2(5) NOT NULL
);
