CREATE TABLE HIST_BRANDS (
AIRLINE VARCHAR2(3) NOT NULL,
CODE VARCHAR2(10) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50) NOT NULL
);
