CREATE TABLE HIST_ROT (
CANON_NAME VARCHAR2(5) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
IP_ADDRESS VARCHAR2(15) NOT NULL,
IP_PORT NUMBER(5) NOT NULL,
OWN_CANON_NAME VARCHAR2(5) NOT NULL
);
