CREATE TABLE HIST_TRIP_LITERS (
CODE VARCHAR2(3) NOT NULL,
CODE_LAT VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50),
NAME_LAT VARCHAR2(50),
PR_DEL NUMBER(1) NOT NULL
);
