CREATE TABLE HIST_SEAT_ALGO_SETS (
AIRLINE VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
ALGO_TYPE NUMBER(2) NOT NULL,
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_SEAT_IN_ROW NUMBER(1) NOT NULL
);
