CREATE TABLE HIST_TYPEB_ADDR_TRANS_PARAMS (
ADDR VARCHAR2(7) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PARAM_NAME VARCHAR2(20) NOT NULL,
PARAM_VALUE VARCHAR2(100) NOT NULL
);
