CREATE TABLE HIST_CRYPT_REQ_DATA (
CITY VARCHAR2(128),
COUNTRY VARCHAR2(2) NOT NULL,
DESK VARCHAR2(6),
DESK_GRP_ID NUMBER(9) NOT NULL,
EMAIL VARCHAR2(40),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
KEYSLENGTH NUMBER(4),
KEY_ALGO VARCHAR2(20),
ORGANIZATION VARCHAR2(64),
ORGANIZATIONAL_UNIT VARCHAR2(64),
PR_DENIAL NUMBER(1) NOT NULL,
STATE VARCHAR2(128),
TITLE VARCHAR2(64),
USER_NAME VARCHAR2(64)
);
