CREATE TABLE HIST_DELAYS (
CODE VARCHAR2(3) NOT NULL,
CODE_LAT VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(300) NOT NULL,
NAME_LAT VARCHAR2(300),
NUM NUMBER(3) NOT NULL
);
