CREATE TABLE HIST_GRAPH_TIMES (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
CRAFT VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
STAGE_ID NUMBER(2) NOT NULL,
TIME NUMBER(4) NOT NULL,
TRIP_TYPE VARCHAR2(1)
);
