CREATE TABLE HIST_DOC_NUM_COPIES (
AIRLINE VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NUM NUMBER(3) NOT NULL,
REPORT_TYPE VARCHAR2(100) NOT NULL
);
