CREATE TABLE HIST_PERS_WEIGHTS (
AIRLINE VARCHAR2(3),
BORT VARCHAR2(10),
CHILD NUMBER(2) NOT NULL,
CLASS VARCHAR2(1),
CRAFT VARCHAR2(3),
FEMALE NUMBER(3),
FIRST_DATE DATE,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
INFANT NUMBER(2) NOT NULL,
LAST_DATE DATE,
MALE NUMBER(3) NOT NULL,
PR_SUMMER NUMBER(1),
SUBCLASS VARCHAR2(1)
);
