CREATE TABLE HIST_TAG_COLORS (
CODE VARCHAR2(2) NOT NULL,
CODE_LAT VARCHAR2(2),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
NAME_LAT VARCHAR2(20)
);
