CREATE TABLE HIST_PLACE_CALC (
BC VARCHAR2(3) NOT NULL,
COD_IN VARCHAR2(3) NOT NULL,
COD_OUT VARCHAR2(3) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
TIME_OUT_IN DATE,
TIME_OUT_OUT DATE,
TROUND_IN NUMBER(3),
TROUND_OUT NUMBER(3)
);
