CREATE TABLE HIST_APIS_SETS (
AIRLINE VARCHAR2(3) NOT NULL,
COUNTRY_ARV VARCHAR2(2) NOT NULL,
COUNTRY_DEP VARCHAR2(2) NOT NULL,
DIR VARCHAR2(50) NOT NULL,
EDI_ADDR VARCHAR2(40),
EDI_OWN_ADDR VARCHAR2(40),
FORMAT VARCHAR2(10) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL
);
