CREATE TABLE HIST_TYPEB_ADDR_OWNERS (
ADDR VARCHAR2(7) NOT NULL,
COUNTRY VARCHAR2(2),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
TRANSPORT_ADDR VARCHAR2(6) NOT NULL,
TRANSPORT_TYPE VARCHAR2(20) NOT NULL
);
