CREATE TABLE HIST_RFISC_RATES (
AIRLINE VARCHAR2(3) NOT NULL,
BRAND VARCHAR2(10) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
RATE NUMBER(12) NOT NULL,
RATE_CUR VARCHAR2(3) NOT NULL,
RFISC VARCHAR2(15) NOT NULL,
SALE_FIRST_DATE DATE NOT NULL,
SALE_LAST_DATE DATE
);
