CREATE TABLE HIST_TRFER_SET_FLTS (
FLT_NO NUMBER(5) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_ONWARD NUMBER(1) NOT NULL,
TRFER_SET_ID NUMBER(9) NOT NULL
);
