CREATE TABLE HIST_PAID_CKIN_SETS (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3),
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PROT_TIMEOUT NUMBER(3),
PR_PERMIT NUMBER(1) NOT NULL
);
