CREATE TABLE HIST_CKIN_REM_TYPES (
CODE VARCHAR2(4) NOT NULL,
CODE_LAT VARCHAR2(4) NOT NULL,
GRP_ID NUMBER(2) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
IS_IATA NUMBER(1) NOT NULL,
NAME VARCHAR2(200) NOT NULL,
NAME_LAT VARCHAR2(200),
PR_DEL NUMBER(1) NOT NULL
);
