CREATE TABLE HIST_HALLS2 (
AIRP VARCHAR2(3) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
NAME_LAT VARCHAR2(20),
PR_VIP NUMBER(1) NOT NULL,
RPT_GRP VARCHAR2(10)
);
