CREATE TABLE HIST_COMP_SUBCLS_SETS (
AIRLINE VARCHAR2(3) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
REM VARCHAR2(4) NOT NULL,
SUBCLASS VARCHAR2(1) NOT NULL
);
