CREATE TABLE HIST_BI_HALLS (
AIRP VARCHAR2(3) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
NAME_LAT VARCHAR2(40),
TERMINAL NUMBER(9)
);
