CREATE TABLE HIST_KIOSKS_GRP (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9),
NAME VARCHAR2(250) NOT NULL,
NAME_LAT VARCHAR2(250) NOT NULL
);
