CREATE TABLE HIST_BI_PRINT_RULES (
AIRLINE VARCHAR2(3) NOT NULL,
BRAND_AIRLINE VARCHAR2(3),
BRAND_CODE VARCHAR2(10),
CLASS VARCHAR2(1),
FQT_AIRLINE VARCHAR2(3),
FQT_TIER_LEVEL VARCHAR2(50),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PRINT_TYPE VARCHAR2(3) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL,
REM_CODE VARCHAR2(4),
SUBCLASS VARCHAR2(1)
);
