CREATE TABLE HIST_PRIORITY_CARD_TYPES (
AIRLINE VARCHAR2(3) NOT NULL,
CARD_TYPE VARCHAR2(20) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
MAX_SIGNS NUMBER(9) NOT NULL,
REM_CODE VARCHAR2(20)
);
