CREATE TABLE HIST_DESK_GRP_SETS (
DEFER_ETSTATUS NUMBER(1) NOT NULL,
GRP_ID NUMBER(9) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
INF_SEATS_FMT NUMBER(1),
PERS_COUNT_FMT NUMBER(1)
);
