CREATE TABLE HIST_RFISC_COMP_PROPS (
AIRLINE VARCHAR2(3) NOT NULL,
CODE VARCHAR2(15) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
RATE_COLOR VARCHAR2(10) NOT NULL
);
