CREATE TABLE HIST_COUNTRIES (
CODE VARCHAR2(2) NOT NULL,
CODE_ISO VARCHAR2(3),
CODE_LAT VARCHAR2(2),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PR_DEL NUMBER(1) NOT NULL
);
