CREATE TABLE HIST_HALL_SET (
AIRLINE VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
FLT_NO NUMBER(5),
HALL NUMBER(9),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_MISC NUMBER(1) NOT NULL,
TYPE NUMBER(3) NOT NULL
);
