CREATE TABLE HIST_BAG_TYPES (
CODE NUMBER(2) NOT NULL,
DESCR VARCHAR2(2000),
DESCR_LAT VARCHAR2(2000),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50)
);
