CREATE TABLE HIST_TYPEB_ADDR_OPTIONS (
CATEGORY VARCHAR2(20) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
TLG_TYPE VARCHAR2(6) NOT NULL,
TYPEB_ADDRS_ID NUMBER(9) NOT NULL,
VALUE VARCHAR2(10)
);
