CREATE TABLE HIST_BI_PRINT_RULES (
AIRLINE VARCHAR2(3) NOT NULL,
CARD_TYPE NUMBER(9),
CLS VARCHAR2(1),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_ISSUE NUMBER(1) NOT NULL,
REG_GROUP VARCHAR2(5) NOT NULL,
REM_CODE VARCHAR2(20),
SUBCLS VARCHAR2(1)
);
