CREATE TABLE HIST_PACTS (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3) NOT NULL,
DESCR VARCHAR2(50) NOT NULL,
FIRST_DATE DATE NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
LAST_DATE DATE
);
