CREATE TABLE HIST_FILE_ENCODING (
ENCODING VARCHAR2(40) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
OWN_POINT_ADDR VARCHAR2(6) NOT NULL,
POINT_ADDR VARCHAR2(6) NOT NULL,
PR_SEND NUMBER(1) NOT NULL,
TYPE VARCHAR2(10) NOT NULL
);
