CREATE TABLE HIST_STAGE_NAMES (
AIRP VARCHAR2(3) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
STAGE_ID NUMBER(2) NOT NULL
);
