CREATE TABLE HIST_TAG_TYPES (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
CODE VARCHAR2(5) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NO_LEN NUMBER(2) NOT NULL,
PRINTABLE NUMBER(1)
);
