CREATE TABLE HISTORY_EVENTS (
CLOSE_DESK VARCHAR2(6),
CLOSE_TIME DATE NOT NULL,
CLOSE_USER VARCHAR2(20),
HIST_ORDER NUMBER(9) NOT NULL,
OPEN_DESK VARCHAR2(6),
OPEN_TIME DATE NOT NULL,
OPEN_USER VARCHAR2(20),
ROW_IDENT NUMBER(9) NOT NULL,
TABLE_ID NUMBER(9) NOT NULL
);
