CREATE TABLE HIST_RFISC_RATES_SELF_CKIN (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_ARV VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
CRAFT VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
RATE NUMBER(12) NOT NULL,
RATE_CUR VARCHAR2(3) NOT NULL,
RFISC VARCHAR2(15) NOT NULL
);
