CREATE TABLE HIST_SALE_POINTS (
AGENCY VARCHAR2(5) NOT NULL,
CITY VARCHAR2(3) NOT NULL,
CODE VARCHAR2(8) NOT NULL,
DESCR VARCHAR2(30) NOT NULL,
DESCR_LAT VARCHAR2(30),
FORMS VARCHAR2(30),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PHONE VARCHAR2(20),
PR_PERMIT NUMBER(1) NOT NULL,
VALIDATOR VARCHAR2(4) NOT NULL
);
