CREATE TABLE HIST_SPECIAL_ENTER (
AIRLINE VARCHAR2(3),
CARD_NUM VARCHAR2(50),
CARD_TYPE VARCHAR2(50),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9),
REM_CODE VARCHAR2(4),
STATUS VARCHAR2(50)
);
