CREATE TABLE HIST_DESK_OWNERS (
AIRLINE VARCHAR2(3),
CHAN_ID NUMBER(9),
DESK VARCHAR2(6) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL
);
