CREATE TABLE HOTEL_ACMD_PAX (
BREAKFAST NUMBER(1) NOT NULL,
DINNER NUMBER(1) NOT NULL,
HOTEL_ID NUMBER(9) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
ROOM_TYPE NUMBER(9) NOT NULL,
SUPPER NUMBER(1) NOT NULL
);
