CREATE TABLE IATCI_SEG (
AIRLINE VARCHAR2(3) NOT NULL,
ARR_DATE DATE,
ARR_PORT VARCHAR2(3) NOT NULL,
ARR_TIME DATE,
DEP_DATE DATE,
DEP_PORT VARCHAR2(3) NOT NULL,
DEP_TIME DATE,
FLT_NO NUMBER(5) NOT NULL,
GRP_ID NUMBER(9),
NUM NUMBER(2) NOT NULL
);
