CREATE TABLE KIOSK_EVENTS (
APPLICATION VARCHAR2(50),
EV_ORDER NUMBER(9) NOT NULL,
ID NUMBER(9) NOT NULL,
KIOSKID VARCHAR2(50),
SCREEN VARCHAR2(50),
SESSION_ID VARCHAR2(32),
TIME DATE NOT NULL,
TYPE VARCHAR2(50)
);
