CREATE TABLE MSG_QUEUE (
CONSEQ_CRC NUMBER(10),
DUP_KEY NUMBER(9),
FORMAT VARCHAR2(20) NOT NULL,
HANDLER VARCHAR2(20) NOT NULL,
ID NUMBER(9) NOT NULL,
PRIORITY NUMBER(2) NOT NULL,
PROCESS VARCHAR2(20),
PROC_ATTEMPT NUMBER(2),
PROC_TIME_MSEC NUMBER(16),
PUT_ORDER NUMBER(9) NOT NULL,
PUT_TIME_MSEC NUMBER(16) NOT NULL,
RELEASE_ATTEMPT NUMBER(1) NOT NULL,
STATUS VARCHAR2(4) NOT NULL,
TIME DATE NOT NULL,
TYPE VARCHAR2(3) NOT NULL
);
