CREATE TABLE MSGS (
BINARY_DATA NUMBER(1) NOT NULL,
ERROR VARCHAR2(100),
FORMAT VARCHAR2(20) NOT NULL,
HANDLER VARCHAR2(20) NOT NULL,
ID NUMBER(9) NOT NULL,
TIME DATE NOT NULL,
TYPE VARCHAR2(3) NOT NULL
);
