CREATE TABLE PAID_BAG_EMD (
BAG_TYPE NUMBER(2),
DROP_HANDMADE NUMBER(1),
EMD_COUPON NUMBER(1) NOT NULL,
EMD_NO VARCHAR2(15) NOT NULL,
GRP_ID NUMBER(9) NOT NULL,
PAX_ID NUMBER(9),
RFISC VARCHAR2(15),
TRANSFER_NUM NUMBER(1),
WEIGHT NUMBER(6) NOT NULL
);
