CREATE TABLE PAX_NORMS_TEXT (
AIRLINE VARCHAR2(3) NOT NULL,
CARRY_ON NUMBER(1) NOT NULL,
CONCEPT VARCHAR2(10) NOT NULL,
LANG VARCHAR2(2) NOT NULL,
PAGE_NO NUMBER(9) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
TEXT VARCHAR2(4000) NOT NULL,
TRANSFER_NUM NUMBER(1) NOT NULL
);

ALTER TABLE pax_norms_text
ADD CONSTRAINT pax_norms_text__PK PRIMARY KEY(pax_id, transfer_num, carry_on, lang, page_no);
