CREATE TABLE PAX_RFISC_STATUS (
AIRLINE VARCHAR2(3) NOT NULL,
LIST_ID NUMBER(9) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
RFISC VARCHAR2(15) NOT NULL,
SERVICE_QUANTITY NUMBER(3) NOT NULL,
SERVICE_TYPE VARCHAR2(1) NOT NULL,
STATUS VARCHAR2(10) NOT NULL,
TRANSFER_NUM NUMBER(1) NOT NULL
);
