CREATE TABLE PAX_EMD (
EMD_COUPON NUMBER(1) NOT NULL,
EMD_NO VARCHAR2(15) NOT NULL,
EMD_NO_BASE VARCHAR2(15) NOT NULL,
EMD_TYPE VARCHAR2(1) NOT NULL,
ET_COUPON NUMBER(1) NOT NULL,
ET_NO VARCHAR2(15) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
RFIC VARCHAR2(1) NOT NULL,
RFISC VARCHAR2(15) NOT NULL,
SERVICE_NAME VARCHAR2(100) NOT NULL,
SSR_CODE VARCHAR2(4),
TRANSFER_NUM NUMBER(1) NOT NULL
);
