CREATE TABLE PAX_DOC (
BIRTH_DATE DATE,
EXPIRY_DATE DATE,
FIRST_NAME VARCHAR2(64),
GENDER VARCHAR2(2),
ISSUE_COUNTRY VARCHAR2(3),
NATIONALITY VARCHAR2(3),
NO VARCHAR2(15),
PAX_ID NUMBER(9) NOT NULL,
PR_MULTI NUMBER(1) NOT NULL,
SECOND_NAME VARCHAR2(64),
SURNAME VARCHAR2(64),
TYPE VARCHAR2(2),
TYPE_RCPT VARCHAR2(3)
);
