CREATE TABLE PAX_DOCO (
APPLIC_COUNTRY VARCHAR2(3),
BIRTH_PLACE VARCHAR2(35),
EXPIRY_DATE DATE,
ISSUE_DATE DATE,
ISSUE_PLACE VARCHAR2(35),
NO VARCHAR2(25),
PAX_ID NUMBER(9) NOT NULL,
PR_INF NUMBER(1) NOT NULL,
TYPE VARCHAR2(2)
);
