CREATE TABLE PAX_DOCA (
ADDRESS VARCHAR2(35),
CITY VARCHAR2(35),
COUNTRY VARCHAR2(3),
PAX_ID NUMBER(9) NOT NULL,
POSTAL_CODE VARCHAR2(17),
PR_INF NUMBER(1) NOT NULL,
REGION VARCHAR2(35),
TYPE VARCHAR2(1) NOT NULL
);
