CREATE TABLE PAX_SERVICES_AUTO (
EMD_COUPON NUMBER(1) NOT NULL,
EMD_NO VARCHAR2(15) NOT NULL,
EMD_TYPE VARCHAR2(1) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
RFIC VARCHAR2(1) NOT NULL,
RFISC VARCHAR2(15) NOT NULL,
SERVICE_NAME VARCHAR2(100) NOT NULL,
SERVICE_QUANTITY NUMBER(3),
SSR_CODE VARCHAR2(4),
TRANSFER_NUM NUMBER(1) NOT NULL
);
