CREATE TABLE PORTS_LEO (
CITY_IATA VARCHAR2(4),
CLOSE NUMBER,
CODE_EN VARCHAR2(4),
CODE_RU VARCHAR2(4),
IDA NUMBER,
IDA_CITY NUMBER,
LATIT NUMBER,
LONGIT NUMBER,
NAME_EN VARCHAR2(1000),
NAME_IATA VARCHAR2(1000),
NAME_RU VARCHAR2(1000),
VERSION NUMBER
);
