CREATE TABLE RCPT_DOC_TYPES (
CODE VARCHAR2(3) NOT NULL,
CODE_LAT VARCHAR2(3) NOT NULL,
CODE_MINTRANS VARCHAR2(2) NOT NULL,
CODE_PAX_DOC VARCHAR2(2),
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(250) NOT NULL,
NAME_LAT VARCHAR2(250),
PR_DEL NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL,
TID_SYNC NUMBER(9) NOT NULL
);
