CREATE TABLE REM_EVENT_SETS (
AIRLINE VARCHAR2(3),
EVENT_TYPE VARCHAR2(20) NOT NULL,
EVENT_VALUE NUMBER(1) NOT NULL,
ID NUMBER(9) NOT NULL,
REM_CODE VARCHAR2(4) NOT NULL,
SET_ID NUMBER(9) NOT NULL
);
