CREATE TABLE ROT (
CANON_NAME VARCHAR2(5) NOT NULL,
ID NUMBER(9) NOT NULL,
IP_ADDRESS VARCHAR2(15) NOT NULL,
IP_PORT NUMBER(5) NOT NULL,
OWN_CANON_NAME VARCHAR2(5) NOT NULL,
H2H NUMBER(1),
H2H_ADDR VARCHAR2(20),
OUR_H2H_ADDR VARCHAR2(20),
RESP_TIMEOUT NUMBER(2),
ROUTER_TRANSLIT NUMBER(1),
LOOPBACK NUMBER(1)
);
