CREATE TABLE SBDO_TAGS_ACTIVATED (
AIRLINE VARCHAR2(3) NOT NULL,
BAG_TYPE VARCHAR2(15),
LIST_ID NUMBER(9) NOT NULL,
NO NUMBER(15) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
RFISC VARCHAR2(15),
SERVICE_TYPE VARCHAR2(20),
WEIGHT NUMBER(4) NOT NULL
);
