CREATE TABLE SCHED_ROUTES (
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_ARV_FMT NUMBER(1) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
AIRP_DEP_FMT NUMBER(1) NOT NULL,
EQUIPS_ID NUMBER(9) NOT NULL,
PAX_SCD_OUT DATE,
ROUTES_ID NUMBER(9) NOT NULL,
ROUTE_NUM NUMBER(3) NOT NULL,
SCD_IN DATE,
SCD_OUT DATE,
VAR_SCD_IN NUMBER(1) NOT NULL,
VAR_SCD_OUT NUMBER(1) NOT NULL
);
