CREATE TABLE SCHEDULE_TEST (
AIRP_IN VARCHAR2(3),
AIRP_OUT VARCHAR2(3),
CRAFT_TYPE VARCHAR2(3),
F_LINE VARCHAR2(3),
F_NUMBER NUMBER(9),
F_SUFFIX NUMBER(9),
P_DATE1 DATE,
P_DATE2 DATE,
P_FREQ VARCHAR2(7),
RBD_LAYOUT VARCHAR2(400),
SCD_IN DATE,
SCD_OUT DATE,
SERV_TYPE NUMBER(9)
);
