CREATE TABLE SCHED_SEGMENTS (
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_ARV_FMT NUMBER(1) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
AIRP_DEP_FMT NUMBER(1) NOT NULL,
DEI8_DATA VARCHAR2(100),
DEI8_DEI NUMBER(3),
DEI8_TRC VARCHAR2(100),
OTHER_DATA VARCHAR2(100),
OTHER_DEI NUMBER(3),
SEGS_ID NUMBER(9) NOT NULL,
SEG_NUM NUMBER(3) NOT NULL
);
