CREATE TABLE SERVICE_STAT (
AIRP_LAST VARCHAR2(3) NOT NULL,
DESK VARCHAR2(6) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
REM_CODE VARCHAR2(4) NOT NULL,
TICKET_NO VARCHAR2(20),
TRAVEL_TIME DATE,
USER_ID NUMBER(9) NOT NULL
);
