CREATE TABLE SNAPSHOT_POINTS (
ATTR VARCHAR2(100),
FILE_TYPE VARCHAR2(10) NOT NULL,
PAGE_NO NUMBER(9) NOT NULL,
POINT_ADDR VARCHAR2(6) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
RECORD VARCHAR2(4000) NOT NULL
);
