CREATE TABLE SPECIAL_ENTER (
AIRLINE VARCHAR2(3) NOT NULL,
CARD_NUM VARCHAR2(50) NOT NULL,
CARD_TYPE VARCHAR2(50) NOT NULL,
ID NUMBER(9) NOT NULL,
REM_CODE VARCHAR2(4) NOT NULL,
STATUS VARCHAR2(50) NOT NULL
);
