CREATE TABLE STAT_ORDERS (
COMPRESSED_DATA_SIZE NUMBER,
DATA_SIZE NUMBER,
FILE_ID NUMBER(9) NOT NULL,
PROGRESS NUMBER NOT NULL,
SOURCE VARCHAR2(100) NOT NULL,
TIME_CREATED DATE,
TIME_ORDERED DATE NOT NULL,
USER_ID NUMBER(9) NOT NULL
);
