CREATE TABLE STAT_ORDERS (
DATA_SIZE NUMBER(10),
DATA_SIZE_ZIP NUMBER(10),
ERROR VARCHAR2(250),
FILE_ID NUMBER(9) NOT NULL,
PROGRESS NUMBER(3) NOT NULL,
SOURCE VARCHAR2(100) NOT NULL,
STATUS NUMBER(1) NOT NULL,
TIME_CREATED DATE,
TIME_ORDERED DATE NOT NULL,
USER_ID NUMBER(9) NOT NULL
);
