CREATE TABLE STATIONS (
AIRP VARCHAR2(3) NOT NULL,
DESK VARCHAR2(6) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(6) NOT NULL,
USING_SCALES NUMBER(1) NOT NULL,
WITHOUT_MONITOR NUMBER(1) NOT NULL,
WORK_MODE VARCHAR2(1) NOT NULL
);
