CREATE TABLE STAT_AD (
BAG_AMOUNT NUMBER(9),
BAG_WEIGHT NUMBER(9),
CLASS VARCHAR2(1) NOT NULL,
CLIENT_TYPE VARCHAR2(5) NOT NULL,
DESK VARCHAR2(6) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
PNR VARCHAR2(20),
POINT_ID NUMBER(9) NOT NULL,
SCD_OUT DATE NOT NULL,
SEAT_NO VARCHAR2(50),
SEAT_NO_LAT VARCHAR2(50),
STATION VARCHAR2(6)
);
