CREATE TABLE STAT_HA (
ADT NUMBER(3) NOT NULL,
CHD NUMBER(3) NOT NULL,
HOTEL_ID NUMBER(9) NOT NULL,
INF NUMBER(3) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
ROOM_TYPE NUMBER(9) NOT NULL,
SCD_OUT DATE NOT NULL,
TOTAL NUMBER(4) NOT NULL
);
