CREATE TABLE TAG_RANGES2 (
AIRCODE NUMBER(3) NOT NULL,
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
CLASS VARCHAR2(1),
LAST_ACCESS DATE NOT NULL,
NO NUMBER(2) NOT NULL,
POINT_ID NUMBER(9),
RANGE NUMBER(4) NOT NULL
);
