CREATE TABLE TEST_PAX (
AIRLINE VARCHAR2(3),
DOC_NO VARCHAR2(15),
FQT_NO VARCHAR2(25),
ID NUMBER(10) NOT NULL,
NAME VARCHAR2(20),
PNR_ADDR VARCHAR2(20),
PNR_AIRLINE VARCHAR2(3),
REG_NO NUMBER(3) NOT NULL,
SEAT_XNAME VARCHAR2(1),
SEAT_YNAME VARCHAR2(3),
SUBCLASS VARCHAR2(1) NOT NULL,
SURNAME VARCHAR2(20) NOT NULL,
TKN_NO VARCHAR2(15)
);
