CREATE TABLE TEST_CRYPT_SERVER (
CERTIFICATE VARCHAR2(4000) NOT NULL,
FIRST_DATE DATE NOT NULL,
ID NUMBER(9) NOT NULL,
LAST_DATE DATE NOT NULL,
PRIVATE_KEY VARCHAR2(4000),
PR_CA NUMBER(1) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL
);
