CREATE TABLE TLG_COMP_LAYERS (
AIRP_ARV VARCHAR2(3) NOT NULL,
CRS_PAX_ID NUMBER(9),
FIRST_XNAME VARCHAR2(4) NOT NULL,
FIRST_YNAME VARCHAR2(4) NOT NULL,
LAST_XNAME VARCHAR2(4) NOT NULL,
LAST_YNAME VARCHAR2(4) NOT NULL,
LAYER_TYPE VARCHAR2(10) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
RANGE_ID NUMBER(9) NOT NULL,
REM_CODE VARCHAR2(5),
TIME_REMOVE DATE,
TLG_ID NUMBER(9)
);
