CREATE TABLE TLG_QUEUE (
ID NUMBER(9) NOT NULL,
LAST_SEND NUMBER(16),
PRIORITY NUMBER(1) NOT NULL,
PROC_ATTEMPT NUMBER(1),
RECEIVER VARCHAR2(5) NOT NULL,
SENDER VARCHAR2(5) NOT NULL,
STATUS VARCHAR2(4) NOT NULL,
TIME DATE NOT NULL,
TIME_MSEC NUMBER(16) NOT NULL,
TLG_NUM NUMBER(10) NOT NULL,
TTL NUMBER(5),
TYPE VARCHAR2(4) NOT NULL
);
