CREATE TABLE TLGS_IN (
ADDR VARCHAR2(300),
BODY LONG,
ENDING VARCHAR2(20),
HEADING VARCHAR2(100),
ID NUMBER(9) NOT NULL,
IS_FINAL_PART NUMBER(1) NOT NULL,
MERGE_KEY VARCHAR2(50),
NUM NUMBER(5) NOT NULL,
TIME_CREATE DATE,
TIME_PARSE DATE,
TIME_RECEIVE DATE NOT NULL,
TIME_RECEIVE_NOT_PARSE DATE,
TYPE VARCHAR2(3)
);
