CREATE TABLE TRFER_TRIPS (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
FLT_NO NUMBER(5) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
POINT_ID_SPP NUMBER(9),
SCD DATE NOT NULL,
SUFFIX VARCHAR2(1)
);
