CREATE TABLE TRFER_STAT (
ADULT NUMBER(3) NOT NULL,
BABY NUMBER(3) NOT NULL,
BABY_WOP NUMBER(3) NOT NULL,
C NUMBER(3) NOT NULL,
CHILD NUMBER(3) NOT NULL,
CHILD_WOP NUMBER(3) NOT NULL,
CLIENT_TYPE VARCHAR2(5) NOT NULL,
EXCESS NUMBER(6) NOT NULL,
F NUMBER(3) NOT NULL,
PCS NUMBER(5) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
TRFER_ROUTE VARCHAR2(200) NOT NULL,
UNCHECKED NUMBER(6) NOT NULL,
WEIGHT NUMBER(6) NOT NULL,
Y NUMBER(3) NOT NULL
);
