CREATE TABLE TRFER_SETS (
AIRLINE_IN VARCHAR2(3) NOT NULL,
AIRLINE_OUT VARCHAR2(3) NOT NULL,
AIRP VARCHAR2(3) NOT NULL,
ID NUMBER(9) NOT NULL,
MAX_INTERVAL NUMBER(4),
MIN_INTERVAL NUMBER(4),
TCKIN_NOREC NUMBER(1) NOT NULL,
TCKIN_PERMIT NUMBER(1) NOT NULL,
TCKIN_WAITLIST NUMBER(1) NOT NULL,
TRFER_OUTBOARD NUMBER(1) NOT NULL,
TRFER_PERMIT NUMBER(1) NOT NULL
);
