CREATE TABLE TRIP_CKIN_CLIENT (
CLIENT_TYPE VARCHAR2(5) NOT NULL,
DESK_GRP_ID NUMBER(9),
POINT_ID NUMBER(9) NOT NULL,
PR_PERMIT NUMBER(1) NOT NULL,
PR_TCKIN NUMBER(1) NOT NULL,
PR_UPD_STAGE NUMBER(1) NOT NULL,
PR_WAITLIST NUMBER(1) NOT NULL
);
