CREATE TABLE TRIP_COMP_LAYERS (
CRS_PAX_ID NUMBER(9),
FIRST_XNAME VARCHAR2(4) NOT NULL,
FIRST_YNAME VARCHAR2(4) NOT NULL,
LAST_XNAME VARCHAR2(4) NOT NULL,
LAST_YNAME VARCHAR2(4) NOT NULL,
LAYER_TYPE VARCHAR2(10) NOT NULL,
PAX_ID NUMBER(9),
POINT_ARV NUMBER(9),
POINT_DEP NUMBER(9),
POINT_ID NUMBER(9) NOT NULL,
RANGE_ID NUMBER(9) NOT NULL,
TIME_CREATE DATE NOT NULL
);
