CREATE TABLE TRIP_PERS_WEIGHTS (
CHILD NUMBER(2) NOT NULL,
CLASS VARCHAR2(1),
FEMALE NUMBER(3),
INFANT NUMBER(2) NOT NULL,
MALE NUMBER(3) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
SUBCLASS VARCHAR2(1)
);
