CREATE TABLE TTS (
BODY_TYPE NUMBER(1),
CATEGORY NUMBER(1),
CLOSE NUMBER(1) DEFAULT 0,
IDA NUMBER(4),
LCODEGROUP VARCHAR2(3),
LCODET VARCHAR2(3),
LNAME VARCHAR2(42),
MAXSEATS NUMBER(4),
MINSEATS NUMBER(3),
RCODEGROUP VARCHAR2(3),
RCODET VARCHAR2(3),
RNAME VARCHAR2(42),
VERSION NUMBER
);
