CREATE TABLE TYPEB_OPTION_VALUES (
CATEGORY VARCHAR2(20) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
SHORT_NAME VARCHAR2(20) NOT NULL,
SHORT_NAME_LAT VARCHAR2(20),
TLG_TYPE VARCHAR2(6) NOT NULL,
VALUE VARCHAR2(10) NOT NULL
);
