CREATE TABLE TYPEB_TYPES (
BASIC_TYPE VARCHAR2(3) NOT NULL,
CODE VARCHAR2(6) NOT NULL,
EDITABLE NUMBER(1) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PR_DEP NUMBER(1),
SHORT_NAME VARCHAR2(20) NOT NULL,
SHORT_NAME_LAT VARCHAR2(20)
);
