CREATE TABLE USERS2 (
DESCR VARCHAR2(20) NOT NULL,
DESK VARCHAR2(6),
LOGIN VARCHAR2(20),
PASSWD VARCHAR2(20),
PR_DENIAL NUMBER(1) DEFAULT 0 NOT NULL,
TYPE NUMBER(1) NOT NULL,
USER_ID NUMBER(9) NOT NULL
);
