CREATE TABLE VOUCHER_STAT (
DESK VARCHAR2(6) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(64),
PAX_ID NUMBER(9),
POINT_ID NUMBER(9) NOT NULL,
SCD_OUT DATE NOT NULL,
SURNAME VARCHAR2(64) NOT NULL,
TIME_PRINT DATE NOT NULL,
VOUCHER VARCHAR2(2) NOT NULL
);
