CREATE TABLE WC_COUPON (
NUM NUMBER(1) NOT NULL,
OWNER_AIRLINE NUMBER(9) NOT NULL,
RECLOC VARCHAR2(6) NOT NULL,
STATUS NUMBER(2) NOT NULL,
TICKNUM VARCHAR2(13) NOT NULL
);
ALTER TABLE WC_COUPON ADD CONSTRAINT WC_COUPON_PK PRIMARY KEY(OWNER_AIRLINE, TICKNUM, NUM);
