CREATE OR REPLACE FUNCTION COMP_ELEMS__BEFORE__TRG_FN() RETURNS TRIGGER AS $$
BEGIN
  NEW.xname:=COALESCE(salons.normalize_xname(NEW.xname),TRIM(UPPER(NEW.xname)));
  NEW.yname:=COALESCE(salons.normalize_yname(NEW.yname),TRIM(UPPER(NEW.yname)));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS COMP_ELEMS__BEFORE__TRG ON COMP_ELEMS;
CREATE TRIGGER COMP_ELEMS__BEFORE__TRG
BEFORE
INSERT OR UPDATE
ON COMP_ELEMS
FOR EACH ROW
EXECUTE PROCEDURE COMP_ELEMS__BEFORE__TRG_FN();
