CREATE OR REPLACE FUNCTION MAGIC_NULL_DATE_REPLACE() RETURNS TRIGGER AS $$
BEGIN
  NEW.time_in := date_trunc('day', COALESCE(NEW.act_in,COALESCE(NEW.est_in, NEW.scd_in)));
  NEW.time_out := date_trunc('day', COALESCE(NEW.act_out,COALESCE(NEW.est_out, NEW.scd_out)));
  IF (NEW.time_in IS NULL AND NEW.time_out IS NULL) THEN
    NEW.time_in := TO_DATE('01.01.1900','DD.MM.YYYY');
    NEW.time_out := TO_DATE('01.01.1900','DD.MM.YYYY');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER POINTS__TIME_IN_OUT__TRG
BEFORE
INSERT OR UPDATE
ON POINTS
FOR EACH ROW
EXECUTE FUNCTION MAGIC_NULL_DATE_REPLACE();
