#!/bin/bash
set -euo pipefail
rm -f ok

proc_file() {
    # set -euo pipefail
    echo "running $@"
    [[ ${QUIET:-0} == 1 ]] && silent="-S" || silent=
    { echo whenever sqlerror exit 3\;; cat $1; } | sqlplus $silent $2
}
# export -f proc_file

function rundir {
for f in `ls *.sql` ; do
    rm -f log
    proc_file $f $1 2>&1 | tee -a log
    if grep "[A-Z0-9]\+-[0-9]\+" log > /dev/null ; then
        echo "error in $f"
        exit 1
    fi
done
}

rundir $1
if [ -d ets ] ; then (cd ets && rundir $1) ; fi
