create or replace trigger TRG_WB_REF_WS_AIR_EQUIP_AD_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_EQUIP_ADV
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_EQUIP_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  PWL_BALANCE_ARM,
	                                                                    PWL_INDEX_UNIT,
	                                                                      GOL_BALANCE_ARM,
	                                                                        GOL_INDEX_UNIT,	
		                                                                      U_NAME,
		                                                                        U_IP,
		                                                                          U_HOST_NAME,
		                                                                            DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_EQUIP_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.PWL_BALANCE_ARM,
	                                   :new.PWL_INDEX_UNIT,
	                                     :new.GOL_BALANCE_ARM,
	                                       :new.GOL_INDEX_UNIT,	
		                         	          :new.U_NAME,
		                               	         :new.U_IP,
		                                	       :new.U_HOST_NAME,
		                                 	         :new.DATE_WRITE,
                                                       :new.DATE_FROM
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_EQUIP_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  PWL_BALANCE_ARM,
	                                                                    PWL_INDEX_UNIT,
	                                                                      GOL_BALANCE_ARM,
	                                                                        GOL_INDEX_UNIT,	
		                                                                      U_NAME,
		                                                                        U_IP,
		                                                                          U_HOST_NAME,
		                                                                            DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_EQUIP_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
		                             :old.IDN,
	                                 :old.PWL_BALANCE_ARM,
	                                   :old.PWL_INDEX_UNIT,
	                                     :old.GOL_BALANCE_ARM,
	                                       :old.GOL_INDEX_UNIT,	
		                         	         :old.U_NAME,
		                               	       :old.U_IP,
		                                	     :old.U_HOST_NAME,
		                                 	       :old.DATE_WRITE,
                                                     :old.DATE_FROM
    from dual;

    insert into WB_REF_WS_AIR_EQUIP_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  PWL_BALANCE_ARM,
	                                                                    PWL_INDEX_UNIT,
	                                                                      GOL_BALANCE_ARM,
	                                                                        GOL_INDEX_UNIT,	
		                                                                      U_NAME,
		                                                                        U_IP,
		                                                                          U_HOST_NAME,
		                                                                            DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_EQUIP_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.PWL_BALANCE_ARM,
	                                   :new.PWL_INDEX_UNIT,
	                                     :new.GOL_BALANCE_ARM,
	                                       :new.GOL_INDEX_UNIT,	
		                         	         :new.U_NAME,
		                               	       :new.U_IP,
		                                	     :new.U_HOST_NAME,
		                                 	       :new.DATE_WRITE,
                                                     :new.DATE_FROM
    from dual;
  end if;
END;
/
