create or replace trigger TRG_WB_REF_AC_PRT_FLIGHT_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_AIRCO_PORT_FLIGHT
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_AIRCO_PORT_FLIGHT_HIST (ID_,
	                                               U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION_,
	                                                         ID,
	                                                           ID_AC_OLD,
	                                                             ID_PORT_OLD,
	 	                                                             DATE_FROM_OLD,
	 	                                                               UTC_DIFF_OLD,
	 	                                                                 IS_CHECK_IN_OLD,
	 	                                                                   IS_LOAD_CONTROL_OLD,
	 	                                                                     U_NAME_OLD,
	 	                                                                       U_IP_OLD,
		                                                                         U_HOST_NAME_OLD,
		                                                                           DATE_WRITE_OLD,
		                                                                             ID_AC_NEW,
		                                                                               ID_PORT_NEW,
		                                                                                 DATE_FROM_NEW,
		                                                                                   UTC_DIFF_NEW,
		                                                                                     IS_CHECK_IN_NEW,
		                                                                                       IS_LOAD_CONTROL_NEW,
		                                                                                         U_NAME_NEW,
		                                                                                           U_IP_NEW,
		                                                                                             U_HOST_NAME_NEW,
		                                                                                               DATE_WRITE_NEW)
    select SEC_WB_REF_AC_PORT_FLIGHT_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       :new.id,
                         :new.ID_AC,
	                         :new.ID_PORT,
	                           :new.DATE_FROM,
	                             :new.UTC_DIFF,
	                               :new.IS_CHECK_IN,
	                                 :new.IS_LOAD_CONTROL,
	                                   :new.U_NAME,
	                                     :new.U_IP,
	                                       :new.U_HOST_NAME,
	                                         :new.DATE_WRITE,
                                             :new.ID_AC,
	                                             :new.ID_PORT,
	                                               :new.DATE_FROM,
	                                                 :new.UTC_DIFF,
	                                                   :new.IS_CHECK_IN,
	                                                     :new.IS_LOAD_CONTROL,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_AIRCO_PORT_FLIGHT_HIST (ID_,
	                                               U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION_,
	                                                         ID,
	                                                           ID_AC_OLD,
	                                                             ID_PORT_OLD,
	 	                                                             DATE_FROM_OLD,
	 	                                                               UTC_DIFF_OLD,
	 	                                                                 IS_CHECK_IN_OLD,
	 	                                                                   IS_LOAD_CONTROL_OLD,
	 	                                                                     U_NAME_OLD,
	 	                                                                       U_IP_OLD,
		                                                                         U_HOST_NAME_OLD,
		                                                                           DATE_WRITE_OLD,
		                                                                             ID_AC_NEW,
		                                                                               ID_PORT_NEW,
		                                                                                 DATE_FROM_NEW,
		                                                                                   UTC_DIFF_NEW,
		                                                                                     IS_CHECK_IN_NEW,
		                                                                                       IS_LOAD_CONTROL_NEW,
		                                                                                         U_NAME_NEW,
		                                                                                           U_IP_NEW,
		                                                                                             U_HOST_NAME_NEW,
		                                                                                               DATE_WRITE_NEW)
    select SEC_WB_REF_AC_PORT_FLIGHT_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       :old.id,
                         :old.ID_AC,
	                         :old.ID_PORT,
	                           :old.DATE_FROM,
	                             :old.UTC_DIFF,
	                               :old.IS_CHECK_IN,
	                                 :old.IS_LOAD_CONTROL,
	                                   :old.U_NAME,
	                                     :old.U_IP,
	                                       :old.U_HOST_NAME,
	                                         :old.DATE_WRITE,
                                             :new.ID_AC,
	                                             :new.ID_PORT,
	                                               :new.DATE_FROM,
	                                                 :new.UTC_DIFF,
	                                                   :new.IS_CHECK_IN,
	                                                     :new.IS_LOAD_CONTROL,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;
END;
/
