create or replace trigger TRG_WB_REF_WS_AIR_SEC_BAY_T_HS
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_SEC_BAY_T
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_SEC_BAY_T_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  CMP_NAME,
	                                                                  SEC_BAY_NAME,
	                                                                    SEC_BAY_TYPE_ID,
	                                                                      MAX_WEIGHT,
	                                                                        MAX_VOLUME,
	                                                                          LA_CENTROID,
	                                                                            LA_FROM,
	                                                                              LA_TO,
	                                                                                BA_CENTROID,
	                                                                                  BA_FWD,
	                                                                                    BA_AFT,
	                                                                                      INDEX_PER_WT_UNIT,
	                                                                                        DOOR_POSITION,
	                                                                                          U_NAME,
		                                                                                          U_IP,
		                                                                                            U_HOST_NAME,
		                                                                                              DATE_WRITE,
                                                                                                    COLOR)
    select SEC_WB_REF_WS_AIR_SEC_BAY_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.CMP_NAME,
	                                 :new.SEC_BAY_NAME,
	                                   :new.SEC_BAY_TYPE_ID,
	                                     :new.MAX_WEIGHT,
	                                       :new.MAX_VOLUME,
	                                         :new.LA_CENTROID,
	                                           :new.LA_FROM,
	                                             :new.LA_TO,
	                                               :new.BA_CENTROID,
	                                                 :new.BA_FWD,
	                                                   :new.BA_AFT,
	                                                     :new.INDEX_PER_WT_UNIT,
	                                                       :new.DOOR_POSITION,
	                                                         :new.U_NAME,
		                               	                         :new.U_IP,
		                                	                         :new.U_HOST_NAME,
		                                 	                           :new.DATE_WRITE,
                                                                   :new.COLOR
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_SEC_BAY_T_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  CMP_NAME,
	                                                                  SEC_BAY_NAME,
	                                                                    SEC_BAY_TYPE_ID,
	                                                                      MAX_WEIGHT,
	                                                                        MAX_VOLUME,
	                                                                          LA_CENTROID,
	                                                                            LA_FROM,
	                                                                              LA_TO,
	                                                                                BA_CENTROID,
	                                                                                  BA_FWD,
	                                                                                    BA_AFT,
	                                                                                      INDEX_PER_WT_UNIT,
	                                                                                        DOOR_POSITION,
	                                                                                          U_NAME,
		                                                                                          U_IP,
		                                                                                            U_HOST_NAME,
		                                                                                              DATE_WRITE,
                                                                                                    COLOR)
    select SEC_WB_REF_WS_AIR_SEC_BAY_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,		
	                               :old.CMP_NAME,
	                                 :old.SEC_BAY_NAME,
	                                   :old.SEC_BAY_TYPE_ID,
	                                     :old.MAX_WEIGHT,
	                                       :old.MAX_VOLUME,
	                                         :old.LA_CENTROID,
	                                           :old.LA_FROM,
	                                             :old.LA_TO,
	                                               :old.BA_CENTROID,
	                                                 :old.BA_FWD,
	                                                   :old.BA_AFT,
	                                                     :old.INDEX_PER_WT_UNIT,
	                                                       :old.DOOR_POSITION,
	                                                         :old.U_NAME,
		                               	                         :old.U_IP,
		                                	                         :old.U_HOST_NAME,
		                                 	                           :old.DATE_WRITE,
                                                                   :old.COLOR
    from dual;

    insert into WB_REF_WS_AIR_SEC_BAY_T_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  CMP_NAME,
	                                                                  SEC_BAY_NAME,
	                                                                    SEC_BAY_TYPE_ID,
	                                                                      MAX_WEIGHT,
	                                                                        MAX_VOLUME,
	                                                                          LA_CENTROID,
	                                                                            LA_FROM,
	                                                                              LA_TO,
	                                                                                BA_CENTROID,
	                                                                                  BA_FWD,
	                                                                                    BA_AFT,
	                                                                                      INDEX_PER_WT_UNIT,
	                                                                                        DOOR_POSITION,
	                                                                                          U_NAME,
		                                                                                          U_IP,
		                                                                                            U_HOST_NAME,
		                                                                                              DATE_WRITE,
                                                                                                    COLOR)
    select SEC_WB_REF_WS_AIR_SEC_BAY_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.CMP_NAME,
	                                 :new.SEC_BAY_NAME,
	                                   :new.SEC_BAY_TYPE_ID,
	                                     :new.MAX_WEIGHT,
	                                       :new.MAX_VOLUME,
	                                         :new.LA_CENTROID,
	                                           :new.LA_FROM,
	                                             :new.LA_TO,
	                                               :new.BA_CENTROID,
	                                                 :new.BA_FWD,
	                                                   :new.BA_AFT,
	                                                     :new.INDEX_PER_WT_UNIT,
	                                                       :new.DOOR_POSITION,
	                                                         :new.U_NAME,
		                               	                         :new.U_IP,
		                                	                         :new.U_HOST_NAME,
		                                 	                           :new.DATE_WRITE,
                                                                   :new.COLOR
    from dual;
  end if;
END;
/
