create or replace trigger TRG_WB_REF_WS_AIR_GR_CH_USE_H
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_GR_CH_USE
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_GR_CH_USE_H (ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             ID_CH,
	                                                                 USE_ITEM_ID,
	                                                                   OPER_ID_1,
	                                                                     VALUE_1,
	                                                                       OPER_ID_2,
	                                                                         VALUE_2,
	                                                                           U_NAME,
	                                                                             U_IP,
	                                                                               U_HOST_NAME,
	                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_USE_H.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.ID_CH,
	                                 :new.USE_ITEM_ID,
	                                   :new.OPER_ID_1,
	                                     :new.VALUE_1,
	                                       :new.OPER_ID_2,
	                                         :new.VALUE_2,
	                                           :new.U_NAME,
		                               	           :new.U_IP,
		                                	           :new.U_HOST_NAME,
		                                 	             :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_GR_CH_USE_H (ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             ID_CH,
	                                                                 USE_ITEM_ID,
	                                                                   OPER_ID_1,
	                                                                     VALUE_1,
	                                                                       OPER_ID_2,
	                                                                         VALUE_2,
	                                                                           U_NAME,
	                                                                             U_IP,
	                                                                               U_HOST_NAME,
	                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_USE_H.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
		                             :old.ID_CH,
	                                 :old.USE_ITEM_ID,
	                                   :old.OPER_ID_1,
	                                     :old.VALUE_1,
	                                       :old.OPER_ID_2,
	                                         :old.VALUE_2,
	                                           :old.U_NAME,
		                               	           :old.U_IP,
		                                	           :old.U_HOST_NAME,
		                                 	             :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_GR_CH_USE_H (ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             ID_CH,
	                                                                 USE_ITEM_ID,
	                                                                   OPER_ID_1,
	                                                                     VALUE_1,
	                                                                       OPER_ID_2,
	                                                                         VALUE_2,
	                                                                           U_NAME,
	                                                                             U_IP,
	                                                                               U_HOST_NAME,
	                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_USE_H.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.ID_CH,
	                                 :new.USE_ITEM_ID,
	                                   :new.OPER_ID_1,
	                                     :new.VALUE_1,
	                                       :new.OPER_ID_2,
	                                         :new.VALUE_2,
	                                           :new.U_NAME,
		                               	           :new.U_IP,
		                                	           :new.U_HOST_NAME,
		                                 	             :new.DATE_WRITE
    from dual;
  end if;
END;
/
