create or replace trigger TRG_WB_REF_WS_AIR_MN_WGT_ID_HS
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_MIN_WGHT_IDN
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_MIN_WGHT_IDN_HS(ID_,
	                                              U_NAME_,
	                                                U_IP_,
	                                                  U_HOST_NAME_,
	                                                    DATE_WRITE_,
                                                        OPERATION_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC,
	                                                              ID_WS,
		                                                              ID_BORT,
                                                                    TABLE_NAME,
	                                                                    CONDITION,
	                                                                      TYPE,
	                                                                        TYPE_FROM,
	                                                                          TYPE_TO,
	                                                                            U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE)
    select SEC_WB_REF_WS_AIR_MIN_W_IDN_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
	                               :new.TABLE_NAME,
	                                 :new.CONDITION,
	                                   :new.TYPE,
	                                     :new.TYPE_FROM,
	                                       :new.TYPE_TO,
	                                         :new.U_NAME,
		                               	         :new.U_IP,
		                                	         :new.U_HOST_NAME,
		                                 	           :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_MIN_WGHT_IDN_HS(ID_,
	                                              U_NAME_,
	                                                U_IP_,
	                                                  U_HOST_NAME_,
	                                                    DATE_WRITE_,
                                                        OPERATION_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC,
	                                                              ID_WS,
		                                                              ID_BORT,
                                                                    TABLE_NAME,
	                                                                    CONDITION,
	                                                                      TYPE,
	                                                                        TYPE_FROM,
	                                                                          TYPE_TO,
	                                                                            U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE)
    select SEC_WB_REF_WS_AIR_MIN_W_IDN_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,		
	                               :old.TABLE_NAME,
	                                 :old.CONDITION,
	                                   :old.TYPE,
	                                     :old.TYPE_FROM,
	                                       :old.TYPE_TO,
	                                         :old.U_NAME,
		                               	         :old.U_IP,
		                                	         :old.U_HOST_NAME,
		                                 	           :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_MIN_WGHT_IDN_HS(ID_,
	                                              U_NAME_,
	                                                U_IP_,
	                                                  U_HOST_NAME_,
	                                                    DATE_WRITE_,
                                                        OPERATION_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC,
	                                                              ID_WS,
		                                                              ID_BORT,
                                                                    TABLE_NAME,
	                                                                    CONDITION,
	                                                                      TYPE,
	                                                                        TYPE_FROM,
	                                                                          TYPE_TO,
	                                                                            U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE)
    select SEC_WB_REF_WS_AIR_MIN_W_IDN_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.TABLE_NAME,
	                                 :new.CONDITION,
	                                   :new.TYPE,
	                                     :new.TYPE_FROM,
	                                       :new.TYPE_TO,
	                                         :new.U_NAME,
		                                    	   :new.U_IP,
		                                	         :new.U_HOST_NAME,
		                                 	           :new.DATE_WRITE
    from dual;
  end if;
END;
/
