create or replace trigger TRG_WB_REF_WS_AIR_SL_CI_T_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_SL_CI_T
FOR EACH ROW
BEGIN null;
  if inserting then
    insert into WB_REF_WS_AIR_SL_CI_T_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
                                                                    CLASS_CODE,
	                                                                    FIRST_ROW,
	                                                                      LAST_ROW,
	                                                                        NUM_OF_SEATS,
	                                                                          LA_FROM,
	                                                                            LA_TO,	
	                                                                              BA_CENTROID,
	                                                                                BA_FWD,
	                                                                                  BA_AFT,
	                                                                                    INDEX_PER_WT_UNIT,
		                                                                                    U_NAME,
		                                                                                      U_IP,
		                                                                                        U_HOST_NAME,
		                                                                                          DATE_WRITE)
    select SEC_WB_REF_WS_AIR_SL_CI_T_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
                                 :new.IDN,
                                   :new.ADV_ID,
	                                   :new.CLASS_CODE,
                                       :new.FIRST_ROW,
	                                       :new.LAST_ROW,
	                                         :new.NUM_OF_SEATS,
	                                           :new.LA_FROM,
	                                             :new.LA_TO,
                                                 :new.BA_CENTROID,
	                                                 :new.BA_FWD,
	                                                   :new.BA_AFT,	
	                                                     :new.INDEX_PER_WT_UNIT,
		                                                     :new.U_NAME,
		                                                       :new.U_IP,
		                                                         :new.U_HOST_NAME,
		                                                           :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_SL_CI_T_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
                                                                    CLASS_CODE,
	                                                                    FIRST_ROW,
	                                                                      LAST_ROW,
	                                                                        NUM_OF_SEATS,
	                                                                          LA_FROM,
	                                                                            LA_TO,	
	                                                                              BA_CENTROID,
	                                                                                BA_FWD,
	                                                                                  BA_AFT,
	                                                                                    INDEX_PER_WT_UNIT,
		                                                                                    U_NAME,
		                                                                                      U_IP,
		                                                                                        U_HOST_NAME,
		                                                                                          DATE_WRITE)
    select SEC_WB_REF_WS_AIR_SL_CI_T_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
                                 :old.IDN,
	                                 :old.ADV_ID,
	                                   :old.CLASS_CODE,
                                       :old.FIRST_ROW,
	                                       :old.LAST_ROW,
	                                         :old.NUM_OF_SEATS,
	                                           :old.LA_FROM,
	                                             :old.LA_TO,
                                                 :old.BA_CENTROID,
        	                                         :old.BA_FWD,
	                                                   :old.BA_AFT,	
	                                                     :old.INDEX_PER_WT_UNIT,
		                                                     :old.U_NAME,
		                                                       :old.U_IP,
		                                                         :old.U_HOST_NAME,
		                                                           :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_SL_CI_T_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
                                                                    CLASS_CODE,
	                                                                    FIRST_ROW,
	                                                                      LAST_ROW,
	                                                                        NUM_OF_SEATS,
	                                                                          LA_FROM,
	                                                                            LA_TO,	
	                                                                              BA_CENTROID,
	                                                                                BA_FWD,
	                                                                                  BA_AFT,
	                                                                                    INDEX_PER_WT_UNIT,
		                                                                                    U_NAME,
		                                                                                      U_IP,
		                                                                                        U_HOST_NAME,
		                                                                                          DATE_WRITE)
    select SEC_WB_REF_WS_AIR_SL_CI_T_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
                                 :new.IDN,
	                                 :new.ADV_ID,
	                                   :new.CLASS_CODE,
                                       :new.FIRST_ROW,
	                                       :new.LAST_ROW,
	                                         :new.NUM_OF_SEATS,
	                                           :new.LA_FROM,
	                                             :new.LA_TO,
                                                 :new.BA_CENTROID,
	                                                 :new.BA_FWD,
	                                                   :new.BA_AFT,	
	                                                     :new.INDEX_PER_WT_UNIT,
		                                                     :new.U_NAME,
		                                                       :new.U_IP,
		                                                         :new.U_HOST_NAME,
		                                                           :new.DATE_WRITE
    from dual;
  end if;
END;
/
