create or replace trigger TRG_WB_REF_AIRCO_ULD_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_AIRCO_ULD
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_AIRCO_ULD_HIST(ID_,
	                                      U_NAME_,
	                                        U_IP_,
	                                          U_HOST_NAME_,
	                                            DATE_WRITE_,
                                                OPERATION_,
	                                                ACTION_,
	                                                  ID,
	                                                    ID_AC,	
	                                                      ULD_TYPE_ID,
	                                                        ULD_ATA_ID,
	                                                          ULD_IATA_ID,
	                                                            BEG_SER_NUM,
	                                                              END_SER_NUM,
	                                                                OWNER_CODE,
	                                                                  TARE_WEIGHT,
	                                                                    MAX_WEIGHT,
	                                                                      MAX_VOLUME,
	                                                                        WIDTH,
	                                                                          LENGTH,
	                                                                            HEIGHT,
	                                                                              BY_DEFAULT,
	                                                                                U_NAME,
		                                                                                U_IP,
		                                                                                  U_HOST_NAME,
		                                                                                    DATE_WRITE)
    select SEC_WB_REF_AIRCO_ULD_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.id_ac,
	                           :new.ULD_TYPE_ID,
	                             :new.ULD_ATA_ID,
	                               :new.ULD_IATA_ID,
	                                 :new.BEG_SER_NUM,
	                                   :new.END_SER_NUM,
	                                     :new.OWNER_CODE,
	                                       :new.TARE_WEIGHT,
	                                         :new.MAX_WEIGHT,
	                                           :new.MAX_VOLUME,
	                                             :new.WIDTH,
	                                               :new.LENGTH,
	                                                 :new.HEIGHT,
	                                                   :new.BY_DEFAULT,
	                                                     :new.U_NAME,
		                                                     :new.U_IP,
		                                                       :new.U_HOST_NAME,
		                                                         :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_AIRCO_ULD_HIST(ID_,
	                                      U_NAME_,
	                                        U_IP_,
	                                          U_HOST_NAME_,
	                                            DATE_WRITE_,
                                                OPERATION_,
	                                                ACTION_,
	                                                  ID,
	                                                    ID_AC,	
	                                                      ULD_TYPE_ID,
	                                                        ULD_ATA_ID,
	                                                          ULD_IATA_ID,
	                                                            BEG_SER_NUM,
	                                                              END_SER_NUM,
	                                                                OWNER_CODE,
	                                                                  TARE_WEIGHT,
	                                                                    MAX_WEIGHT,
	                                                                      MAX_VOLUME,
	                                                                        WIDTH,
	                                                                          LENGTH,
	                                                                            HEIGHT,
	                                                                              BY_DEFAULT,
	                                                                                U_NAME,
		                                                                                U_IP,
		                                                                                  U_HOST_NAME,
		                                                                                    DATE_WRITE)
    select SEC_WB_REF_AIRCO_ULD_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.id_ac,
	                           :old.ULD_TYPE_ID,
	                             :old.ULD_ATA_ID,
	                               :old.ULD_IATA_ID,
	                                 :old.BEG_SER_NUM,
	                                   :old.END_SER_NUM,
	                                     :old.OWNER_CODE,
	                                       :old.TARE_WEIGHT,
	                                         :old.MAX_WEIGHT,
	                                           :old.MAX_VOLUME,
	                                             :old.WIDTH,
	                                               :old.LENGTH,
	                                                 :old.HEIGHT,
	                                                   :old.BY_DEFAULT,
	                                                     :old.U_NAME,
		                                                     :old.U_IP,
		                                                       :old.U_HOST_NAME,
		                                                         :old.DATE_WRITE
    from dual;

    insert into WB_REF_AIRCO_ULD_HIST(ID_,
	                                      U_NAME_,
	                                        U_IP_,
	                                          U_HOST_NAME_,
	                                            DATE_WRITE_,
                                                OPERATION_,
	                                                ACTION_,
	                                                  ID,
	                                                    ID_AC,	
	                                                      ULD_TYPE_ID,
	                                                        ULD_ATA_ID,
	                                                          ULD_IATA_ID,
	                                                            BEG_SER_NUM,
	                                                              END_SER_NUM,
	                                                                OWNER_CODE,
	                                                                  TARE_WEIGHT,
	                                                                    MAX_WEIGHT,
	                                                                      MAX_VOLUME,
	                                                                        WIDTH,
	                                                                          LENGTH,
	                                                                            HEIGHT,
	                                                                              BY_DEFAULT,
	                                                                                U_NAME,
		                                                                                U_IP,
		                                                                                  U_HOST_NAME,
		                                                                                    DATE_WRITE)
   select SEC_WB_REF_AIRCO_ULD_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.id_ac,
	                           :new.ULD_TYPE_ID,
	                             :new.ULD_ATA_ID,
	                               :new.ULD_IATA_ID,
	                                 :new.BEG_SER_NUM,
	                                   :new.END_SER_NUM,
	                                     :new.OWNER_CODE,
	                                       :new.TARE_WEIGHT,
	                                         :new.MAX_WEIGHT,
	                                           :new.MAX_VOLUME,
	                                             :new.WIDTH,
	                                               :new.LENGTH,
	                                                 :new.HEIGHT,
	                                                   :new.BY_DEFAULT,
	                                                     :new.U_NAME,
		                                                     :new.U_IP,
		                                                       :new.U_HOST_NAME,
		                                                         :new.DATE_WRITE
    from dual;
  end if;
END;
/
