create or replace trigger TRG_WB_REF_WS_AIR_CABIN_AD_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_CABIN_ADV
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_CABIN_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CD_BALANCE_ARM,
	                                                                    CD_INDEX_UNIT,
	                                                                      FDL_BALANCE_ARM,
	                                                                        FDL_INDEX_UNIT,
	                                                                          CCL_BALANCE_ARM,
	                                                                            CCL_INDEX_UNIT,
		                                                                          U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_CABIN_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.CD_BALANCE_ARM,
	                                   :new.CD_INDEX_UNIT,
	                                     :new.FDL_BALANCE_ARM,
	                                       :new.FDL_INDEX_UNIT,
	                                         :new.CCL_BALANCE_ARM,
	                                           :new.CCL_INDEX_UNIT,
		                         	                 :new.U_NAME,
		                               	             :new.U_IP,
		                                	             :new.U_HOST_NAME,
		                                 	               :new.DATE_WRITE,
                                                       :new.DATE_FROM
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_CABIN_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CD_BALANCE_ARM,
	                                                                    CD_INDEX_UNIT,
	                                                                      FDL_BALANCE_ARM,
	                                                                        FDL_INDEX_UNIT,
	                                                                          CCL_BALANCE_ARM,
	                                                                            CCL_INDEX_UNIT,
		                                                                          U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_CABIN_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
		                             :old.IDN,
	                                 :old.CD_BALANCE_ARM,
	                                   :old.CD_INDEX_UNIT,
	                                     :old.FDL_BALANCE_ARM,
	                                       :old.FDL_INDEX_UNIT,
	                                         :old.CCL_BALANCE_ARM,
	                                           :old.CCL_INDEX_UNIT,
		                         	                 :old.U_NAME,
		                               	             :old.U_IP,
		                                	             :old.U_HOST_NAME,
		                                 	               :old.DATE_WRITE,
                                                       :old.DATE_FROM
    from dual;

    insert into WB_REF_WS_AIR_CABIN_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CD_BALANCE_ARM,
	                                                                    CD_INDEX_UNIT,
	                                                                      FDL_BALANCE_ARM,
	                                                                        FDL_INDEX_UNIT,
	                                                                          CCL_BALANCE_ARM,
	                                                                            CCL_INDEX_UNIT,
		                                                                          U_NAME,
		                                                                            U_IP,
		                                                                              U_HOST_NAME,
		                                                                                DATE_WRITE,
                                                                                      DATE_FROM)
    select SEC_WB_REF_WS_AIR_CABIN_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.CD_BALANCE_ARM,
	                                   :new.CD_INDEX_UNIT,
	                                     :new.FDL_BALANCE_ARM,
	                                       :new.FDL_INDEX_UNIT,
	                                         :new.CCL_BALANCE_ARM,
	                                           :new.CCL_INDEX_UNIT,
		                         	                 :new.U_NAME,
		                               	             :new.U_IP,
		                                	             :new.U_HOST_NAME,
		                                 	               :new.DATE_WRITE,
                                                       :new.DATE_FROM
    from dual;
  end if;
END;
/
