create or replace trigger TRG_WB_REF_WS_AIR_SP_IN_DT_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_SUPPL_INFO_DATA
FOR EACH ROW
BEGIN null;
  if inserting then
    insert into WB_REF_WS_AIR_SUP_INF_DATA_HST (ID_,
	                                                U_NAME_,
	                                                  U_IP_,
	                                                    U_HOST_NAME_,
	                                                      DATE_WRITE_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC_OLD,
	                                                              ID_WS_OLD,
		                                                              ID_BORT_OLD,
		                                                                DATE_FROM_OLD,
		                                                                  ITEM_ID_OLD,
	                                                                      DET_COL_ID_OLD,
	                                                                        IS_CHECK_OLD,
                                                                            REMARK_OLD,
		                                                                          U_NAME_OLD,
		                                                                            U_IP_OLD,
		                                                                              U_HOST_NAME_OLD,
		                                                                                DATE_WRITE_OLD,
		                                                                                  ID_AC_NEW,
		                                                                                    ID_WS_NEW,
		                                                                                      ID_BORT_NEW,
		                                                                                        DATE_FROM_NEW,
		                                                                                          ITEM_ID_NEW,
	                                                                                              DET_COL_ID_NEW,
	                                                                                                IS_CHECK_NEW,
		                                                                                                REMARK_NEW,
		                                                                                                  U_NAME_NEW,
		                                                                                                    U_IP_NEW,
		                                                                                                      U_HOST_NAME_NEW,
		                                                                                                        DATE_WRITE_NEW,
                                                                                                              ADV_ID_OLD,
                                                                                                                ADV_ID_NEW)
    select SEC_WB_REF_WS_AIR_SUP_DATA_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       :new.id,
                         :new.ID_AC,
	                         :new.ID_WS,
		                         :new.ID_BORT,
		                           :new.DATE_FROM,
		                             :new.ITEM_ID,
	                                 :new.DET_COL_ID,
	                                   :new.IS_CHECK,
		                                   :new.REMARK,
		                                     :new.U_NAME,
		                                       :new.U_IP,
		                                         :new.U_HOST_NAME,
		                                           :new.DATE_WRITE,
		                                             :new.ID_AC,
		                                               :new.ID_WS,
		                                                 :new.ID_BORT,
		                                                   :new.DATE_FROM,
		                                                     :new.ITEM_ID,
	                                                         :new.DET_COL_ID,
	                                                           :new.IS_CHECK,
		                                                           :new.REMARK,
		                                                             :new.U_NAME,
		                                                               :new.U_IP,
		                                                                 :new.U_HOST_NAME,
		                                                                   :new.DATE_WRITE,
                                                                         :new.adv_id,
                                                                           :new.adv_id
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_SUP_INF_DATA_HST (ID_,
	                                                U_NAME_,
	                                                  U_IP_,
	                                                    U_HOST_NAME_,
	                                                      DATE_WRITE_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC_OLD,
	                                                              ID_WS_OLD,
		                                                              ID_BORT_OLD,
		                                                                DATE_FROM_OLD,
		                                                                  ITEM_ID_OLD,
	                                                                      DET_COL_ID_OLD,
	                                                                        IS_CHECK_OLD,
                                                                            REMARK_OLD,
		                                                                          U_NAME_OLD,
		                                                                            U_IP_OLD,
		                                                                              U_HOST_NAME_OLD,
		                                                                                DATE_WRITE_OLD,
		                                                                                  ID_AC_NEW,
		                                                                                    ID_WS_NEW,
		                                                                                      ID_BORT_NEW,
		                                                                                        DATE_FROM_NEW,
		                                                                                          ITEM_ID_NEW,
	                                                                                              DET_COL_ID_NEW,
	                                                                                                IS_CHECK_NEW,
		                                                                                                REMARK_NEW,
		                                                                                                  U_NAME_NEW,
		                                                                                                    U_IP_NEW,
		                                                                                                      U_HOST_NAME_NEW,
		                                                                                                        DATE_WRITE_NEW,
                                                                                                              ADV_ID_OLD,
                                                                                                                ADV_ID_NEW)
    select SEC_WB_REF_WS_AIR_SUP_DATA_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       :old.id,
                         :old.ID_AC,
	                         :old.ID_WS,
		                         :old.ID_BORT,
		                           :old.DATE_FROM,
		                             :old.ITEM_ID,
	                                 :old.DET_COL_ID,
	                                   :old.IS_CHECK,
		                                   :old.REMARK,
		                                     :old.U_NAME,
		                                       :old.U_IP,
		                                         :old.U_HOST_NAME,
		                                           :old.DATE_WRITE,
		                                             :new.ID_AC,
		                                               :new.ID_WS,
		                                                 :new.ID_BORT,
		                                                   :new.DATE_FROM,
		                                                     :new.ITEM_ID,
	                                                         :new.DET_COL_ID,
	                                                           :new.IS_CHECK,
		                                                           :new.REMARK,
		                                                             :new.U_NAME,
		                                                               :new.U_IP,
		                                                                 :new.U_HOST_NAME,
		                                                                   :new.DATE_WRITE,
                                                                         :old.adv_id,
                                                                           :new.adv_id
    from dual;
  end if;
END;
/
