create or replace trigger TRG_WB_REF_AIRCO_C_DATA_1_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_AIRCO_C_DATA_1
FOR EACH ROW
BEGIN

  if inserting then
    insert into WB_REF_AIRCO_C_DATA_1_HISTORY (ID_,
                                                 U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION,
	                                                         ID,
	                                                           ID_AC_OLD,
	                                                             DATE_FROM_OLD,
                                                                 H_ADRESS_OLD,
	                                                                 C_PERSONE_OLD,
	                                                                   E_MAIL_ADRESS_OLD,
	                                                                     TELETYPE_ADRESS_OLD,
	                                                                       PHONE_NUMBER_OLD,
	                                                                       	 FAX_NUMBER_OLD,
		                                                                         REMARK_OLD,
		                                                                           U_NAME_OLD,
		                                                                             U_IP_OLD,
		                                                                               U_HOST_NAME_OLD,
		                                                                                 DATE_WRITE_OLD,
		                                                                                   ID_AC_NEW,
	                                                                                   	   DATE_FROM_NEW,
	                                                                     	                   H_ADRESS_NEW,
	                                                                     	                     C_PERSONE_NEW,
	                                                                     	                       E_MAIL_ADRESS_NEW,
	                                                                     	                         TELETYPE_ADRESS_NEW,
	                                                                     	                           PHONE_NUMBER_NEW,
	                                                                     	                             FAX_NUMBER_NEW,
	                                                                     	                               REMARK_NEW,
	                                                                     	                                 U_NAME_NEW,
	                                                                     	                                   U_IP_NEW,
	                                                                     	                                     U_HOST_NAME_NEW,
	                                                                     	                                       DATE_WRITE_NEW)
        select SEC_WB_REF_AIRCO_C_DATA_1_HIST.nextval,
                 :new.U_NAME,
	                 :new.U_IP,
	                   :new.U_HOST_NAME,
                       SYSDATE(),
                         'insert',
                           :new.id,
                             :new.id_ac,
	                             :new.DATE_FROM,
                                 :new.H_ADRESS,
	                                 :new.C_PERSONE,
	                                   :new.E_MAIL_ADRESS,
	                                     :new.TELETYPE_ADRESS,
	                                       :new.PHONE_NUMBER,
	                                         :new.FAX_NUMBER,
	                                           :new.REMARK,	
	                                             :new.U_NAME,
	                                               :new.U_IP,
	                                                 :new.U_HOST_NAME,
	                                                   :new.DATE_WRITE,
                                                       :new.id_ac,
                                                         :new.DATE_FROM,
                                                           :new.H_ADRESS,
                             	                               :new.C_PERSONE,
	                                                             :new.E_MAIL_ADRESS,
	                                                               :new.TELETYPE_ADRESS,
	                                                                 :new.PHONE_NUMBER,
	                                                                   :new.FAX_NUMBER,
	                                                                     :new.REMARK,	
	                                                                       :new.U_NAME,
	                                                                         :new.U_IP,
	                                                                           :new.U_HOST_NAME,
	                                                                             :new.DATE_WRITE

        from dual;
  end if;

  if updating then
    insert into WB_REF_AIRCO_C_DATA_1_HISTORY (ID_,
                                                 U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION,
	                                                         ID,
	                                                           ID_AC_OLD,
	                                                             DATE_FROM_OLD,
                                                                 H_ADRESS_OLD,
	                                                                 C_PERSONE_OLD,
	                                                                   E_MAIL_ADRESS_OLD,
	                                                                     TELETYPE_ADRESS_OLD,
	                                                                       PHONE_NUMBER_OLD,
	                                                                       	 FAX_NUMBER_OLD,
		                                                                         REMARK_OLD,
		                                                                           U_NAME_OLD,
		                                                                             U_IP_OLD,
		                                                                               U_HOST_NAME_OLD,
		                                                                                 DATE_WRITE_OLD,
		                                                                                   ID_AC_NEW,
	                                                                                   	   DATE_FROM_NEW,
	                                                                     	                   H_ADRESS_NEW,
	                                                                     	                     C_PERSONE_NEW,
	                                                                     	                       E_MAIL_ADRESS_NEW,
	                                                                     	                         TELETYPE_ADRESS_NEW,
	                                                                     	                           PHONE_NUMBER_NEW,
	                                                                     	                             FAX_NUMBER_NEW,
	                                                                     	                               REMARK_NEW,
	                                                                     	                                 U_NAME_NEW,
	                                                                     	                                   U_IP_NEW,
	                                                                     	                                     U_HOST_NAME_NEW,
	                                                                     	                                       DATE_WRITE_NEW)
        select SEC_WB_REF_AIRCO_C_DATA_1_HIST.nextval,
                 :new.U_NAME,
	                 :new.U_IP,
	                   :new.U_HOST_NAME,
                       SYSDATE(),
                         'update',
                           :old.id,
                             :old.id_ac,
	                             :old.DATE_FROM,
                                 :old.H_ADRESS,
	                                 :old.C_PERSONE,
	                                   :old.E_MAIL_ADRESS,
	                                     :old.TELETYPE_ADRESS,
	                                       :old.PHONE_NUMBER,
	                                         :old.FAX_NUMBER,
	                                           :old.REMARK,	
	                                             :old.U_NAME,
	                                               :old.U_IP,
	                                                 :old.U_HOST_NAME,
	                                                   :old.DATE_WRITE,
                                                       :new.id_ac,
                                                         :new.DATE_FROM,
                                                           :new.H_ADRESS,
                             	                               :new.C_PERSONE,
	                                                             :new.E_MAIL_ADRESS,
	                                                               :new.TELETYPE_ADRESS,
	                                                                 :new.PHONE_NUMBER,
	                                                                   :new.FAX_NUMBER,
	                                                                     :new.REMARK,	
	                                                                       :new.U_NAME,
	                                                                         :new.U_IP,
	                                                                           :new.U_HOST_NAME,
	                                                                             :new.DATE_WRITE

        from dual;
  end if;

END;
/
