create or replace trigger TRG_WB_REF_WS_AIR_GR_CH_AD_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_GR_CH_ADV
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_GR_CH_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CH_INDEX,
	                                                                    CH_PROC_MAC,
	                                                                      CH_CERTIFIED,
	                                                                        CH_CURTAILED,
	                                                                          TABLE_NAME,
	                                                                            CONDITION,
	                                                                              TYPE,
	                                                                                TYPE_FROM,
	                                                                                  TYPE_TO,
	                                                                                    REMARK_1,
	                                                                                      REMARK_2,
		                                                                                      U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.CH_INDEX,
	                                   :new.CH_PROC_MAC,
	                                     :new.CH_CERTIFIED,
	                                       :new.CH_CURTAILED,
	                                         :new.TABLE_NAME,
	                                           :new.CONDITION,
	                                             :new.TYPE,
	                                               :new.TYPE_FROM,
	                                                 :new.TYPE_TO,
	                                                   :new.REMARK_1,
	                                                     :new.REMARK_2,
		                         	                           :new.U_NAME,
		                               	                       :new.U_IP,
		                                	                       :new.U_HOST_NAME,
		                                 	                         :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_GR_CH_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CH_INDEX,
	                                                                    CH_PROC_MAC,
	                                                                      CH_CERTIFIED,
	                                                                        CH_CURTAILED,
	                                                                          TABLE_NAME,
	                                                                            CONDITION,
	                                                                              TYPE,
	                                                                                TYPE_FROM,
	                                                                                  TYPE_TO,
	                                                                                    REMARK_1,
	                                                                                      REMARK_2,
		                                                                                      U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
		                             :old.IDN,
	                                 :old.CH_INDEX,
	                                   :old.CH_PROC_MAC,
	                                     :old.CH_CERTIFIED,
	                                       :old.CH_CURTAILED,
	                                         :old.TABLE_NAME,
	                                           :old.CONDITION,
	                                             :old.TYPE,
	                                               :old.TYPE_FROM,
	                                                 :old.TYPE_TO,
	                                                   :old.REMARK_1,
	                                                     :old.REMARK_2,
		                         	                           :old.U_NAME,
		                               	                       :old.U_IP,
		                                	                       :old.U_HOST_NAME,
		                                 	                         :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_GR_CH_ADV_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
		                                                              IDN,
	                                                                  CH_INDEX,
	                                                                    CH_PROC_MAC,
	                                                                      CH_CERTIFIED,
	                                                                        CH_CURTAILED,
	                                                                          TABLE_NAME,
	                                                                            CONDITION,
	                                                                              TYPE,
	                                                                                TYPE_FROM,
	                                                                                  TYPE_TO,
	                                                                                    REMARK_1,
	                                                                                      REMARK_2,
		                                                                                      U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_GR_CH_ADV_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.CH_INDEX,
	                                   :new.CH_PROC_MAC,
	                                     :new.CH_CERTIFIED,
	                                       :new.CH_CURTAILED,
	                                         :new.TABLE_NAME,
	                                           :new.CONDITION,
	                                             :new.TYPE,
	                                               :new.TYPE_FROM,
	                                                 :new.TYPE_TO,
	                                                   :new.REMARK_1,
	                                                     :new.REMARK_2,
		                         	                           :new.U_NAME,
		                               	                       :new.U_IP,
		                                	                       :new.U_HOST_NAME,
		                                 	                         :new.DATE_WRITE
    from dual;
  end if;
END;
/
