create or replace trigger TRG_WB_REF_AIRCO_MEAS_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_AIRCO_MEAS
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_AIRCO_MEAS_HIST (ID_,
	                                        U_NAME_,
	                                          U_IP_,
	                                            U_HOST_NAME_,
	                                              DATE_WRITE_,
	                                                ACTION_,
	                                                  ID,
	                                                    ID_AC_OLD,
	                                                      DATE_FROM_OLD,
                                                      	  WEIGHT_ID_OLD,
	                                                          VOLUME_ID_OLD,
	                                                            LENGTH_ID_OLD,
	                                                              DENSITY_ID_OLD,
	                                                                U_NAME_OLD,
	                                                                  U_IP_OLD,
	                                                                    U_HOST_NAME_OLD,
	                                                                      DATE_WRITE_OLD,
	                                                                        ID_AC_NEW,
	                                                                          DATE_FROM_NEW,
	                                                                            WEIGHT_ID_NEW,
	                                                                              VOLUME_ID_NEW,
	                                                                                LENGTH_ID_NEW,
	                                                                                  DENSITY_ID_NEW,
	                                                                                    U_NAME_NEW,
	                                                                                      U_IP_NEW,
	                                                                                        U_HOST_NAME_NEW,
	                                                                                          DATE_WRITE_NEW)
    select SEC_WB_REF_AIRCO_MEAS_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE,
                     'insert',
                       :new.id,
                         :new.ID_AC,
	                         :new.DATE_FROM,
                             :new.WEIGHT_ID,
	                             :new.VOLUME_ID,
	                               :new.LENGTH_ID,
	                                 :new.DENSITY_ID,
                                     :new.U_NAME,
	                                     :new.U_IP,
	                                       :new.U_HOST_NAME,
	                                         :new.DATE_WRITE,	
                                             :new.ID_AC,
	                                             :new.DATE_FROM,
                                                 :new.WEIGHT_ID,
	                                                 :new.VOLUME_ID,
	                                                   :new.LENGTH_ID,
	                                                     :new.DENSITY_ID,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_AIRCO_MEAS_HIST (ID_,
	                                        U_NAME_,
	                                          U_IP_,
	                                            U_HOST_NAME_,
	                                              DATE_WRITE_,
	                                                ACTION_,
	                                                  ID,
	                                                    ID_AC_OLD,
	                                                      DATE_FROM_OLD,
                                                      	  WEIGHT_ID_OLD,
	                                                          VOLUME_ID_OLD,
	                                                            LENGTH_ID_OLD,
	                                                              DENSITY_ID_OLD,
	                                                                U_NAME_OLD,
	                                                                  U_IP_OLD,
	                                                                    U_HOST_NAME_OLD,
	                                                                      DATE_WRITE_OLD,
	                                                                        ID_AC_NEW,
	                                                                          DATE_FROM_NEW,
	                                                                            WEIGHT_ID_NEW,
	                                                                              VOLUME_ID_NEW,
	                                                                                LENGTH_ID_NEW,
	                                                                                  DENSITY_ID_NEW,
	                                                                                    U_NAME_NEW,
	                                                                                      U_IP_NEW,
	                                                                                        U_HOST_NAME_NEW,
	                                                                                          DATE_WRITE_NEW)
    select SEC_WB_REF_AIRCO_MEAS_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE,
                     'update',
                       :old.id,
                         :old.ID_AC,
	                         :old.DATE_FROM,
                             :old.WEIGHT_ID,
	                             :old.VOLUME_ID,
	                               :old.LENGTH_ID,
	                                 :old.DENSITY_ID,
                                     :old.U_NAME,
	                                     :old.U_IP,
	                                       :old.U_HOST_NAME,
	                                         :old.DATE_WRITE,	
                                             :new.ID_AC,
	                                             :new.DATE_FROM,
                                                 :new.WEIGHT_ID,
	                                                 :new.VOLUME_ID,
	                                                   :new.LENGTH_ID,
	                                                     :new.DENSITY_ID,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;
END;
/
