create or replace trigger TRG_WB_REF_WS_AIR_DOORS_T_HS
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_DOORS_T
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_DOORS_T_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 HOLD_ID,
	                                                                 D_POS_ID,
	                                                                   DOOR_NAME,
	                                                                     BA_FWD,
	                                                                       BA_AFT,
	                                                                         HEIGHT,
	                                                                           WIDTH,
	                                                                             U_NAME,
		                                                                             U_IP,
		                                                                               U_HOST_NAME,
		                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOORS_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
	                               :new.HOLD_ID,
	                                 :new.D_POS_ID,
	                                    :new.DOOR_NAME,
	                                      :new.BA_FWD,
	                                        :new.BA_AFT,
	                                          :new.HEIGHT,
	                                            :new.WIDTH,
	                                              :new.U_NAME,
		                               	              :new.U_IP,
		                                	              :new.U_HOST_NAME,
		                                 	                :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_DOORS_T_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 HOLD_ID,
	                                                                 D_POS_ID,
	                                                                   DOOR_NAME,
	                                                                     BA_FWD,
	                                                                       BA_AFT,
	                                                                         HEIGHT,
	                                                                           WIDTH,
	                                                                             U_NAME,
		                                                                             U_IP,
		                                                                               U_HOST_NAME,
		                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOORS_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,		
	                                :old.HOLD_ID,
	                                 :old.D_POS_ID,
	                                    :old.DOOR_NAME,
	                                      :old.BA_FWD,
	                                        :old.BA_AFT,
	                                          :old.HEIGHT,
	                                            :old.WIDTH,
	                                              :old.U_NAME,
		                               	              :old.U_IP,
		                                	              :old.U_HOST_NAME,
		                                 	                :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_DOORS_T_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 HOLD_ID,
	                                                                 D_POS_ID,
	                                                                   DOOR_NAME,
	                                                                     BA_FWD,
	                                                                       BA_AFT,
	                                                                         HEIGHT,
	                                                                           WIDTH,
	                                                                             U_NAME,
		                                                                             U_IP,
		                                                                               U_HOST_NAME,
		                                                                                 DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOORS_T_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                                :new.HOLD_ID,
	                                 :new.D_POS_ID,
	                                    :new.DOOR_NAME,
	                                      :new.BA_FWD,
	                                        :new.BA_AFT,
	                                          :new.HEIGHT,
	                                            :new.WIDTH,
	                                              :new.U_NAME,
		                               	              :new.U_IP,
		                                	              :new.U_HOST_NAME,
		                                 	                :new.DATE_WRITE
    from dual;
  end if;
END;
/
