create or replace trigger TRG_WB_REF_WS_AIR_REG_WGT_HS
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_REG_WGT
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_REG_WGT_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  ADV_ID,
	                                                                  DATE_FROM,
	                                                                    S_L_ADV_ID,
	                                                                      WCC_ID,
	                                                                        IS_ACARS,
	                                                                          IS_DEFAULT,
	                                                                            IS_APPROVED,
	                                                                              DOW,
	                                                                                DOI,
	                                                                                  ARM,
	                                                                                    PROC_MAC,
	                                                                                      REMARK,
	                                                                                        U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_REG_WGT_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
	                               :new.ADV_ID,
	                                 :new.DATE_FROM,
	                                   :new.S_L_ADV_ID,
	                                     :new.WCC_ID,
	                                       :new.IS_ACARS,
	                                         :new.IS_DEFAULT,
	                                           :new.IS_APPROVED,
	                                             :new.DOW,
	                                               :new.DOI,
	                                                 :new.ARM,
	                                                   :new.PROC_MAC,
	                                                     :new.REMARK,
	                                                       :new.U_NAME,
		                               	                       :new.U_IP,
		                                	                       :new.U_HOST_NAME,
		                                 	                         :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_REG_WGT_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  ADV_ID,
	                                                                  DATE_FROM,
	                                                                    S_L_ADV_ID,
	                                                                      WCC_ID,
	                                                                        IS_ACARS,
	                                                                          IS_DEFAULT,
	                                                                            IS_APPROVED,
	                                                                              DOW,
	                                                                                DOI,
	                                                                                  ARM,
	                                                                                    PROC_MAC,
	                                                                                      REMARK,
	                                                                                        U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_REG_WGT_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,		
	                               :old.ADV_ID,
	                                 :old.DATE_FROM,
	                                   :old.S_L_ADV_ID,
	                                     :old.WCC_ID,
	                                       :old.IS_ACARS,
	                                         :old.IS_DEFAULT,
	                                           :old.IS_APPROVED,
	                                             :old.DOW,
	                                               :old.DOI,
	                                                 :old.ARM,
	                                                   :old.PROC_MAC,
	                                                     :old.REMARK,
	                                                       :old.U_NAME,
		                               	                       :old.U_IP,
		                                	                       :old.U_HOST_NAME,
		                                 	                         :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_REG_WGT_HST(ID_,
	                                            U_NAME_,
	                                              U_IP_,
	                                                U_HOST_NAME_,
	                                                  DATE_WRITE_,
                                                      OPERATION_,
	                                                      ACTION_,
	                                                        ID,
	                                                          ID_AC,
	                                                            ID_WS,
		                                                            ID_BORT,
                                                                  ADV_ID,
	                                                                  DATE_FROM,
	                                                                    S_L_ADV_ID,
	                                                                      WCC_ID,
	                                                                        IS_ACARS,
	                                                                          IS_DEFAULT,
	                                                                            IS_APPROVED,
	                                                                              DOW,
	                                                                                DOI,
	                                                                                  ARM,
	                                                                                    PROC_MAC,
	                                                                                      REMARK,
	                                                                                        U_NAME,
		                                                                                        U_IP,
		                                                                                          U_HOST_NAME,
		                                                                                            DATE_WRITE)
    select SEC_WB_REF_WS_AIR_REG_WGT_HS.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.ADV_ID,
	                                 :new.DATE_FROM,
	                                   :new.S_L_ADV_ID,
	                                     :new.WCC_ID,
	                                       :new.IS_ACARS,
	                                         :new.IS_DEFAULT,
	                                           :new.IS_APPROVED,
	                                             :new.DOW,
	                                               :new.DOI,
	                                                 :new.ARM,
	                                                   :new.PROC_MAC,
	                                                     :new.REMARK,
	                                                       :new.U_NAME,
		                               	                       :new.U_IP,
		                                	                       :new.U_HOST_NAME,
		                                 	                         :new.DATE_WRITE
    from dual;
  end if;
END;
/
