create or replace trigger TRG_WB_REF_AC_CLASS_CODES_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_AIRCO_CLASS_CODES
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_AIRCO_CLASS_CODES_HIST (ID_,
	                                               U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION_,
	                                                         ID,
	                                                           ID_AC_OLD,
                                                               CLASS_CODE_OLD,
	                                                               DATE_FROM_OLD,
                                                                   DATE_TO_OLD,
                                                                     PRIORITY_CODE_OLD,
                                                      	               DESCRIPTION_OLD,
	                                                                       U_NAME_OLD,
	                                                                         U_IP_OLD,
                                                      	                     U_HOST_NAME_OLD,
	                                                                             DATE_WRITE_OLD,
	                                                                               ID_AC_NEW,
                                                                                   CLASS_CODE_NEW,
	                                                                                   DATE_FROM_NEW,
                                                                                       DATE_TO_NEW,
                                                                                         PRIORITY_CODE_NEW,
	                                                                                         DESCRIPTION_NEW,
	                                                                                           U_NAME_NEW,
	                                                                                             U_IP_NEW,
	                                                                                               U_HOST_NAME_NEW,
	                                                                                                 DATE_WRITE_NEW)
    select SEC_WB_REF_AC_CLASS_CODES_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE,
                     'insert',
                       :new.id,
                         :new.ID_AC,
                           :new.CLASS_CODE,
	                           :new.DATE_FROM,
                               :new.DATE_TO,
                                 :new.priority_code,
                                   :new.DESCRIPTION,
	                                   :new.U_NAME,
	                                     :new.U_IP,
	                                       :new.U_HOST_NAME,
	                                         :new.DATE_WRITE,
                                             :new.ID_AC,
                                               :new.CLASS_CODE,
	                                               :new.DATE_FROM,
                                                   :new.DATE_TO,
                                                     :new.priority_code,
                                                       :new.DESCRIPTION,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;

  if updating then
     insert into WB_REF_AIRCO_CLASS_CODES_HIST (ID_,
	                                               U_NAME_,
	                                                 U_IP_,
	                                                   U_HOST_NAME_,
	                                                     DATE_WRITE_,
	                                                       ACTION_,
	                                                         ID,
	                                                           ID_AC_OLD,
                                                               CLASS_CODE_OLD,
	                                                               DATE_FROM_OLD,
                                                                   DATE_TO_OLD,
                                                                     PRIORITY_CODE_OLD,
                                                      	               DESCRIPTION_OLD,
	                                                                       U_NAME_OLD,
	                                                                         U_IP_OLD,
                                                      	                     U_HOST_NAME_OLD,
	                                                                             DATE_WRITE_OLD,
	                                                                               ID_AC_NEW,
                                                                                   CLASS_CODE_NEW,
	                                                                                   DATE_FROM_NEW,
                                                                                       DATE_TO_NEW,
                                                                                         PRIORITY_CODE_NEW,
	                                                                                         DESCRIPTION_NEW,
	                                                                                           U_NAME_NEW,
	                                                                                             U_IP_NEW,
	                                                                                               U_HOST_NAME_NEW,
	                                                                                                 DATE_WRITE_NEW)
    select SEC_WB_REF_AC_CLASS_CODES_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE,
                     'update',
                       :old.id,
                         :old.ID_AC,
                           :old.CLASS_CODE,
	                           :old.DATE_FROM,
                               :old.DATE_TO,
                                 :old.priority_code,
                                   :old.DESCRIPTION,
	                                   :old.U_NAME,
	                                     :old.U_IP,
	                                       :old.U_HOST_NAME,
	                                         :old.DATE_WRITE,
                                             :new.ID_AC,
                                               :new.CLASS_CODE,
	                                               :new.DATE_FROM,
                                                   :new.DATE_TO,
                                                     :new.priority_code,
                                                       :new.DESCRIPTION,
	                                                       :new.U_NAME,
	                                                         :new.U_IP,
	                                                           :new.U_HOST_NAME,
	                                                             :new.DATE_WRITE
    from dual;
  end if;
END;
/
