create or replace trigger TRG_WB_REF_WS_AIR_BS_ID_FM_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_BAS_IND_FORM
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_BAS_IND_FORM_HST (ID_,
	                                                U_NAME_,
	                                                  U_IP_,
	                                                    U_HOST_NAME_,
	                                                      DATE_WRITE_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC_OLD,
	                                                              ID_WS_OLD,
		                                                              ID_BORT_OLD,
		                                                                DATE_FROM_OLD,
		                                                                  REF_ARM_OLD,
	                                                                      K_CONST_OLD,
	                                                                        C_CONST_OLD,
	                                                                          LEN_MAC_RC_OLD,
	                                                                            LEMAC_LERC_OLD,
		                                                                            U_NAME_OLD,
		                                                                              U_IP_OLD,
		                                                                                U_HOST_NAME_OLD,
		                                                                                  DATE_WRITE_OLD,
		                                                                                    ID_AC_NEW,
		                                                                                      ID_WS_NEW,
		                                                                                        ID_BORT_NEW,
		                                                                                          DATE_FROM_NEW,
		                                                                                            REF_ARM_NEW,
	                                                                                                K_CONST_NEW,
	                                                                                                  C_CONST_NEW,
	                                                                                                    LEN_MAC_RC_NEW,
	                                                                                                      LEMAC_LERC_NEW,
		                                                                                                      U_NAME_NEW,
		                                                                                                        U_IP_NEW,
		                                                                                                          U_HOST_NAME_NEW,
		                                                                                                            DATE_WRITE_NEW)
    select SEC_WB_REF_WS_AIR_B_I_FORM_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       :new.id,
                         :new.ID_AC,
	                         :new.ID_WS,
		                         :new.ID_BORT,
		                           :new.DATE_FROM,
		                             :new.REF_ARM,
	                                 :new.K_CONST,
	                                   :new.C_CONST,
	                                     :new.LEN_MAC_RC,
	                                       :new.LEMAC_LERC,
		                                       :new.U_NAME,
		                                         :new.U_IP,
		                                           :new.U_HOST_NAME,
		                                             :new.DATE_WRITE,
		                                               :new.ID_AC,
		                                                 :new.ID_WS,
		                                                   :new.ID_BORT,
		                                                     :new.DATE_FROM,
		                                                       :new.REF_ARM,
	                                                           :new.K_CONST,
	                                                             :new.C_CONST,
	                                                               :new.LEN_MAC_RC,
	                                                                 :new.LEMAC_LERC,
		                                                                 :new.U_NAME,
		                                                                   :new.U_IP,
		                                                                     :new.U_HOST_NAME,
		                                                                       :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_BAS_IND_FORM_HST (ID_,
	                                                U_NAME_,
	                                                  U_IP_,
	                                                    U_HOST_NAME_,
	                                                      DATE_WRITE_,
	                                                        ACTION_,
	                                                          ID,
	                                                            ID_AC_OLD,
	                                                              ID_WS_OLD,
		                                                              ID_BORT_OLD,
		                                                                DATE_FROM_OLD,
		                                                                  REF_ARM_OLD,
	                                                                      K_CONST_OLD,
	                                                                        C_CONST_OLD,
	                                                                          LEN_MAC_RC_OLD,
	                                                                            LEMAC_LERC_OLD,
		                                                                            U_NAME_OLD,
		                                                                              U_IP_OLD,
		                                                                                U_HOST_NAME_OLD,
		                                                                                  DATE_WRITE_OLD,
		                                                                                    ID_AC_NEW,
		                                                                                      ID_WS_NEW,
		                                                                                        ID_BORT_NEW,
		                                                                                          DATE_FROM_NEW,
		                                                                                            REF_ARM_NEW,
	                                                                                                K_CONST_NEW,
	                                                                                                  C_CONST_NEW,
	                                                                                                    LEN_MAC_RC_NEW,
	                                                                                                      LEMAC_LERC_NEW,
		                                                                                                      U_NAME_NEW,
		                                                                                                        U_IP_NEW,
		                                                                                                          U_HOST_NAME_NEW,
		                                                                                                            DATE_WRITE_NEW)
    select SEC_WB_REF_WS_AIR_B_I_FORM_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       :old.id,
                         :old.ID_AC,
	                         :old.ID_WS,
		                         :old.ID_BORT,
		                           :old.DATE_FROM,
		                             :old.REF_ARM,
	                                 :old.K_CONST,
	                                   :old.C_CONST,
	                                     :old.LEN_MAC_RC,
	                                       :old.LEMAC_LERC,
		                                       :old.U_NAME,
		                                         :old.U_IP,
		                                           :old.U_HOST_NAME,
		                                             :old.DATE_WRITE,
		                                               :new.ID_AC,
		                                                 :new.ID_WS,
		                                                   :new.ID_BORT,
		                                                     :new.DATE_FROM,
		                                                       :new.REF_ARM,
	                                                           :new.K_CONST,
	                                                             :new.C_CONST,
	                                                               :new.LEN_MAC_RC,
	                                                                 :new.LEMAC_LERC,
		                                                                 :new.U_NAME,
		                                                                   :new.U_IP,
		                                                                     :new.U_HOST_NAME,
		                                                                       :new.DATE_WRITE
    from dual;
  end if;
END;
/
