create or replace trigger TRG_WB_REF_WS_TYPES_HIST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_TYPES
FOR EACH ROW
BEGIN

   if inserting then
    insert into WB_REF_WS_TYPES_HIST (ID_,
	                                      U_NAME_,
	                                        U_IP_,
	                                          U_HOST_NAME_,
	                                            DATE_WRITE_,
	                                              ACTION_,
	                                                ID,
	                                                  U_NAME_OLD,
	                                                    U_IP_OLD,
                                                      	U_HOST_NAME_OLD,
	                                                        DATE_WRITE_OLD,
                                                            IATA_OLD,
	                                                            ICAO_OLD,
	                                                              DOP_IDENT_OLD,
	                                                                NAME_RUS_SMALL_OLD,
	                                                                  NAME_RUS_FULL_OLD,
	                                                                    NAME_ENG_SMALL_OLD,
	                                                                      NAME_ENG_FULL_OLD,
	                                                                        REMARK_OLD,
	                                                                          U_NAME_NEW,
	                                                                            U_IP_NEW,
	                                                                              U_HOST_NAME_NEW,
	                                                                                DATE_WRITE_NEW,
	                                                                                  IATA_NEW,
	                                                                                    ICAO_NEW,
	                                                                                      DOP_IDENT_NEW,
	                                                                                        NAME_RUS_SMALL_NEW,
	                                                                                          NAME_RUS_FULL_NEW,
	                                                                                            NAME_ENG_SMALL_NEW,
	                                                                                              NAME_ENG_FULL_NEW,
	                                                                                                REMARK_NEW)
    select SEC_WB_REF_WS_TYPES_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       :new.id,
                         :new.U_NAME,
	                         :new.U_IP,
                             :new.U_HOST_NAME,
	                             :new.DATE_WRITE,
                                 :new.IATA,
	                                 :new.ICAO,
	                                   :new.DOP_IDENT,
	                                     :new.NAME_RUS_SMALL,
	                                       :new.NAME_RUS_FULL,
	                                         :new.NAME_ENG_SMALL,
	                                           :new.NAME_ENG_FULL,
	                                             :new.REMARK,
                                                 :new.U_NAME,
	                                                 :new.U_IP,
                                                     :new.U_HOST_NAME,
	                                                     :new.DATE_WRITE,
                                                         :new.IATA,
	                                                         :new.ICAO,
	                                                           :new.DOP_IDENT,
	                                                             :new.NAME_RUS_SMALL,
	                                                               :new.NAME_RUS_FULL,
	                                                                 :new.NAME_ENG_SMALL,
	                                                                   :new.NAME_ENG_FULL,
	                                                                     :new.REMARK
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_TYPES_HIST (ID_,
	                                      U_NAME_,
	                                        U_IP_,
	                                          U_HOST_NAME_,
	                                            DATE_WRITE_,
	                                              ACTION_,
	                                                ID,
	                                                  U_NAME_OLD,
	                                                    U_IP_OLD,
                                                      	U_HOST_NAME_OLD,
	                                                        DATE_WRITE_OLD,
                                                            IATA_OLD,
	                                                            ICAO_OLD,
	                                                              DOP_IDENT_OLD,
	                                                                NAME_RUS_SMALL_OLD,
	                                                                  NAME_RUS_FULL_OLD,
	                                                                    NAME_ENG_SMALL_OLD,
	                                                                      NAME_ENG_FULL_OLD,
	                                                                        REMARK_OLD,
	                                                                          U_NAME_NEW,
	                                                                            U_IP_NEW,
	                                                                              U_HOST_NAME_NEW,
	                                                                                DATE_WRITE_NEW,
	                                                                                  IATA_NEW,
	                                                                                    ICAO_NEW,
	                                                                                      DOP_IDENT_NEW,
	                                                                                        NAME_RUS_SMALL_NEW,
	                                                                                          NAME_RUS_FULL_NEW,
	                                                                                            NAME_ENG_SMALL_NEW,
	                                                                                              NAME_ENG_FULL_NEW,
	                                                                                                REMARK_NEW)
    select SEC_WB_REF_WS_TYPES_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       :old.id,
                         :old.U_NAME,
	                         :old.U_IP,
                             :old.U_HOST_NAME,
	                             :old.DATE_WRITE,
                                 :old.IATA,
	                                 :old.ICAO,
	                                   :old.DOP_IDENT,
	                                     :old.NAME_RUS_SMALL,
	                                       :old.NAME_RUS_FULL,
	                                         :old.NAME_ENG_SMALL,
	                                           :old.NAME_ENG_FULL,
	                                             :old.REMARK,
                                                 :new.U_NAME,
	                                                 :new.U_IP,
                                                     :new.U_HOST_NAME,
	                                                     :new.DATE_WRITE,
                                                         :new.IATA,
	                                                         :new.ICAO,
	                                                           :new.DOP_IDENT,
	                                                             :new.NAME_RUS_SMALL,
	                                                               :new.NAME_RUS_FULL,
	                                                                 :new.NAME_ENG_SMALL,
	                                                                   :new.NAME_ENG_FULL,
	                                                                     :new.REMARK
    from dual;
  end if;

END;
/
