create or replace trigger TRG_WB_REF_WS_AIR_HLD_DECK_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_HLD_DECK
FOR EACH ROW
BEGIN
  if inserting then
    insert into WB_REF_WS_AIR_HLD_DECK_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 DECK_ID,
	                                                                 MAX_WEIGHT,
	                                                                   LA_FROM,
	                                                                     LA_TO,
	                                                                       BA_FWD,
	                                                                         BA_AFT,
	                                                                           U_NAME,
		                                                                           U_IP,
		                                                                             U_HOST_NAME,
		                                                                               DATE_WRITE,
                                                                                     MAX_VOLUME)
    select SEC_WB_REF_WS_AIR_HLD_DECK_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.DECK_ID,
	                                 :new.MAX_WEIGHT,
	                                   :new.LA_FROM,
	                                     :new.LA_TO,
	                                       :new.BA_FWD,
	                                         :new.BA_AFT,
	                                           :new.U_NAME,
		                               	           :new.U_IP,
		                                	           :new.U_HOST_NAME,
		                                 	             :new.DATE_WRITE,
                                                     :new.MAX_VOLUME
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_HLD_DECK_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 DECK_ID,
	                                                                 MAX_WEIGHT,
	                                                                   LA_FROM,
	                                                                     LA_TO,
	                                                                       BA_FWD,
	                                                                         BA_AFT,
	                                                                           U_NAME,
		                                                                           U_IP,
		                                                                             U_HOST_NAME,
		                                                                               DATE_WRITE,
                                                                                     MAX_VOLUME)
    select SEC_WB_REF_WS_AIR_HLD_DECK_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,		
	                               :old.DECK_ID,
	                                 :old.MAX_WEIGHT,
	                                   :old.LA_FROM,
	                                     :old.LA_TO,
	                                       :old.BA_FWD,
	                                         :old.BA_AFT,
	                                           :old.U_NAME,
		                               	           :old.U_IP,
		                                	           :old.U_HOST_NAME,
		                                 	             :old.DATE_WRITE,
                                                     :old.MAX_VOLUME
    from dual;

    insert into WB_REF_WS_AIR_HLD_DECK_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
                                                                 DECK_ID,
	                                                                 MAX_WEIGHT,
	                                                                   LA_FROM,
	                                                                     LA_TO,
	                                                                       BA_FWD,
	                                                                         BA_AFT,
	                                                                           U_NAME,
		                                                                           U_IP,
		                                                                             U_HOST_NAME,
		                                                                               DATE_WRITE,
                                                                                     MAX_VOLUME)
    select SEC_WB_REF_WS_AIR_HLD_DECK_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,		
	                               :new.DECK_ID,
	                                 :new.MAX_WEIGHT,
	                                   :new.LA_FROM,
	                                     :new.LA_TO,
	                                       :new.BA_FWD,
	                                         :new.BA_AFT,
	                                           :new.U_NAME,
		                               	           :new.U_IP,
		                                	           :new.U_HOST_NAME,
		                                 	             :new.DATE_WRITE,
                                                     :new.MAX_VOLUME
    from dual;
  end if;
END;
/
