create or replace trigger TRG_WB_REF_WS_AIR_DOW_ITM_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_DOW_ITM
FOR EACH ROW
BEGIN null;
  if inserting then
    insert into WB_REF_WS_AIR_DOW_ITM_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
	                                                                  ITEM_ID,
	                                                                    IS_INCLUDED,
	                                                                      IS_EXCLUDED,
	                                                                        REMARK,
		                                                                        U_NAME,
		                                                                          U_IP,
		                                                                            U_HOST_NAME,
		                                                                              DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOW_ITM_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
                                 :new.IDN,
	                                 :new.ADV_ID,
	                                   :new.ITEM_ID,
	                                     :new.IS_INCLUDED,
	                                       :new.IS_EXCLUDED,
	                                         :new.REMARK,
		                                         :new.U_NAME,
		                                           :new.U_IP,
		                                             :new.U_HOST_NAME,
		                                               :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_DOW_ITM_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
	                                                                  ITEM_ID,
	                                                                    IS_INCLUDED,
	                                                                      IS_EXCLUDED,
	                                                                        REMARK,
		                                                                        U_NAME,
		                                                                          U_IP,
		                                                                            U_HOST_NAME,
		                                                                              DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOW_ITM_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
                                 :old.IDN,
	                                 :old.ADV_ID,
	                                   :old.ITEM_ID,
	                                     :old.IS_INCLUDED,
	                                       :old.IS_EXCLUDED,
	                                         :old.REMARK,
		                                         :old.U_NAME,
		                                           :old.U_IP,
		                                             :old.U_HOST_NAME,
		                                               :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_DOW_ITM_HST(ID_,
	                                          U_NAME_,
	                                            U_IP_,
	                                              U_HOST_NAME_,
	                                                DATE_WRITE_,
                                                    OPERATION_,
	                                                    ACTION_,
	                                                      ID,
	                                                        ID_AC,
	                                                          ID_WS,
		                                                          ID_BORT,
                                                                IDN,
	                                                                ADV_ID,
	                                                                  ITEM_ID,
	                                                                    IS_INCLUDED,
	                                                                      IS_EXCLUDED,
	                                                                        REMARK,
		                                                                        U_NAME,
		                                                                          U_IP,
		                                                                            U_HOST_NAME,
		                                                                              DATE_WRITE)
    select SEC_WB_REF_WS_AIR_DOW_ITM_HST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
                                 :new.IDN,
	                                 :new.ADV_ID,
	                                   :new.ITEM_ID,
	                                     :new.IS_INCLUDED,
	                                       :new.IS_EXCLUDED,
	                                         :new.REMARK,
		                                         :new.U_NAME,
		                                           :new.U_IP,
		                                             :new.U_HOST_NAME,
		                                               :new.DATE_WRITE
    from dual;
  end if;
END;
/
