create or replace trigger TRG_WB_REF_WS_AIR_CFV_ADV_HST
AFTER
INSERT OR UPDATE
ON WB_REF_WS_AIR_CFV_ADV
FOR EACH ROW
BEGIN null;
  if inserting then
    insert into WB_REF_WS_AIR_CFV_ADV_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             IDN,
	                                                                 PROC_NAME,
	                                                                   REMARKS,
	                                                                     DENSITY,
	                                                                       MAX_VOLUME,
	                                                                         MAX_WEIGHT,
	                                                                           CH_WEIGHT,
	                                                                             CH_VOLUME,
	                                                                               CH_BALANCE_ARM,
	                                                                                 CH_INDEX_UNIT,
	                                                                                   CH_STANDART,
	                                                                                     CH_NON_STANDART,
	                                                                                       CH_USE_BY_DEFAULT,
		                                                                                       U_NAME,
		                                                                                         U_IP,
		                                                                                           U_HOST_NAME,
		                                                                                             DATE_WRITE)
    select SEC_WB_REF_WS_AIR_CFV_ADV_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'insert',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.PROC_NAME,
	                                   :new.REMARKS,
	                                     :new.DENSITY,
	                                       :new.MAX_VOLUME,
	                                         :new.MAX_WEIGHT,
	                                           :new.CH_WEIGHT,
	                                             :new.CH_VOLUME,
	                                               :new.CH_BALANCE_ARM,
	                                                 :new.CH_INDEX_UNIT,
	                                                   :new.CH_STANDART,
	                                                     :new.CH_NON_STANDART,
	                                                       :new.CH_USE_BY_DEFAULT,
		                                                       :new.U_NAME,
		                                                         :new.U_IP,
		                                                           :new.U_HOST_NAME,
		                                                             :new.DATE_WRITE
    from dual;
  end if;

  if updating then
    insert into WB_REF_WS_AIR_CFV_ADV_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             IDN,
	                                                                 PROC_NAME,
	                                                                   REMARKS,
	                                                                     DENSITY,
	                                                                       MAX_VOLUME,
	                                                                         MAX_WEIGHT,
	                                                                           CH_WEIGHT,
	                                                                             CH_VOLUME,
	                                                                               CH_BALANCE_ARM,
	                                                                                 CH_INDEX_UNIT,
	                                                                                   CH_STANDART,
	                                                                                     CH_NON_STANDART,
	                                                                                       CH_USE_BY_DEFAULT,
		                                                                                       U_NAME,
		                                                                                         U_IP,
		                                                                                           U_HOST_NAME,
		                                                                                             DATE_WRITE)
    select SEC_WB_REF_WS_AIR_CFV_ADV_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'delete',
                         :old.id,
                           :old.ID_AC,
	                           :old.ID_WS,
		                           :old.ID_BORT,
		                             :new.IDN,
	                                 :old.PROC_NAME,
	                                   :old.REMARKS,
	                                     :old.DENSITY,
	                                       :old.MAX_VOLUME,
	                                         :old.MAX_WEIGHT,
	                                           :old.CH_WEIGHT,
	                                             :old.CH_VOLUME,
	                                               :old.CH_BALANCE_ARM,
	                                                 :old.CH_INDEX_UNIT,
	                                                   :old.CH_STANDART,
	                                                     :old.CH_NON_STANDART,
	                                                       :old.CH_USE_BY_DEFAULT,
		                                                       :old.U_NAME,
		                                                         :old.U_IP,
		                                                           :old.U_HOST_NAME,
		                                                             :old.DATE_WRITE
    from dual;

    insert into WB_REF_WS_AIR_CFV_ADV_HST(ID_,
	                                           U_NAME_,
	                                             U_IP_,
	                                               U_HOST_NAME_,
	                                                 DATE_WRITE_,
                                                     OPERATION_,
	                                                     ACTION_,
	                                                       ID,
	                                                         ID_AC,
	                                                           ID_WS,
		                                                           ID_BORT,
		                                                             IDN,
	                                                                 PROC_NAME,
	                                                                   REMARKS,
	                                                                     DENSITY,
	                                                                       MAX_VOLUME,
	                                                                         MAX_WEIGHT,
	                                                                           CH_WEIGHT,
	                                                                             CH_VOLUME,
	                                                                               CH_BALANCE_ARM,
	                                                                                 CH_INDEX_UNIT,
	                                                                                   CH_STANDART,
	                                                                                     CH_NON_STANDART,
	                                                                                       CH_USE_BY_DEFAULT,
		                                                                                       U_NAME,
		                                                                                         U_IP,
		                                                                                           U_HOST_NAME,
		                                                                                             DATE_WRITE)
    select SEC_WB_REF_WS_AIR_CFV_ADV_HIST.nextval,
             :new.U_NAME,
	             :new.U_IP,
	               :new.U_HOST_NAME,
                   SYSDATE(),
                     'update',
                       'insert',
                         :new.id,
                           :new.ID_AC,
	                           :new.ID_WS,
		                           :new.ID_BORT,
		                             :new.IDN,
	                                 :new.PROC_NAME,
	                                   :new.REMARKS,
	                                     :new.DENSITY,
	                                       :new.MAX_VOLUME,
	                                         :new.MAX_WEIGHT,
	                                           :new.CH_WEIGHT,
	                                             :new.CH_VOLUME,
	                                               :new.CH_BALANCE_ARM,
	                                                 :new.CH_INDEX_UNIT,
	                                                   :new.CH_STANDART,
	                                                     :new.CH_NON_STANDART,
	                                                       :new.CH_USE_BY_DEFAULT,
		                                                       :new.U_NAME,
		                                                         :new.U_IP,
		                                                           :new.U_HOST_NAME,
		                                                             :new.DATE_WRITE
    from dual;
  end if;
END;
/
