CREATE TABLE WB_REF_WS_AIR_SL_CAI_TT (
ADV_ID NUMBER NOT NULL,
CLASS_CODE VARCHAR2(200) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
NUM_OF_SEATS NUMBER,
T_ID NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
