CREATE TABLE WB_REF_WS_AIR_BAL_OUTPUT_ITEM (
ACRONYM_ENG VARCHAR2(200) NOT NULL,
ACRONYM_RUS VARCHAR2(200) NOT NULL,
ID NUMBER NOT NULL,
ITEM_ENG VARCHAR2(200) NOT NULL,
ITEM_RUS VARCHAR2(200) NOT NULL
);
