CREATE TABLE WB_REF_WS_AIR_BAS_IND_FORM (
C_CONST NUMBER NOT NULL,
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
K_CONST NUMBER NOT NULL,
LEMAC_LERC NUMBER NOT NULL,
LEN_MAC_RC NUMBER NOT NULL,
REF_ARM NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
