CREATE TABLE WB_REF_MEASUREMENT_MOMENTS (
ID NUMBER NOT NULL,
NAME_ENG_FULL VARCHAR2(100) NOT NULL,
NAME_ENG_SMALL VARCHAR2(50) NOT NULL,
NAME_RUS_FULL VARCHAR2(100) NOT NULL,
NAME_RUS_SMALL VARCHAR2(50) NOT NULL
);
