CREATE TABLE WB_REF_WS_AIR_S_L_A_U_S (
ADV_ID NUMBER,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
SEAT_ID NUMBER,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
