CREATE TABLE WB_REF_WS_AIR_S_L_P_S_P (
ADV_ID NUMBER NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
PARAM_ID NUMBER NOT NULL,
PLAN_ID NUMBER NOT NULL,
S_SEAT_ID NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
