CREATE TABLE WB_REF_WS_AIR_TYPE (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
ID_WS_TRANSP_KATEG NUMBER NOT NULL,
ID_WS_TYPE_OF_LOADING NUMBER NOT NULL,
IS_LOWER_DECK NUMBER NOT NULL,
IS_MAIN_DECK NUMBER NOT NULL,
IS_UPPER_DECK NUMBER NOT NULL,
REMARK CLOB NOT NULL,
REVIZION VARCHAR2(200) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
