CREATE TABLE WB_REF_WS_AIR_DOW_SWA_CODES (
BALANCE_ARM NUMBER,
CODE_NAME_1 VARCHAR2(200) NOT NULL,
CODE_NAME_2 VARCHAR2(200) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDEX_UNIT NUMBER,
REMARKS VARCHAR2(1000) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(20) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
WEIGHT NUMBER
);
