CREATE TABLE WB_REF_WS_AIR_S_L_PLAN (
ADV_ID NUMBER NOT NULL,
BALANCE_ARM NUMBER,
CABIN_SECTION VARCHAR2(200) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDEX_PER_WT_UNIT NUMBER,
LENGTH_OF_ARM NUMBER,
MAX_SEATS NUMBER,
MAX_WEIGHT NUMBER,
ROW_NUMBER NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
