CREATE TABLE WB_REF_AIRCO_C_DATA_1 (
C_PERSONE VARCHAR2(200) NOT NULL,
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE DEFAULT sysdate NOT NULL,
E_MAIL_ADRESS VARCHAR2(200) NOT NULL,
FAX_NUMBER VARCHAR2(200) NOT NULL,
H_ADRESS VARCHAR2(200) NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
PHONE_NUMBER VARCHAR2(200) NOT NULL,
REMARK CLOB,
TELETYPE_ADRESS VARCHAR2(200) NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
