CREATE TABLE WB_REF_COUNTRY (
CC_E VARCHAR2(50) NOT NULL,
CC_R VARCHAR2(50) NOT NULL,
DATE_WRITE DATE NOT NULL,
FLAG CLOB,
ID NUMBER NOT NULL,
NAME_ENG_FULL VARCHAR2(100) NOT NULL,
NAME_ENG_SMALL VARCHAR2(50) NOT NULL,
NAME_RUS_FULL VARCHAR2(100) NOT NULL,
NAME_RUS_SMALL VARCHAR2(50) NOT NULL,
REMARK CLOB,
U_HOST_NAME VARCHAR2(50) NOT NULL,
U_IP VARCHAR2(50) NOT NULL,
U_NAME VARCHAR2(50) NOT NULL
);
