CREATE TABLE WB_REF_WS_AIR_GR_CH_ITL_L (
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_CH NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDX NUMBER,
PROC_MAC NUMBER,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
WEIGHT NUMBER NOT NULL
);
