CREATE TABLE WB_REF_WS_AIR_SL_CAI_T (
ADV_ID NUMBER NOT NULL,
BA_AFT NUMBER,
BA_CENTROID NUMBER,
BA_FWD NUMBER,
CABIN_SECTION VARCHAR2(200) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDEX_PER_WT_UNIT NUMBER,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
