CREATE TABLE WB_REF_AIRCOMPANY_ADV_INFO (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
IATA_CODE VARCHAR2(50) NOT NULL,
ICAO_CODE VARCHAR2(50) NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_CITY NUMBER NOT NULL,
NAME_ENG_FULL VARCHAR2(100) NOT NULL,
NAME_ENG_SMALL VARCHAR2(50) NOT NULL,
NAME_RUS_FULL VARCHAR2(100) NOT NULL,
NAME_RUS_SMALL VARCHAR2(50) NOT NULL,
OTHER_CODE VARCHAR2(50) NOT NULL,
REMARK CLOB,
U_HOST_NAME VARCHAR2(50) NOT NULL,
U_IP VARCHAR2(50) NOT NULL,
U_NAME VARCHAR2(50) NOT NULL
);
