CREATE TABLE WB_REF_AIRCO_PORT_FLIGHT (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_PORT NUMBER NOT NULL,
IS_CHECK_IN NUMBER NOT NULL,
IS_LOAD_CONTROL NUMBER NOT NULL,
UTC_DIFF NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
