CREATE TABLE WB_REF_WS_AIR_DOORS_T (
BA_AFT NUMBER NOT NULL,
BA_FWD NUMBER NOT NULL,
DATE_WRITE DATE NOT NULL,
DOOR_NAME VARCHAR2(200) NOT NULL,
D_POS_ID NUMBER NOT NULL,
HEIGHT NUMBER NOT NULL,
HOLD_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
WIDTH NUMBER NOT NULL
);
