CREATE TABLE WB_REF_AIRCO_PAX_WEIGHTS (
ADULT NUMBER,
BY_DEFAULT NUMBER NOT NULL,
CHILD NUMBER,
DATE_FROM DATE,
DATE_WRITE DATE NOT NULL,
DESCRIPTION VARCHAR2(1000) NOT NULL,
FEMALE NUMBER,
HAND_BAG NUMBER,
HAND_BAG_INCLUDE NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_CLASS NUMBER NOT NULL,
INFANT NUMBER,
MALE NUMBER,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
