CREATE TABLE WB_REF_WS_BORT_AHM_TREE (
FUNCTIONS VARCHAR2(500) DEFAULT 'EMPTY_STRING' NOT NULL,
ID NUMBER NOT NULL,
LEVEL_TREE NUMBER NOT NULL,
PARENT_ID NUMBER NOT NULL,
SHOW_INFO NUMBER DEFAULT 0 NOT NULL,
SORT_PRIOR_ENG NUMBER NOT NULL,
SORT_PRIOR_RUS NUMBER NOT NULL,
TAB_INDEX NUMBER NOT NULL,
TITLE_ENG VARCHAR2(100) NOT NULL,
TITLE_RUS VARCHAR2(100) NOT NULL
);
