CREATE TABLE WB_REF_WS_AIR_MIN_WGHT_IDN (
CONDITION VARCHAR2(1000) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
TABLE_NAME VARCHAR2(200) NOT NULL,
TYPE VARCHAR2(1000) NOT NULL,
TYPE_FROM NUMBER,
TYPE_TO NUMBER,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
