CREATE TABLE WB_REF_WS_AIR_MEASUREMENT (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
DENSITY_ID_FUEL NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
LENGTH_ID NUMBER NOT NULL,
MOMENTS_ID NUMBER NOT NULL,
REMARK CLOB NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
VOLUME_ID NUMBER NOT NULL,
VOLUME_ID_LIQUID NUMBER NOT NULL,
WEIGHT_ID NUMBER NOT NULL
);
