CREATE TABLE WB_REF_WS_TRANSP_KATEG (
DATE_WRITE DATE NOT NULL,
DESCRIPTION CLOB NOT NULL,
ID NUMBER NOT NULL,
NAME VARCHAR2(200) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
