CREATE TABLE WB_REF_WS_AIR_MIN_WGHT_T (
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
IS_DEFAULT NUMBER NOT NULL,
MIN_LND_WEIGHT NUMBER NOT NULL,
MIN_RMP_WEIGHT NUMBER NOT NULL,
MIN_TO_WEIGHT NUMBER NOT NULL,
MIN_ZF_WEIGHT NUMBER NOT NULL,
REMARK VARCHAR2(2000) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
