CREATE TABLE WB_REF_AIRCO_MEAS (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
DENSITY_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
LENGTH_ID NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL,
VOLUME_ID NUMBER NOT NULL,
WEIGHT_ID NUMBER NOT NULL
);
