CREATE TABLE WB_REF_AIRCO_C_DATA_DTM (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
DTM_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
REMARK CLOB,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
