CREATE TABLE WB_REF_WS_AIR_DOW_ITM (
ADV_ID NUMBER NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
IS_EXCLUDED NUMBER NOT NULL,
IS_INCLUDED NUMBER NOT NULL,
ITEM_ID NUMBER NOT NULL,
REMARK VARCHAR2(1000),
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(20) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
