CREATE TABLE WB_REF_WS_AIR_SEAT_LAY_ADV (
CABIN_ID NUMBER NOT NULL,
CH_BALANCE_ARM NUMBER NOT NULL,
CH_INDEX_UNIT NUMBER NOT NULL,
DATE_FROM DATE,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
NUM_OF_SEATS NUMBER,
TABLE_NAME VARCHAR2(200) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
