CREATE TABLE WB_REF_WS_AIR_GR_CH_REL (
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
IDN_REL NUMBER,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
