CREATE TABLE WB_REF_WS_AIR_EQUIP_ADV (
DATE_FROM DATE DEFAULT sysdate,
DATE_WRITE DATE NOT NULL,
GOL_BALANCE_ARM NUMBER NOT NULL,
GOL_INDEX_UNIT NUMBER NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
PWL_BALANCE_ARM NUMBER NOT NULL,
PWL_INDEX_UNIT NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
