CREATE TABLE WB_REF_WS_AIR_HLD_HLD_A (
CH_BALANCE_ARM NUMBER NOT NULL,
CH_INDEX_UNIT NUMBER NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
REMARKS CLOB,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
