CREATE TABLE WB_REF_WS_AIR_DOW_CR_CODES (
ARM_DIFF NUMBER,
BY_DEFAULT NUMBER NOT NULL,
CC_NUMBER NUMBER,
CODE_TYPE VARCHAR2(200) NOT NULL,
CR_CODE_NAME VARCHAR2(200) NOT NULL,
DATE_WRITE DATE NOT NULL,
FC_NUMBER NUMBER,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDEX_DIFF NUMBER,
REMARKS VARCHAR2(1000) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(20) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
WEIHGT_DIFF NUMBER
);
