CREATE TABLE WB_REF_WS_AIR_S_L_C_ADV (
ADV_ID NUMBER NOT NULL,
CH_CAI_BALANCE_ARM NUMBER NOT NULL,
CH_CAI_INDEX_UNIT NUMBER NOT NULL,
CH_CI_BALANCE_ARM NUMBER NOT NULL,
CH_CI_INDEX_UNIT NUMBER NOT NULL,
CH_USE_AS_DEFAULT NUMBER NOT NULL,
DATE_FROM DATE,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(20) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
