CREATE TABLE WB_REF_AIRCO_ULD_REM_HIST (
ACTION_ VARCHAR2(50) NOT NULL,
DATE_WRITE DATE NOT NULL,
DATE_WRITE_ DATE NOT NULL,
ID NUMBER NOT NULL,
ID_ NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
OPERATION_ VARCHAR2(50) NOT NULL,
REMARKS CLOB NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_HOST_NAME_ VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_IP_ VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL,
U_NAME_ VARCHAR2(200) NOT NULL
);
