CREATE TABLE WB_REF_AIRCOMPANY_KEY_HISTORY (
ACTION VARCHAR2(50) NOT NULL,
DATE_WRITE_ DATE NOT NULL,
DATE_WRITE_NEW DATE NOT NULL,
DATE_WRITE_OLD DATE NOT NULL,
ID NUMBER NOT NULL,
ID_ NUMBER NOT NULL,
U_HOST_NAME_ VARCHAR2(50) NOT NULL,
U_HOST_NAME_NEW VARCHAR2(50) NOT NULL,
U_HOST_NAME_OLD VARCHAR2(50) NOT NULL,
U_IP_ VARCHAR2(50) NOT NULL,
U_IP_NEW VARCHAR2(50) NOT NULL,
U_IP_OLD VARCHAR2(50) NOT NULL,
U_NAME_ VARCHAR2(50) NOT NULL,
U_NAME_NEW VARCHAR2(50) NOT NULL,
U_NAME_OLD VARCHAR2(50) NOT NULL
);
