CREATE TABLE WB_REF_WS_AIR_HLD_DECK (
BA_AFT NUMBER,
BA_FWD NUMBER,
DATE_WRITE DATE NOT NULL,
DECK_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
LA_FROM NUMBER,
LA_TO NUMBER,
MAX_VOLUME NUMBER,
MAX_WEIGHT NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
