CREATE TABLE WB_REF_WS_AIR_GR_CH_CND (
CND_NAME_ID NUMBER NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
OPER_ID_1 NUMBER NOT NULL,
OPER_ID_2 NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
VALUE_1 NUMBER NOT NULL,
VALUE_2 NUMBER
);
