CREATE TABLE WB_REF_WS_AIR_ATO (
CHECK_LATERAL_IMBALANCE_LIMITS NUMBER NOT NULL,
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
EZFW_THRESHOLD_LIMIT NUMBER NOT NULL,
EZFW_THRESHOLD_LIMIT_VAL NUMBER,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
PTO_CABIN_AREA_TRIM NUMBER NOT NULL,
PTO_CLASS_TRIM NUMBER NOT NULL,
PTO_SEAT_ROW_TRIM NUMBER NOT NULL,
REMARK CLOB NOT NULL,
SORT_CONTAINER_LOADING NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
