CREATE TABLE WB_REF_AIRCO_DOCS_HEAD_FOOT (
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
DOC_ID NUMBER NOT NULL,
FOOTER CLOB NOT NULL,
HEADER CLOB NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
