CREATE TABLE WB_REF_AIRCO_MISC_ADV (
DATE_FROM DATE,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
REMARK CLOB,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
