CREATE TABLE WB_REF_AIRCO_FLIGHT_CODES (
CODE_NAME VARCHAR2(100) NOT NULL,
DATE_FROM DATE,
DATE_TO DATE,
DATE_WRITE DATE NOT NULL,
DESCRIPTION VARCHAR2(1000) NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(100) NOT NULL,
U_IP VARCHAR2(100) NOT NULL,
U_NAME VARCHAR2(100) NOT NULL
);
