CREATE TABLE WB_REF_WS_AIR_MIN_WGHT_USE (
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
OPER_ID_1 NUMBER NOT NULL,
OPER_ID_2 NUMBER NOT NULL,
USE_ITEM_ID NUMBER NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
VALUE_1 NUMBER,
VALUE_2 NUMBER
);
