CREATE TABLE WB_REF_WS_AIR_DOW_IDN_HST (
ACTION_ VARCHAR2(50) NOT NULL,
DATE_WRITE DATE NOT NULL,
DATE_WRITE_ DATE NOT NULL,
ID NUMBER NOT NULL,
ID_ NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
OPERATION_ VARCHAR2(50) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_HOST_NAME_ VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(20) NOT NULL,
U_IP_ VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL,
U_NAME_ VARCHAR2(200) NOT NULL
);
