CREATE TABLE WB_REF_AIRCOMPANY_LOGO (
DATE_FROM DATE,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
LOGO CLOB NOT NULL,
LOGO_TYPE VARCHAR2(50),
U_HOST_NAME VARCHAR2(50) NOT NULL,
U_IP VARCHAR2(50) NOT NULL,
U_NAME VARCHAR2(50) NOT NULL
);
