CREATE TABLE WB_REF_WS_AIR_CABIN_FD (
ADV_ID NUMBER,
BA_CENTROID NUMBER,
DATE_WRITE DATE NOT NULL,
FCL_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
IDN NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
INDEX_PER_WT_UNIT NUMBER,
LA_CENTROID NUMBER,
MAX_NUM_SEATS NUMBER,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
