CREATE TABLE WB_REF_WS_AIR_SUPPL_INFO_ADV_I (
ADV_ID NUMBER NOT NULL,
DATE_FROM DATE NOT NULL,
DATE_WRITE VARCHAR2(20),
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
ITEM_ID NUMBER NOT NULL,
REMARK VARCHAR2(1000) NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
