CREATE TABLE WB_REF_WS_AIR_BAL_OUTPUT_DATA (
ADV_ID NUMBER NOT NULL,
DATE_FROM DATE NOT NULL,
DATE_WRITE DATE NOT NULL,
DET_COL_ID NUMBER NOT NULL,
ID NUMBER NOT NULL,
ID_AC NUMBER NOT NULL,
ID_BORT NUMBER NOT NULL,
ID_WS NUMBER NOT NULL,
IS_CHECK NUMBER NOT NULL,
ITEM_ID NUMBER NOT NULL,
REMARK CLOB NOT NULL,
U_HOST_NAME VARCHAR2(200) NOT NULL,
U_IP VARCHAR2(200) NOT NULL,
U_NAME VARCHAR2(200) NOT NULL
);
