CREATE TABLE WB_SCHED (
AV_BAG_PAX NUMBER,
BLOCK_FUEL NUMBER,
CAPTAIN VARCHAR2(40),
CREW VARCHAR2(20),
ETD DATE,
FLIGHT_STATUS VARCHAR2(10),
GATE VARCHAR2(10),
ID NUMBER NOT NULL,
ID_AC NUMBER,
ID_BORT NUMBER,
ID_SL NUMBER,
ID_WS NUMBER,
NR VARCHAR2(20),
STD DATE,
TRIP_FUEL NUMBER
);
