CREATE TABLE WB_TEMP_XML_ID_EX (
ACTION_DATE DATE DEFAULT Null ,
ACTION_NAME VARCHAR2(200) NOT NULL,
F_DATE_1 DATE DEFAULT Null ,
F_DATE_2 DATE DEFAULT Null ,
F_DATE_3 DATE DEFAULT Null ,
F_DATE_4 DATE DEFAULT Null ,
F_DATE_5 DATE DEFAULT Null ,
F_FLT_1 NUMBER DEFAULT Null 
,
F_FLT_2 NUMBER DEFAULT Null 
,
F_FLT_3 NUMBER DEFAULT Null 
,
F_FLT_4 NUMBER DEFAULT Null 
,
F_FLT_5 NUMBER DEFAULT Null 
,
F_STR_1 VARCHAR2(1000) DEFAULT Null 
,
F_STR_2 VARCHAR2(1000) DEFAULT Null 
,
F_STR_3 VARCHAR2(1000) DEFAULT Null 
,
F_STR_4 VARCHAR2(1000) DEFAULT Null 
,
F_STR_5 VARCHAR2(1000) DEFAULT Null 
,
ID NUMBER NOT NULL
);
