CREATE TABLE WB_TEMP_XML_ID_KEY (
ID NUMBER NOT NULL,
NUM_VAL_1 NUMBER DEFAULT null,
NUM_VAL_2 NUMBER DEFAULT null,
NUM_VAL_3 NUMBER DEFAULT null,
NUM_VAL_4 NUMBER DEFAULT null,
NUM_VAL_5 NUMBER DEFAULT null,
NUM_VAL_6 NUMBER DEFAULT null,
NUM_VAL_7 NUMBER DEFAULT null,
STR_VAL_1 VARCHAR2(1000) DEFAULT null ,
STR_VAL_2 VARCHAR2(1000) DEFAULT null ,
STR_VAL_3 VARCHAR2(1000) DEFAULT null ,
STR_VAL_4 VARCHAR2(1000) DEFAULT null ,
STR_VAL_5 VARCHAR2(1000) DEFAULT null ,
STR_VAL_6 VARCHAR2(1000) DEFAULT null ,
STR_VAL_7 VARCHAR2(1000) DEFAULT null
);
