CREATE TABLE WB_USERS_IN_OUT (
A_VERSION VARCHAR2(50) NOT NULL,
DATE_WRITE DATE NOT NULL,
ID NUMBER NOT NULL,
U_ACTION VARCHAR2(50) NOT NULL,
U_COMP_NAME VARCHAR2(50) NOT NULL,
U_HOST_NAME VARCHAR2(50) NOT NULL,
U_IP VARCHAR2(50) NOT NULL,
U_NAME VARCHAR2(50) NOT NULL
);
