CREATE TABLE XML_STUFF (
  DESCR        VARCHAR2(2000),
  ID           VARCHAR2(50) NOT NULL,
  PAGE_N       NUMBER(3)    NOT NULL,
  TYPE         VARCHAR2(20) NOT NULL,
  VERSION      NUMBER       NOT NULL
);