CREATE TABLE AGENT_STAT (
DBAG_AMOUNT AGENT_STAT_T NOT NULL,
DBAG_WEIGHT AGENT_STAT_T NOT NULL,
DESK VARCHAR2(6) NOT NULL,
DPAX_AMOUNT AGENT_STAT_T NOT NULL,
DRK_AMOUNT AGENT_STAT_T NOT NULL,
DRK_WEIGHT AGENT_STAT_T NOT NULL,
DTCKIN_AMOUNT AGENT_STAT_T NOT NULL,
ONDATE DATE NOT NULL,
PAX_AMOUNT NUMBER(9) NOT NULL,
PAX_TIME NUMBER(9) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
USER_ID NUMBER(9) NOT NULL
);
