CREATE TABLE AODB_UNACCOMP (
GRP_ID NUMBER(9) NOT NULL,
NUM NUMBER(4) NOT NULL,
POINT_ADDR VARCHAR2(6) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PR_CABIN NUMBER(1) NOT NULL,
RECORD VARCHAR2(1000) NOT NULL
);
