CREATE TABLE AODB_EVENTS (
AIRLINE VARCHAR2(3) NOT NULL,
FILENAME VARCHAR2(50) NOT NULL,
MSG VARCHAR2(1000) NOT NULL,
POINT_ADDR VARCHAR2(6) NOT NULL,
RECORD VARCHAR2(4000) NOT NULL,
REC_NO NUMBER(6) NOT NULL,
TIME DATE NOT NULL,
TYPE VARCHAR2(3) NOT NULL
);
