CREATE TABLE APPS_PAX_DATA (
    APPS_PAX_ID VARCHAR2(15),
    CICX_MSG_ID NUMBER(9),
    CICX_MSG_TEXT VARCHAR2(4000),
    CIRQ_MSG_ID NUMBER(9) NOT NULL,
    CIRQ_MSG_TEXT VARCHAR2(4000) NOT NULL,
    FAMILY_NAME VARCHAR2(40) NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    SEND_TIME DATE NOT NULL,
    SETTINGS_ID NUMBER(9),
    STATUS VARCHAR2(1)
);
