CREATE TABLE ARX_MARK_TRIPS (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP_DEP VARCHAR2(3) NOT NULL,
    FLT_NO NUMBER NOT NULL,
    PART_KEY DATE NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    SCD DATE NOT NULL,
    SUFFIX VARCHAR2(1)
);
