CREATE TABLE ARX_STAT_REPRINT (
    AMOUNT NUMBER(9) NOT NULL,
    CKIN_TYPE VARCHAR2(5),
    DESK VARCHAR2(6) NOT NULL,
    PART_KEY DATE NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    SCD_OUT DATE NOT NULL
);
