CREATE TABLE ARX_STAT_SERVICES (
    AIRP_ARV VARCHAR2(3) NOT NULL,
    AIRP_DEP VARCHAR2(3) NOT NULL,
    PART_KEY DATE NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    RECEIPT_NO VARCHAR2(30),
    RFIC VARCHAR2(1),
    RFISC VARCHAR2(15) NOT NULL,
    SCD_OUT DATE NOT NULL
);
