CREATE TABLE ARX_UNACCOMP_BAG_INFO (
    AIRLINE VARCHAR2(3),
    FLT_NO NUMBER(5),
    GRP_ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(64),
    NUM NUMBER(3) NOT NULL,
    ORIGINAL_TAG_NO VARCHAR2(15),
    PART_KEY DATE NOT NULL,
    SCD DATE,
    SUFFIX VARCHAR2(1),
    SURNAME VARCHAR2(64)
);
