CREATE TABLE ARX_TRIP_SETS (
    C NUMBER(3),
    COMP_ID NUMBER(9),
    F NUMBER(3),
    MAX_COMMERCE NUMBER(6) DEFAULT 0,
    PART_KEY DATE NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    PR_ETSTATUS NUMBER(1) NOT NULL,
    PR_STAT NUMBER(1) NOT NULL,
    PR_TRANZ_REG NUMBER(1),
    Y NUMBER(3)
);
