CREATE TABLE ARX_STAT_REM (
    AIRP_LAST VARCHAR2(3) NOT NULL,
    DESK VARCHAR2(6) NOT NULL,
    PART_KEY DATE NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    RATE NUMBER(12,2),
    RATE_CUR VARCHAR2(3),
    REM_CODE VARCHAR2(4) NOT NULL,
    RFISC VARCHAR2(50),
    TICKET_NO VARCHAR2(20),
    TRAVEL_TIME DATE,
    USER_ID NUMBER(9) NOT NULL
);
