CREATE TABLE ARX_BAG_TAGS (
    BAG_NUM NUMBER(3),
    COLOR VARCHAR2(2),
    GRP_ID NUMBER(9) NOT NULL,
    NO NUMBER(15) NOT NULL,
    NUM NUMBER(3) NOT NULL,
    PART_KEY DATE NOT NULL,
    PR_PRINT NUMBER(1) NOT NULL,
    TAG_TYPE VARCHAR2(5) NOT NULL
);
