CREATE TABLE ARX_BI_STAT (
    DESK VARCHAR2(6) NOT NULL,
    HALL NUMBER(9) NOT NULL,
    OP_TYPE VARCHAR2(10) NOT NULL,
    PART_KEY DATE NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    PRINT_TYPE VARCHAR2(3) NOT NULL,
    PR_PRINT NUMBER(1) NOT NULL,
    SCD_OUT DATE NOT NULL,
    TERMINAL NUMBER(9),
    TIME_PRINT DATE NOT NULL
);
