CREATE TABLE ARX_TCKIN_SEGMENTS (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP_ARV VARCHAR2(3) NOT NULL,
    AIRP_DEP VARCHAR2(3) NOT NULL,
    FLT_NO NUMBER(5) NOT NULL,
    GRP_ID NUMBER(9) NOT NULL,
    PART_KEY DATE NOT NULL,
    PR_FINAL NUMBER(1) NOT NULL,
    SCD DATE NOT NULL,
    SEG_NO NUMBER(1) NOT NULL,
    SUFFIX VARCHAR2(1)
);
