CREATE TABLE ARX_TLGS_IN (
    ADDR VARCHAR2(300),
    BODY VARCHAR2(4000),
    ENDING VARCHAR2(20),
    HEADING VARCHAR2(100),
    ID NUMBER(9) NOT NULL,
    MERGE_KEY VARCHAR2(50),
    NUM NUMBER(5) NOT NULL,
    PAGE_NO NUMBER(9) NOT NULL,
    PART_KEY DATE NOT NULL,
    TIME_CREATE DATE,
    TIME_PARSE DATE,
    TIME_RECEIVE DATE NOT NULL,
    TYPE VARCHAR2(3)
);
