CREATE TABLE ARX_EVENTS (
EV_ORDER NUMBER(9) NOT NULL,
EV_USER VARCHAR2(20),
ID1 NUMBER(9),
ID2 NUMBER(9),
ID3 NUMBER(9),
LANG VARCHAR2(2),
MSG VARCHAR2(250) NOT NULL,
PART_KEY DATE NOT NULL,
PART_NUM NUMBER(2),
SCREEN VARCHAR2(15),
STATION VARCHAR2(15),
TIME DATE NOT NULL,
TYPE VARCHAR2(3) NOT NULL,
SUB_TYPE VARCHAR2(100)
);
