CREATE TABLE ARX_LIMITED_CAPABILITY_STAT (
    AIRP_ARV VARCHAR2(3) NOT NULL,
    PART_KEY DATE NOT NULL,
    PAX_AMOUNT NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    REM_CODE VARCHAR2(5) NOT NULL
);
