CREATE TABLE BAG_TYPES (
    CODE NUMBER(2) NOT NULL,
    DESCR VARCHAR2(2000),
    DESCR_LAT VARCHAR2(2000),
    ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    NAME_LAT VARCHAR2(50),
    REM_CODE_LCI VARCHAR2(4),
    REM_CODE_LDM VARCHAR2(3)
);
