CREATE TABLE BAG_UNACCOMP (
    AIRLINE VARCHAR2(3),
    AIRP VARCHAR2(3),
    CODE NUMBER(9) NOT NULL,
    ID NUMBER(9) NOT NULL,
    PR_ADDITIONAL NUMBER(1) NOT NULL,
    PR_UNACCOMP NUMBER(1) NOT NULL
);
