CREATE TABLE BALANCE_SETS (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3) NOT NULL,
BALANCE_TYPE VARCHAR2(5) NOT NULL,
BORT VARCHAR2(10),
FLT_NO NUMBER(5),
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL
);
