CREATE TABLE BI_AIRLINE_SERVICE (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP VARCHAR2(3) NOT NULL,
    HALL NUMBER(9),
    ID NUMBER(9) NOT NULL,
    PR_DENIAL NUMBER(1) NOT NULL,
    PR_PRINT_BI NUMBER(1) NOT NULL,
    TERMINAL NUMBER(9)
);
