CREATE TABLE BRAND_FARES (
    AIRLINE VARCHAR2(3) NOT NULL,
    BRAND VARCHAR2(10) NOT NULL,
    FARE_BASIS VARCHAR2(15) NOT NULL,
    ID NUMBER(9) NOT NULL,
    SALE_FIRST_DATE DATE NOT NULL,
    SALE_LAST_DATE DATE
);
