CREATE TABLE COMP_ELEM_TYPES (
CODE VARCHAR2(1) NOT NULL,
FILENAME VARCHAR2(20) NOT NULL,
IMAGE LONG RAW NOT NULL,
NAME VARCHAR2(50),
NAME_LAT VARCHAR2(50),
PR_DEL NUMBER(1) NOT NULL,
PR_SEAT NUMBER(1) NOT NULL,
TIME_CREATE DATE NOT NULL
);
