CREATE TABLE CONVERT_ROUTES (
ACT_IN DATE,
ACT_OUT DATE,
AIRP VARCHAR2(3),
EST_IN DATE,
EST_OUT DATE,
MOVE_ID NUMBER(9),
NUM NUMBER(3),
RTYPE VARCHAR2(1),
SCD_IN DATE,
SCD_OUT DATE,
TRIP_ID NUMBER(9)
);
