CREATE TABLE CRS_DATA (
AIRP_ARV VARCHAR2(3) NOT NULL,
AVAIL NUMBER(3),
CFG NUMBER(3),
CLASS VARCHAR2(1) NOT NULL,
PAD NUMBER(3),
POINT_ID NUMBER(9) NOT NULL,
RESA NUMBER(3),
SENDER VARCHAR2(7) NOT NULL,
SYSTEM VARCHAR2(3) NOT NULL,
TRANZIT NUMBER(3)
);
