CREATE TABLE CURRENCY (
CODE VARCHAR2(3) NOT NULL,
CODE_LAT VARCHAR2(3),
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
NAME_LAT VARCHAR2(30),
PR_DEL NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL,
TID_SYNC NUMBER(9) NOT NULL
);
