CREATE TABLE CUSTOM_ALARM_TYPES (
    AIRLINE VARCHAR2(3),
    ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    NAME_LAT VARCHAR2(100) NOT NULL,
    PR_DEL NUMBER(1) NOT NULL,
    TID NUMBER(9) NOT NULL
);
