CREATE TABLE CUSTOM_ALARM_SETS (
AIRLINE VARCHAR2(3) NOT NULL,
ALARM NUMBER(9) NOT NULL,
BRAND_AIRLINE VARCHAR2(3),
BRAND_CODE VARCHAR2(10),
FQT_AIRLINE VARCHAR2(3),
FQT_TIER_LEVEL VARCHAR2(50),
ID NUMBER(9) NOT NULL,
RFISC VARCHAR2(15)
);
