CREATE TABLE DEFERRED_ASTRA_CALLS (
    ID NUMBER(9) NOT NULL,
    SOURCE VARCHAR2(30) NOT NULL,
    STATUS NUMBER(1) NOT NULL,
    TIME_CREATE TIMESTAMP NOT NULL,
    TIME_HANDLE TIMESTAMP,
    XML_REQ CLOB NOT NULL,
    XML_RES CLOB
);
