CREATE TABLE DEL_VO (
    COUPON_NO NUMBER(1),
    FULL_NAME VARCHAR2(129) NOT NULL,
    PERS_TYPE VARCHAR2(2) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    REG_NO NUMBER(3) NOT NULL,
    REM_CODES VARCHAR2(500),
    TICKET_NO VARCHAR2(15),
    TOTAL NUMBER(9) NOT NULL,
    VOUCHER VARCHAR2(2) NOT NULL
);
