CREATE TABLE DEV_EVENT_CMD (
BINARY NUMBER(1) NOT NULL,
CMD_DATA VARCHAR2(100) NOT NULL,
CMD_FMT_FILE NUMBER(1) NOT NULL,
CMD_FMT_HEX NUMBER(1) NOT NULL,
CMD_ORDER NUMBER(2) NOT NULL,
DESK_GRP_ID NUMBER(9),
DEV_MODEL VARCHAR2(10),
ERROR_ABORT NUMBER(1) NOT NULL,
ERROR_LOG NUMBER(1) NOT NULL,
ERROR_SHOW NUMBER(1) NOT NULL,
EVENT_NAME VARCHAR2(30) NOT NULL,
FMT_TYPE VARCHAR2(10) NOT NULL,
POSTED NUMBER(1) NOT NULL,
SESS_TYPE VARCHAR2(10),
WAIT_PRIOR_CMD NUMBER(1) NOT NULL
);
