CREATE TABLE DROP_PRIOR_SCHED_DAYS (
DAYS VARCHAR2(7),
FIRST_DAY DATE,
LAST_DAY DATE,
MOVE_ID NUMBER(9),
NUM NUMBER(3),
PRIOR_DAYS VARCHAR2(7),
PRIOR_FIRST_DAY DATE,
PRIOR_LAST_DAY DATE,
TRIP_ID NUMBER(9)
);
