CREATE TABLE DROP_TYPEB_ADDRS (
ADDR VARCHAR2(100) NOT NULL,
AIRLINE VARCHAR2(3),
AIRP_ARV VARCHAR2(3),
AIRP_DEP VARCHAR2(3),
CRS VARCHAR2(7),
FLT_NO NUMBER(5),
ID NUMBER(9) NOT NULL,
PR_LAT NUMBER(1) NOT NULL,
PR_MARK_FLT NUMBER(1) NOT NULL,
PR_MARK_HEADER NUMBER(1) NOT NULL,
TLG_TYPE VARCHAR2(6) NOT NULL
);
