CREATE TABLE DROP_ARX_ETICKETS (
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
COUPON_NO NUMBER(1) NOT NULL,
COUPON_STATUS VARCHAR2(1),
ERROR VARCHAR2(100),
PART_KEY DATE NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
TICKET_NO VARCHAR2(15) NOT NULL
);
