CREATE TABLE DROP_GRP_RFISC_LISTS (
EMD_TYPE VARCHAR2(1),
LIST_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
NAME_LAT VARCHAR2(100) NOT NULL,
PR_CABIN NUMBER(1),
RFIC VARCHAR2(1),
RFISC VARCHAR2(15) NOT NULL,
SERVICE_TYPE VARCHAR2(1) NOT NULL
);
