CREATE TABLE DROP_ME3 (
BIRTH_DATE NUMBER(9),
EXPIRY_DATE NUMBER(9),
FIRST_NAME NUMBER(9),
FULL_EMPTY NUMBER(9),
GENDER NUMBER(9),
ISSUE_COUNTRY NUMBER(9),
NATIONALITY NUMBER(9),
NO NUMBER(9),
POINT_ID NUMBER(9),
SECOND_NAME NUMBER(9),
SURNAME NUMBER(9),
TYPE NUMBER(9)
);
