CREATE TABLE DROP_TEST_APIS4 (
DOC_SURNAME VARCHAR2(64) NOT NULL,
EDIT_DIST NUMBER(3) NOT NULL,
EDIT_DIST_FMT NUMBER(1) NOT NULL,
EDIT_DIST_SIM NUMBER(3) NOT NULL,
EDIT_DIST_SIM_FMT NUMBER(1) NOT NULL,
EDIT_DIST_VLAD NUMBER(3) NOT NULL,
EDIT_DIST_VLAD_FMT NUMBER(1) NOT NULL,
EDIT_DIST_VLAD_SIM NUMBER(3) NOT NULL,
EDIT_DIST_VLAD_SIM_FMT NUMBER(1) NOT NULL,
JARO_WINKLER_SIM NUMBER(3) NOT NULL,
JARO_WINKLER_SIM_FMT NUMBER(1) NOT NULL,
PAX_ID NUMBER(9) NOT NULL,
SURNAME VARCHAR2(64) NOT NULL
);
