CREATE TABLE EMDOCS_DISPLAY (
EMD_COUPON NUMBER(1) NOT NULL,
EMD_NO VARCHAR2(15) NOT NULL,
EMD_NO_BASE VARCHAR2(15) NOT NULL,
EMD_TYPE VARCHAR2(1) NOT NULL,
ET_COUPON NUMBER(1),
ET_NO VARCHAR2(15),
LAST_DISPLAY DATE NOT NULL,
RFIC VARCHAR2(1) NOT NULL,
RFISC VARCHAR2(15) NOT NULL,
SERVICE_NAME VARCHAR2(100) NOT NULL,
SERVICE_QUANTITY NUMBER(3),
SSR_CODE VARCHAR2(4)
);
