CREATE TABLE ETICKETS (
    AIRP_ARV VARCHAR2(3) NOT NULL,
    AIRP_DEP VARCHAR2(3) NOT NULL,
    COUPON_NO NUMBER(1) NOT NULL,
    COUPON_STATUS VARCHAR2(1),
    ERROR VARCHAR2(100),
    POINT_ID NUMBER(9) NOT NULL,
    SUBCLASS VARCHAR2(1),
    TICKET_NO VARCHAR2(15) NOT NULL
);
