CREATE TABLE ETICKS_DISPLAY_TLGS (
COUPON_NO NUMBER(1) NOT NULL,
LAST_DISPLAY DATE NOT NULL,
PAGE_NO NUMBER(9) NOT NULL,
TICKET_NO VARCHAR2(20) NOT NULL,
TLG_TEXT VARCHAR2(1000) NOT NULL,
TLG_TYPE NUMBER(1) NOT NULL
);
