CREATE TABLE FORM_TYPES (
BASIC_TYPE VARCHAR2(3) NOT NULL,
CODE VARCHAR2(7) NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
NAME_LAT VARCHAR2(100),
NO_LEN NUMBER(2) NOT NULL,
PR_CHECK_BIT NUMBER(1) NOT NULL,
SERIES_LEN NUMBER(1) NOT NULL,
VALIDATOR VARCHAR2(4) NOT NULL
);
