CREATE TABLE GRP_NORMS (
    AIRLINE VARCHAR2(3),
    BAG_TYPE NUMBER(2),
    BAG_TYPE_STR VARCHAR2(15),
    GRP_ID NUMBER(9) NOT NULL,
    HANDMADE NUMBER(1),
    LIST_ID NUMBER(9),
    NORM_ID NUMBER(9),
    NORM_TRFER NUMBER(1)
);
