CREATE TABLE HIST_AGENCIES (
CODE VARCHAR2(5) NOT NULL,
CODE_LAT VARCHAR2(5) NOT NULL,
DESCR VARCHAR2(100),
DESCR_LAT VARCHAR2(100),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
NAME_LAT VARCHAR2(100)
);
