CREATE TABLE HIST_OPERATORS (
AGENCY VARCHAR2(5) NOT NULL,
DESCR VARCHAR2(100) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
LOGIN VARCHAR2(12) NOT NULL,
PRIVATE_NUM NUMBER(4) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL,
VALIDATOR VARCHAR2(4) NOT NULL
);
