CREATE TABLE HIST_STAGE_SETS (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_AUTO NUMBER(1) NOT NULL,
STAGE_ID NUMBER(2) NOT NULL
);
