CREATE TABLE HIST_TYPEB_CREATE_POINTS (
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
STAGE_ID NUMBER(2) NOT NULL,
TIME_OFFSET NUMBER(4),
TYPEB_ADDRS_ID NUMBER(9) NOT NULL
);
