CREATE TABLE HIST_REM_TXT_SETS (
    AIRLINE VARCHAR2(3) NOT NULL,
    BRAND_AIRLINE VARCHAR2(3),
    BRAND_CODE VARCHAR2(10),
    FQT_AIRLINE VARCHAR2(3),
    FQT_TIER_LEVEL VARCHAR2(50),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    PR_LAT NUMBER(1) NOT NULL,
    RFISC VARCHAR2(15),
    TAG_INDEX NUMBER(1) NOT NULL,
    TEXT VARCHAR2(100) NOT NULL,
    TEXT_LENGTH NUMBER(2) NOT NULL
);
