CREATE TABLE HIST_LIBRA_CLASSES (
    AIRLINE VARCHAR2(3) NOT NULL,
    BORT VARCHAR2(10),
    CLASS VARCHAR2(1) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    LIBRA_CLASS VARCHAR2(1) NOT NULL
);
