CREATE TABLE HIST_TRIP_TYPES (
CODE VARCHAR2(1) NOT NULL,
CODE_LAT VARCHAR2(1),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PR_DEL NUMBER(1) NOT NULL,
PR_REG NUMBER(1) NOT NULL
);
