CREATE TABLE HIST_CUSTOM_ALARM_TYPES (
    AIRLINE VARCHAR2(3),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    NAME_LAT VARCHAR2(100) NOT NULL
);
