CREATE TABLE HIST_BALANCE_SETS (
AIRLINE VARCHAR2(3),
AIRP VARCHAR2(3) NOT NULL,
BALANCE_TYPE VARCHAR2(5) NOT NULL,
BORT VARCHAR2(10),
FLT_NO NUMBER(5),
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL
);
