CREATE TABLE HIST_TRIP_LIST_DAYS (
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
ROLE_ID NUMBER(9) NOT NULL,
SHIFT_DOWN NUMBER(3) NOT NULL,
SHIFT_UP NUMBER(3) NOT NULL
);
