CREATE TABLE HIST_INFO (
ALIGN VARCHAR2(1),
CHAR_CASE VARCHAR2(1),
DATA_SIZE NUMBER(4) NOT NULL,
DATA_TYPE VARCHAR2(3) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
NULLABLE NUMBER(1) NOT NULL,
NUM NUMBER(2) NOT NULL,
PR_IDENT NUMBER(1) NOT NULL,
READ_ONLY NUMBER(1) NOT NULL,
SCALE NUMBER(1),
TITLE VARCHAR2(100),
WIDTH NUMBER(4)
);
