CREATE TABLE HIST_POS_TERM_SETS (
    ADDRESS VARCHAR2(100),
    AIRLINE VARCHAR2(3),
    AIRP VARCHAR2(3),
    CLIENT_ID NUMBER(9) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    PR_DENIAL NUMBER(1) NOT NULL,
    SERIAL VARCHAR2(30) NOT NULL,
    SHOP_ID NUMBER(9) NOT NULL,
    VENDOR_ID NUMBER(9) NOT NULL
);
