CREATE TABLE HIST_SALE_DESKS (
CODE VARCHAR2(6) NOT NULL,
HIST_ORDER NUMBER(9) NOT NULL,
HIST_TIME DATE NOT NULL,
ID NUMBER(9) NOT NULL,
PR_DENIAL NUMBER(1) NOT NULL,
SALE_POINT VARCHAR2(8) NOT NULL,
VALIDATOR VARCHAR2(4) NOT NULL
);
