CREATE TABLE HIST_EDIFACT_PROFILES (
    CTRL_AGENCY VARCHAR2(2) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    SUB_VERSION VARCHAR2(3) NOT NULL,
    SYNTAX_NAME VARCHAR2(4) NOT NULL,
    SYNTAX_VER NUMBER NOT NULL,
    VERSION VARCHAR2(3) NOT NULL
);
