CREATE TABLE HIST_PAY_METHODS_SET (
    AIRLINE VARCHAR2(3),
    AIRP_DEP VARCHAR2(3),
    DESK VARCHAR2(6),
    DESK_GRP_ID NUMBER(9),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    METHOD_TYPE NUMBER(2) NOT NULL
);
