CREATE TABLE HIST_RFISC_BAG_PROPS (
    AIRLINE VARCHAR2(3) NOT NULL,
    CODE VARCHAR2(15) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    MAX_WEIGHT NUMBER(3),
    MIN_WEIGHT NUMBER(3),
    PRIORITY NUMBER(5),
    REM_CODE_LCI VARCHAR2(4),
    REM_CODE_LDM VARCHAR2(3)
);
