CREATE TABLE HIST_APIS_SETS (
    AIRLINE VARCHAR2(3) NOT NULL,
    COUNTRY_ARV VARCHAR2(2),
    COUNTRY_CONTROL VARCHAR2(2),
    COUNTRY_DEP VARCHAR2(2),
    DIR VARCHAR2(50),
    EDI_ADDR VARCHAR2(40),
    EDI_OWN_ADDR VARCHAR2(40),
    FORMAT VARCHAR2(10) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    PR_DENIAL NUMBER(1) NOT NULL,
    TRANSPORT_PARAMS VARCHAR2(250) NOT NULL,
    TRANSPORT_TYPE VARCHAR2(20) NOT NULL
);
