CREATE TABLE HIST_WEB_SALES (
    CLIENT_ID VARCHAR2(20) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    ST_DESK VARCHAR2(6) NOT NULL,
    ST_USER VARCHAR2(12) NOT NULL
);
