CREATE TABLE HIST_CACHE_TABLES (
CODE VARCHAR2(30) NOT NULL,
EVENT_TYPE VARCHAR2(3),
KEEP_DELETED_ROWS NUMBER(1) NOT NULL,
KEEP_LOCALLY NUMBER(1) NOT NULL,
LOGGING NUMBER(1) NOT NULL,
NEED_REFRESH NUMBER(1) NOT NULL,
PREPARE_SQL VARCHAR2(4000),
SELECT_SQL VARCHAR2(4000) NOT NULL,
TID NUMBER(9) NOT NULL,
TITLE VARCHAR2(100) NOT NULL
);
