CREATE TABLE HIST_TRANZIT_SET (
    AIRLINE VARCHAR2(3),
    AIRP_DEP VARCHAR2(3),
    BORT_CHANGING NUMBER(1) NOT NULL,
    BRD_WITH_AUTOREG NUMBER(1) NOT NULL,
    FLT_NO NUMBER(5),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    PR_REG NUMBER(1) NOT NULL,
    PR_TRANZIT NUMBER(1) NOT NULL
);
