CREATE TABLE HIST_ET_ADDR_SET (
    AIRLINE VARCHAR2(3) NOT NULL,
    EDIFACT_PROFILE VARCHAR2(30),
    EDI_ADDR VARCHAR2(20) NOT NULL,
    EDI_ADDR_EXT VARCHAR2(20),
    EDI_OWN_ADDR VARCHAR2(20) NOT NULL,
    EDI_OWN_ADDR_EXT VARCHAR2(20),
    FLT_NO NUMBER(5),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL
);
