CREATE TABLE HIST_TIMATIC_SETS (
    AIRLINE VARCHAR2(3),
    AIRP VARCHAR2(3),
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    HOST VARCHAR2(200) NOT NULL,
    ID NUMBER(9),
    PORT NUMBER(5) NOT NULL,
    PR_DENIAL NUMBER(1) NOT NULL,
    PWD VARCHAR2(200) NOT NULL,
    SUB_USERNAME VARCHAR2(200) NOT NULL,
    USERNAME VARCHAR2(200) NOT NULL
);
