CREATE TABLE HIST_BCBP_REPRINT_OPTIONS (
    AIRLINE VARCHAR2(3),
    AIRP VARCHAR2(3),
    DESK VARCHAR2(6),
    DESK_GRP NUMBER(9) NOT NULL,
    HIST_ORDER NUMBER(9) NOT NULL,
    HIST_TIME DATE NOT NULL,
    ID NUMBER(9) NOT NULL,
    LOWER_SHIFT NUMBER(3) NOT NULL,
    UPPER_SHIFT NUMBER(3) NOT NULL
);
