CREATE TABLE HOTEL_ACMD (
    AIRLINE VARCHAR2(3),
    AIRP VARCHAR2(3) NOT NULL,
    DOUBLE_AMOUNT NUMBER(9) NOT NULL,
    HOTEL_NAME VARCHAR2(100) NOT NULL,
    ID NUMBER(9) NOT NULL,
    SINGLE_AMOUNT NUMBER(9) NOT NULL
);
