CREATE TABLE IAPI_PAX_DATA (
COUNTRY_CONTROL VARCHAR2(2) NOT NULL,
FREE_TEXT VARCHAR2(100),
MSG_ID VARCHAR2(70) NOT NULL,
PAX_ID NUMBER NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PR_DEL NUMBER(1) NOT NULL,
STATUS VARCHAR2(2)
);
