CREATE TABLE IATCI_SETTINGS (
BPR NUMBER(1) NOT NULL,
CKI NUMBER(1) NOT NULL,
CKU NUMBER(1) NOT NULL,
CKX NUMBER(1) NOT NULL,
DCS_ID NUMBER(9) NOT NULL,
IFM NUMBER(1) DEFAULT 0 NOT NULL,
PLF NUMBER(1) NOT NULL,
SMF NUMBER(1) NOT NULL
);
