create table LIBRA_LOG_EVENTS (
    AIRLINE VARCHAR2(3),
    BORT_NUM VARCHAR2(10),
    CATEGORY VARCHAR2(30),
    EV_ORDER NUMBER(9) NOT NULL,
    EV_STATION VARCHAR2(15) NOT NULL,
    EV_USER VARCHAR2(20) NOT NULL,
    LAT_MSG VARCHAR2(1000) NOT NULL,
    LOG_TIME DATE NOT NULL,
    LOG_TYPE VARCHAR2(3) NOT NULL,
    POINT_ID NUMBER(9),
    RUS_MSG VARCHAR2(1000) NOT NULL
);
