CREATE TABLE MPS_EXCHANGE (
    GRP_ID NUMBER(9) NOT NULL,
    METHOD VARCHAR2(20) NOT NULL,
    ORDER_ID VARCHAR2(9) NOT NULL,
    PAGE_NO NUMBER(3) NOT NULL,
    REQUEST_TYPE VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    TIME_CREATE DATE NOT NULL,
    XML VARCHAR2(4000) NOT NULL
);
