CREATE TABLE PAID_BAG_EMD_PROPS (
    EMD_COUPON NUMBER(1) NOT NULL,
    EMD_NO VARCHAR2(15) NOT NULL,
    GRP_ID NUMBER(9) NOT NULL,
    MANUAL_BIND NUMBER(1) NOT NULL,
    NOT_AUTO_CHECKIN NUMBER(1) NOT NULL
);
