CREATE TABLE PAID_BAG (
    AIRLINE VARCHAR2(3) NOT NULL,
    BAG_TYPE NUMBER(2),
    BAG_TYPE_STR VARCHAR2(15),
    GRP_ID NUMBER(9) NOT NULL,
    HANDMADE NUMBER(1),
    LIST_ID NUMBER(9) NOT NULL,
    RATE_ID NUMBER(9),
    RATE_TRFER NUMBER(1),
    WEIGHT NUMBER(6) NOT NULL
);
