CREATE TABLE PAX_EVENTS (
    DESK VARCHAR2(6) NOT NULL,
    EV_ORDER NUMBER(9) NOT NULL,
    PAX_EVENT VARCHAR2(10) NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    STATION VARCHAR2(6),
    TIME DATE NOT NULL
);
