CREATE TABLE PAX_DOC_TYPES (
    CODE VARCHAR2(2) NOT NULL,
    CODE_MINTRANS VARCHAR2(2) NOT NULL,
    IS_DOCO_TYPE NUMBER(1) NOT NULL,
    IS_DOCS_TYPE NUMBER(1) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    NAME_LAT VARCHAR2(100)
);
