CREATE TABLE PAX_ASVC (
    EMD_COUPON NUMBER(1),
    EMD_NO VARCHAR2(15),
    EMD_TYPE VARCHAR2(1),
    PAX_ID NUMBER(9) NOT NULL,
    RFIC VARCHAR2(1) NOT NULL,
    RFISC VARCHAR2(15) NOT NULL,
    SERVICE_NAME VARCHAR2(30) NOT NULL,
    SERVICE_QUANTITY NUMBER(3) NOT NULL,
    SSR_CODE VARCHAR2(4)
);
