CREATE TABLE PAX_REM_ORIGIN (
    DESK VARCHAR2(6) NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    REM VARCHAR2(250),
    REM_CODE VARCHAR2(4) NOT NULL,
    TIME_CREATE DATE NOT NULL,
    USER_ID NUMBER(9) NOT NULL
);
