CREATE TABLE PAX_DOC_COUNTRIES (
CODE VARCHAR2(3) NOT NULL,
COUNTRY VARCHAR2(2),
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(250) NOT NULL,
NAME_LAT VARCHAR2(250),
PR_DEL NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL
);
