CREATE TABLE PAX_TRANSLIT (
    GRP_ID NUMBER(9) NOT NULL,
    NAME VARCHAR2(64),
    PAX_ID NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    SURNAME VARCHAR2(64) NOT NULL,
    TRANSLIT_FORMAT NUMBER(1) NOT NULL
);
