CREATE TABLE PAY_CLIENTS (
    AIRLINE VARCHAR2(3),
    AIRP_DEP VARCHAR2(3),
    CLIENT_ID NUMBER(5) NOT NULL,
    ID NUMBER(9) NOT NULL,
    PACT VARCHAR2(100) NOT NULL,
    PR_DENIAL NUMBER(1) NOT NULL
);
