CREATE TABLE PFS_STAT (
    AIRP_ARV VARCHAR2(3) NOT NULL,
    BIRTH_DATE DATE,
    GENDER VARCHAR2(2),
    NAME VARCHAR2(64),
    PAX_ID NUMBER(9) NOT NULL,
    PNR VARCHAR2(50),
    POINT_ID NUMBER(9) NOT NULL,
    SEATS NUMBER(1) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SUBCLS VARCHAR2(1) NOT NULL,
    SURNAME VARCHAR2(64) NOT NULL
);
