CREATE TABLE PNR_MARKET_FLT (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
FLT_NO NUMBER(5) NOT NULL,
LOCAL_DATE NUMBER(2) NOT NULL,
PNR_ID NUMBER(9) NOT NULL,
SUBCLASS VARCHAR2(1) NOT NULL,
SUFFIX VARCHAR2(1)
);
