CREATE TABLE REFUSAL_TYPES (
CODE VARCHAR2(1) NOT NULL,
CODE_LAT VARCHAR2(1),
ID NUMBER(9) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
PR_DEL NUMBER(1) NOT NULL,
TID NUMBER(9) NOT NULL
);
