CREATE TABLE RFISC_RATES (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP_ARV VARCHAR2(3),
    AIRP_DEP VARCHAR2(3),
    BRAND VARCHAR2(10) NOT NULL,
    ID NUMBER(9) NOT NULL,
    RATE NUMBER(12,2) NOT NULL,
    RATE_CUR VARCHAR2(3) NOT NULL,
    RFISC VARCHAR2(15) NOT NULL,
    SALE_FIRST_DATE DATE NOT NULL,
    SALE_LAST_DATE DATE
);
