CREATE TABLE RFISC_SETS (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP_DEP VARCHAR2(3),
    AUTO_CHECKIN NUMBER(1) NOT NULL,
    FLT_NO NUMBER(5),
    ID NUMBER(9) NOT NULL,
    RFIC VARCHAR2(1) NOT NULL,
    RFISC VARCHAR2(15)
);
