CREATE TABLE SBDO_TAGS_GENERATED (
    AIRLINE VARCHAR2(3) NOT NULL,
    BAG_TYPE VARCHAR2(15),
    DEACTIVATED NUMBER(1) NOT NULL,
    LIST_ID NUMBER(9) NOT NULL,
    NO NUMBER(15) NOT NULL,
    PAX_ID NUMBER(9) NOT NULL,
    RFISC VARCHAR2(15),
    SBDO_TYPE VARCHAR2(10) NOT NULL,
    SERVICE_TYPE VARCHAR2(20),
    WEIGHT NUMBER(4) NOT NULL
);
