CREATE TABLE SBM_PROFILES (
    ACK_MSG_TIMEOUT NUMBER NOT NULL,
    CANON_NAME VARCHAR2(10) NOT NULL,
    HEARTBEAT_INTERVAL NUMBER NOT NULL,
    HEARTBEAT_TIMEOUT NUMBER NOT NULL,
    HOST1 VARCHAR2(20) NOT NULL,
    HOST2 VARCHAR2(20) NOT NULL,
    LOGIN VARCHAR2(20) NOT NULL,
    LOGIN_TIMEOUT NUMBER NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    PORT1 NUMBER NOT NULL,
    PORT2 NUMBER NOT NULL,
    WARM_UP_TIMEOUT NUMBER NOT NULL
);
