CREATE TABLE SEAT_REM_LAYERS (
    AIRLINE_MARK VARCHAR2(3),
    LAYER_WITHOUT_ASVC VARCHAR2(10),
    LAYER_WITH_ASVC_HI VARCHAR2(10),
    LAYER_WITH_ASVC_HK VARCHAR2(10),
    REM_CODE VARCHAR2(4) NOT NULL
);
