CREATE TABLE SERVICE_PAYMENT (
    AIRLINE VARCHAR2(3) NOT NULL,
    BAG_TYPE VARCHAR2(15),
    DOC_AIRCODE VARCHAR2(3),
    DOC_COUPON NUMBER(1),
    DOC_NO VARCHAR2(15) NOT NULL,
    DOC_TYPE VARCHAR2(5) NOT NULL,
    DOC_WEIGHT NUMBER(6),
    GRP_ID NUMBER(9) NOT NULL,
    LIST_ID NUMBER(9) NOT NULL,
    PAX_ID NUMBER(9),
    RFISC VARCHAR2(15),
    SERVICE_QUANTITY NUMBER(3) NOT NULL,
    SERVICE_TYPE VARCHAR2(1),
    TRANSFER_NUM NUMBER(1) NOT NULL
);
