CREATE TABLE STAT_ZAMAR (
    AIRLINE VARCHAR2(3) NOT NULL,
    AIRP VARCHAR2(3) NOT NULL,
    AMOUNT_FAULT NUMBER(9) NOT NULL,
    AMOUNT_OK NUMBER(9) NOT NULL,
    SBDO_TYPE VARCHAR2(10) NOT NULL,
    TIME DATE NOT NULL
);
