CREATE TABLE TIMATIC_SESSION (
    EXPIRE DATE NOT NULL,
    HOST VARCHAR2(200) NOT NULL,
    JSESSIONID VARCHAR2(200),
    PORT NUMBER(5) NOT NULL,
    PWD VARCHAR2(200) NOT NULL,
    SESSIONID VARCHAR2(200),
    SUB_USERNAME VARCHAR2(200) NOT NULL,
    USERNAME VARCHAR2(200) NOT NULL
);
