CREATE TABLE TLG_TRFER_ONWARDS (
AIRLINE VARCHAR2(3) NOT NULL,
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
FLT_NO NUMBER NOT NULL,
GRP_ID NUMBER(9) NOT NULL,
LOCAL_DATE DATE NOT NULL,
NUM NUMBER(1) NOT NULL,
SUBCLASS VARCHAR2(1),
SUFFIX VARCHAR2(20)
);
