CREATE TABLE TRFER_PAX_STAT (
    BAG_AMOUNT NUMBER(9),
    BAG_WEIGHT NUMBER(9),
    PAX_ID NUMBER(9) NOT NULL,
    POINT_ID NUMBER(9) NOT NULL,
    RK_WEIGHT NUMBER(9),
    SCD_OUT DATE NOT NULL,
    SEGMENTS VARCHAR2(4000) NOT NULL
);
