CREATE TABLE TRIP_LOAD (
AIRP_ARV VARCHAR2(3) NOT NULL,
AIRP_DEP VARCHAR2(3) NOT NULL,
CARGO NUMBER(9) NOT NULL,
MAIL NUMBER(9) NOT NULL,
POINT_ARV NUMBER(9) NOT NULL,
POINT_DEP NUMBER(9) NOT NULL
);
