CREATE TABLE TRIP_COMP_ELEMS (
AGLE NUMBER(3) NOT NULL,
CLASS VARCHAR2(1),
ELEM_TYPE VARCHAR2(1) NOT NULL,
NOT_GOOD NUMBER(1),
NUM NUMBER(2) NOT NULL,
POINT_ID NUMBER(9) NOT NULL,
PR_SMOKE NUMBER(1),
X NUMBER(3) NOT NULL,
XNAME VARCHAR2(4),
XPRIOR NUMBER(3),
Y NUMBER(3) NOT NULL,
YNAME VARCHAR2(4),
YPRIOR NUMBER(3)
);
