CREATE TABLE TYPEB_OUT_ERRORS (
ERROR_LEN NUMBER(9) NOT NULL,
ERROR_NO NUMBER(9) NOT NULL,
ERROR_POS NUMBER(9) NOT NULL,
LANG VARCHAR2(2) NOT NULL,
PART_NO NUMBER(5),
TEXT VARCHAR2(250) NOT NULL,
TLG_ID NUMBER(9) NOT NULL
);
