CREATE TABLE USER_SET_TYPES (
CATEGORY VARCHAR2(10) NOT NULL,
CODE NUMBER(2) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NAME_LAT VARCHAR2(50),
SHORT_NAME VARCHAR2(20) NOT NULL,
SHORT_NAME_LAT VARCHAR2(20)
);
