#include "astra_msg.h"

#define REGERR(x,e,r) ADDERR(AstraErr,x,e,r)
#define REGMSG(x,e,r) ADDMSG(AstraMsg,x,e,r)

namespace Ticketing
{

REGERR(TIMEOUT_ON_HOST_3,
       "Timeout occured on host 3",
       "’ ©¬ ãâ")
REGERR(EDI_PROC_ERR,
       "UNABLE TO PROCESS - SYSTEM ERROR",
       "…‚Ž‡ŒŽ†Ž Ž€Ž’€’œ - ‘ˆ‘’…Œ€Ÿ Ž˜ˆŠ€")
REGERR(EDI_INV_MESSAGE_F,
       "MESSAGE FUNCTION INVALID",
       "…‚…€Ÿ ”“Š–ˆŸ ‘ŽŽ™…ˆŸ")
REGERR(EDI_NS_MESSAGE_F,
       "MESSAGE FUNCTION NOT SUPPORTED",
       "”“Š–ˆŸ ‘ŽŽ™…ˆŸ … Ž„„…†ˆ‚€…’‘Ÿ")
REGERR(EDI_SYNTAX_ERR,
       "EDIFACT SYNTAX MESSAGE ERROR",
       "‘ˆ’€Š‘ˆ—…‘Š€Ÿ Ž˜ˆŠ€ ‚ ‘ŽŽ™…ˆˆ EDIFACT")
REGERR(PAX_SURNAME_NF,
       "PASSENGER SURNAME NOT FOUND",
       "”€Œˆ‹ˆŸ €‘‘€†ˆ€ … €‰„…€")
REGERR(INV_FLIGHT_DATE,
       "INVALID FLIGHT/DATE",
       "…‚…›‰ …‰‘/„€’€")
REGERR(TOO_MANY_PAX_WITH_SAME_SURNAME,
       "TOO MANY PASSENGERS WITH SAME SURNAME",
       "…‚›˜… ‹ˆŒˆ’ €€‘€†ˆŽ‚ ‘ Ž„ˆ€ŠŽ‚Ž‰ ”€Œˆ‹ˆ…‰")
REGERR(FLIGHT_NOT_FOR_THROUGH_CHECK_IN,
       "FLIGHT NOT OPEN FOR THROUGH CHECK-IN",
       "‘Š‚Ž‡€Ÿ …ƒˆ‘’€–ˆŸ …„Ž“‘’ˆŒ€ „‹Ÿ …‰‘€")
REGERR(PAX_ALREADY_CHECKED_IN,
       "PASSENGER SURNAME ALREADY CHECKED IN",
       "€‘‘€†ˆ ‘ “Š€‡€Ž‰ ”€Œˆ‹ˆ…‰ “†… ‡€…ƒˆ‘’ˆŽ‚€")
REGERR(BAGGAGE_WEIGHT_REQUIRED,
       "BAGGAGE WEIGHT REQUIRED",
       "’…“…’‘Ÿ ‚…‘ €ƒ€†€")
REGERR(NO_SEAT_SELCTN_ON_FLIGHT,
       "NO SEAT SELECTION ON THIS FLIGHT",
       "Ž’‘“’‘’‚“…’ ‚Ž‡ŒŽ†Ž‘’œ ‚›Ž€ Œ…‘’€ € …‰‘…")
REGERR(TOO_MANY_PAXES,
       "TOO MANY PASSENGERS",
       "…‚›˜… ‹ˆŒˆ’ €‘‘€†ˆŽ‚")
REGERR(TOO_MANY_INFANTS,
       "TOO MANY INFANTS",
       "…‚›˜… ‹ˆŒˆ’ Œ‹€„…–…‚")
REGERR(SMOKING_ZONE_UNAVAILABLE,
       "SMOKING ZONE UNAVAILABLE",
       "‡Ž€ „‹Ÿ Š“Ÿ™ˆ• …„Ž‘’“€")
REGERR(NON_SMOKING_ZONE_UNAVAILABLE,
       "NON-SMOKING ZONE UNAVAILABLE",
       "‡Ž€ „‹Ÿ …Š“Ÿ™ˆ• …„Ž‘’“€")
REGERR(PAX_SURNAME_NOT_CHECKED_IN,
       "PASSENGER SURNAME NOT CHECKED-IN",
       "€‘‘€†ˆ ‘ “Š€‡€Ž‰ ”€Œˆ‹ˆ…‰ … ‡€…ƒˆ‘’ˆŽ‚€")
REGERR(CHECK_IN_SEPARATELY,
       "CHECK-IN SEPARATELY",
       "’…“…’‘Ÿ €‡„…‹œ€Ÿ …ƒˆ‘’€–ˆŸ")
REGERR(UPDATE_SEPARATELY,
       "UPDATE SEPARATELY",
       "’…“…’‘Ÿ €‡„…‹œŽ… ŽŽ‚‹…ˆ…")
REGERR(CASCADED_QUERY_TIMEOUT,
       "CASCADED QUERY TIMED OUT",
       "’€‰Œ€“’ Š€‘Š€„ŽƒŽ ‡€Ž‘€")
REGERR(ID_CARD_REQUIRED,
       "PASSPORT/ID DOCUMENT DATA REQUIRED",
       "’…“…’‘Ÿ ŽŒ… €‘Ž’€/„ŽŠ“Œ…’€")

}//namespace Ticketing
