#!/bin/sh
if [  -z "$1" ] ; then
	port=`awk '/tclmode/ {print $3}' sirena.pid`
else
	port=$1
fi
if [ -z "$port" ] ; then
	kill -2 `cat sirena.pid`
else
(sleep 2 ; cat <<EOF ; sleep 2 )|
stop_obr all
EOF
telnet localhost $port
fi

