#!/bin/sh


for i in /bin/nawk /usr/bin/nawk /bin/awk /usr/bin/awk /usr/bin/gawk \
/usr/local/bin/gawk /usr/local/bin/nawk ; do
	if [ -f $i ] ; then
	 	AWK=$i 
		break
    fi
done
if [ "" == "$AWK" ] ; then
    echo no awk
    exit 1
fi

if [ -z "$1" ]; then 
	LOGLIST="astra  daemon  logairimp  monitor  system  tclmon";
else
	LOGLIST="$@"
fi
 
for i in $LOGLIST ; do
 	mv $i.log $i.moved	
done

PS | $AWK '/monitor|logger|astra/ {print $2}' | xargs kill -USR1
