SAVECC:=$(CC)
SAVECXX:=$(CXX)
include $(SRCHOME)/oracle.mk
CC:=$(SAVECC)
CXX:=$(SAVECXX)
OTHERINCLUDES=$(LIBXML2INCLUDE) $(BOOST_INCLUDE)
COMPFLAGS2=-DTCL_MODE $(EDILIBMODE) $(EDIINC) $(ORACLE_INCLUDE) -I$(SRCHOME) \
           $(OP_CFLAGS) $(XML) $(OTHERINCLUDES) \
           $(shell $(SERVERLIB_PATH)/serverlib-config --cflags)
COMPFLAGS=$(COMPFLAGS2) $(LOCALFLAGS)
CPPCOMPFLAGS=$(CPPINCLUDE) 

