#ifndef __MONCMD_H__
 #define __MONCMD_H__
  #define MONCMD_HELP    "help"
  #define MONCMD_CTRL    "ctrl"
  #define MONCMD_SHOW    "show"
  #define MONCMD_EXIT    "exit"
  #define MONCMD_QUIT    "quit"
  #define MONCMD_SYSTEMINFO "PS_system"
  #define MONCMD_PROC_BRIEFINFO "PS"
  #define MONCMD_PROC_FULLINFO "PS_show_all"
  #define MONCMD_PROC_CMD     "proccmd"
  #define MONCMD_PROC_GRP_CMD "proc_grp_cmd"
  #define MONCMD_PROC_START   "start_obr"
  #define MONCMD_PROC_RESTART "restart_obr"
  #define MONCMD_PROC_RESTART_PARALL "all"
  #define MONCMD_PROC_RESTART_HANDLERS "handlers"
  #define MONCMD_PROC_STOP    "stop_obr"
  #define MONCMD_PROC_STOP_PARALL    "all"
  #define MONCMD_PROC_STOP_PARSEL    "obr"
  #define MONCMD_SHOW_TCLBUFS    "show_bufs"

  #define ARRCMD_DELETE_ARR_NO        "delete_arr_no"
  #define ARRCMD_CREATE_ARR_NO        "create_arr_no"
  #define ARRCMD_SET_START_ARR_NO     "set_start_arr_no"
  #define ARRCMD_SET_STOP_ARR_NO      "set_stop_arr_no"
  #define ARRCMD_SET_ACTION_ARR_NO    "set_action_arr_no"
  #define ARRCMD_RESET_N_START_ARR_NO "reset_n_start_arr_no"
  #define ARRCMD_GET_CMDS_ARR_NO      "get_cmds_arr_no"
  #define ARRCMD_GET_HANDLERS_GROUP_ARR_NO "get_handlers_group_arr_no"
  #define ARRCMD_GET_NAME_ARR_NO      "get_name_arr_no"
  #define ARRCMD_PS_SHOW              "PS_show"
  #define ARRCMD_SET_FLAG_ARR_NO      "set_flag_arr_no"
  #define ARRCMD_TEST_RESTART_PROC    "arr_test_restart_proc"
  #define ARRCMD_TEST_NOT_ASKED_PROC  "arr_test_not_asked_proc"
  #define ARRCMD_SET_QUEUE_SIZE       "arr_set_queue_size_proc"
  #define ARRCMD_GET_QUEUE_SIZE       "arr_get_queue_size_proc"
  #define ARRCMD_GET_QUEUE_SIZE_FOR_LOG "arr_get_queue_size_proc_for_log"
  #define ARRCMD_SET_CUR_REQ            "arr_set_cur_req_proc"
  #define ARRCMD_CLEAR_CUR_REQ          "arr_clear_cur_req_proc"
  #define ARRCMD_GET_CUR_REQ          "arr_get_cur_req_proc"
  #define ARRCMD_FIND_PROC_FOR_STOP "find_proc_for_stop"
#endif /* ! __MONCMD_H__ */
