#!/bin/bash

shopt -s extglob

get_distro_name()
{
    local redhat=redhat
    local ubuntu=ubuntu
    declare result;
    
    if ! [[ -z $(which lsb_release 2> /dev/null) ]]; then
        vendor=$(lsb_release -i | cut -b17-)
        if [ `echo $vendor | grep RedHatEnterpriseServer` ]; then
            result=$redhat
        elif [[ `echo $vendor | grep Ubuntu` ]]; then
            result=$ubuntu
        fi;
    fi;
    
    if [[ -z $result ]]; then
        rpm=$(which rpm 2> /dev/null)
        dpkg=$(which dpkg 2> /dev/null)
    
        if [[ -n $rpm ]]; then
            result=$redhat
        fi;

        if [[ -n $dpkg ]]; then
            result=$ubuntu
        fi;
    fi;

    echo $result
}

get_distro_bit()
{
    case $(uname -m | awk '{print tolower($0)}') in
      @(i[76543]86|x86|ia-32) )
        echo 32;
      ;;
      @(x86_64|x86-64|x64|amd64|intel 64|ia-32e|em64t) )
        echo 64;
      ;;
    esac
}

apply_host_script()
{
    local script=$(get_distro_name)
    apply_script $script

    define_empty_func apply_host_script
}

os()
{
    local what=$1
    local prefix=$2

    case $1 in
        libc)
            echo $(get_host_libc_path $prefix)
        ;;
        include)
            echo $(get_host_include_path $prefix)
        ;;
    esac;
}

apply_host_script;

